### ISSUE TITLE
Issues with Fitbit

### ISSUE THREAD

**Issue by AustinErck** [p2/OAuth2#101]
When using this library with Xcode 7.3. It all works until you get to the allow button. Upon clicking it you get a popup saying "Safari cannot open the page because the address invalid". I have been unable to find a fix.

AppDelegate
```
var oauth2 = OAuth2CodeGrant(settings:[
                                    "client_id": "hidden",
                                    "client_secret": "hidden",
                                    "authorize_uri": "https://www.fitbit.com/oauth2/authorize",
                                    "token_uri": "https://api.fitbit.com/oauth2/token",   // code grant only
                                    "scope": "profile activity",
                                    "redirect_uris": ["projectgrizzly://oauth/callback"],   // don't forget to register this scheme
                                    "keychain": true,     // if you DON'T want keychain integration
                                ] as OAuth2JSON)
 
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        
        oauth2.onAuthorize = { parameters in
            print("Did authorize with parameters: \(parameters)")
        }
        oauth2.onFailure = { error in        // `error` is nil on cancel
            if let error = error {
                print("Authorization went wrong: \(error)")
            }
        }
        
        return true
    }
```

Button that starts process
```
@IBAction func testButtonYo(sender: UIButton) {
        let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
        appDelegate.oauth2.authorize()
    }
```

**Comment by p2** [comment]
Is `projectgrizzly` registered in your app's `Info.plist`? Is this the URL that Safari is trying to open but ultimately fails?

**Comment by AustinErck** [comment]
Yeah that is what I thought. In my Info.plist I have "Information Property Types">"URL Types">"Item 0">"URL Identifier" that is set to "projectgrizzly://oauth/callback"

**Comment by p2** [comment]
You only have to provide the scheme, so only put `projectgrizzly` there. Does this solve the issue?

**Comment by AustinErck** [comment]
That fixed it, thank you! Also I need a way to essentially reset the entire login process each time so I can debug it. I tried having a button that runs forgetClient() but when I login and run activate it still has me logged in.

**Comment by p2** [comment]
You can check whether `oauth.accessToken` is not nil/empty, but that is no guarantee the token is still valid. You can just call `authorize()`, it will not prompt the user if there already is an access or a refresh token.

**Comment by AustinErck** [comment]
Ok, I have it working for the most part now with hasExpiredAccessToken and it seems to work. Lastly and this might be just an Xcode thing, but when opening a view controller, it immediately checks to see if the user is logged in. If they are not it opens a login activity. The thing I'm having an issue with is after they hit a button on login that runs `authorize()` followed by `dismissViewControllerAnimated(true, completion: nil)` authorize logs them in but because i dismiss the the activity immediately it checks to see if they are logged in immediately and since it hasn't yet it opens another instance of login. Essentially what I'm asking is there a way I can call `dismissViewControllerAnimated(true, completion: nil)` as soon as the authorization is completed? Preferably successfully? 

Thank you for your help, I'm new to Swift and iOS development and working with server's is not my strong suit in any language.

**Comment by p2** [comment]
If you're using the standard way to authorize, you don't need to dismiss the view controller yourself, you can just do this:

```
oauth2.authorizeEmbeddedFrom(<# presenting view controller #>)
```

This will automatically dismiss the view controller for you when done. Does that not work for you?
