### ISSUE TITLE
Google on iOS can use SFSafariViewController

### ISSUE THREAD

**Issue by WilliamDenniss** [p2/OAuth2#102]
The [current instructions](https://github.com/p2/OAuth2#google) for Google:

> If you authorize against Google with a OAuth2CodeGrant, the built-in iOS web view will intercept the http://localhost as well as the urn:ietf:wg:oauth:2.0:oob (with or without :auto) callbacks. This means you must disable the Safari view controller and – for now – this only works on iOS.

are not accurate. Google supports OAuth flows in a SFSafariViewController. If you [register](https://console.developers.google.com/apis/credentials?project=_) the OAuth client as an iOS client, a custom URI scheme is automatically provisioned for the redirect, and is the reverse DNS form of the client-id. No client secrets are required for such clients.

For example, if the Google iOS client ID is `YOUR_CLIENT.apps.googleusercontent.com`, the custom scheme that you add to the project's `Info.plist` would be `com.googleusercontent.apps.YOUR_CLIENT`. A path component is added resulting in `com.googleusercontent.apps.YOUR_CLIENT:/oauthredirect` as the OAuth redirect.

**Comment by p2** [comment]
Ah very cool, thanks for sharing. I hadn't seen that option when I tried Google, not sure whether I missed it or whether it's a recent addition.
