### ISSUE TITLE
Making functions public

### ISSUE THREAD

**Issue by mwolski89** [p2/OAuth2#103]
It would be great to have some functions accessible from public, because they are currently implicit 'internal' and I cannot sublcass and override some methods e.g. from OAuth2GrantCode.swift. That's because I am importing it as a framework, so 'internal' accessible for me.

**Comment by p2** [comment]
The original intent was to make the included classes cover all "legal" use-cases of OAuth2 so that subclasses would not be necessary. Which internal function would you need to be external? And for which service provider?

**Comment by p2** [comment]
@mwolski89 can you let me know which methods you wish to override (and to what end)?

**Comment by ChrisTitos** [comment]
In my case we have a custom oauth grant for our own service. It's pretty much the same as the password grant except the parameters are named differently.
So we thought we could simply copy the OAuth2PasswordGrant class and make the small changes, but we can't override `doAuthorize`

**Comment by p2** [comment]
@ChrisTitos in your case you'd just override `parseAccessTokenResponse()`, though. That one is also not public.

Ok, I'll write a call-graph so people can orient themselves about what's happening, and make some methods public that I think may make sense hooking in to. 👍🏼

**Comment by p2** [comment]
Call graph is here:
https://github.com/p2/OAuth2/wiki/Call-Graph

**Comment by p2** [comment]
@ChrisTitos I've pushed 2.2.7 that allows you to override `normalizeAccessTokenResponseKeys()`. Use it to convert your custom keys to the ones that are expected by OAuth2.

**Comment by p2** [comment]
I've also made `didAuthorize(parameters:)` and `didFail(error:)` public, but marked as final. These can now be called in subclasses, but should be used cautiously to avoid double-calls and such.

I'll mark this issue resolved, if anybody needs another method opened up re-open the issue!
