### ISSUE TITLE
Question about embedded authorization with SFSafariViewController

### ISSUE THREAD

**Issue by tylerswartz** [p2/OAuth2#104]
Hi Pascal - Apple is now rejecting apps that use the safari oauth flow. They advised me to use the new SFSafariViewController to embed the authorization.

Looking at the readme I'm having trouble figuring out what exactly I need to do to trigger the embedded authorization.  I saw these two section on embedding authorization, but I don't understand if I need to combine them, etc. 
```
// for embedded authorization you can just use:
oauth2.authorizeEmbeddedFrom(<# presenting view controller / window #>)
```
and:
```
let web = oauth2.authorizeEmbeddedWith(<# presenting view controller #>)
oauth2.authConfig.authorizeEmbeddedAutoDismiss = false
oauth2.afterAuthorizeOrFailure = { wasFailure, error in
    web.dismissViewControllerAnimated(true, completion: nil)
}
```
Below is my code for oauth. It triggers `storing tokens to keychain`, but nothing after that and no embedded view. Can you help, or do you know of a good blog that covers it? Thanks a lot for the help 😀

```
import SafariServices

@IBAction func loginBtn(sender: AnyObject) {

     let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
            
     // what I was originally using
     // let url = try appDelegate.oauth2.authorizeURL()
     // UIApplication.sharedApplication().openURL(url)

     // new for embedding
     appDelegate.oauth2.authorizeEmbeddedFrom(MyViewController)

            
     appDelegate.oauth2.onAuthorize = { parameters in
          //successful authorization and show paramters from Uber
          print("Did authorize with parameters: \(parameters)")
      }
            
      appDelegate.oauth2.onFailure = { error in        // `error` is nil on cancel
          if nil != error {
              //show error
              print("Authorization went wrong: \(error)")
          }
      }
}
```

**Comment by tylerswartz** [comment]
Forgot to mention, I'm using version 2.2.1

**Comment by p2** [comment]
Is `MyViewController` an actual view controller or the name of a class? In needs to be the former (and usually you just pass `self`). The _OAuth2PodApp_ is an iOS sample app, and [its main view controller](https://github.com/p2/OAuth2PodApp/blob/master/OAuth2PodApp/ViewController.swift#L42) shows how this can be done.

Latest version is 2.2.5, should be safe to update.

**Comment by tylerswartz** [comment]
Thanks @p2, that example app is super helpful. Got it working. Submitting it back to the app store!

**Comment by p2** [comment]
Great!
