### ISSUE TITLE
How to allow invalid certificates (e.g: localhost/127.0.0.1)

### ISSUE THREAD

**Issue by mistre83** [p2/OAuth2#108]
I have write an OAuth2 server using NodeJS over HTTPS but when p2.OAuth2 request the access token i got:

he certificate for this server is invalid. You might be connecting to a server that is pretending to be “127.0.0.1” which could put your confidential information at risk.

There is a way to setup OAuth2CodeGrant(settings:) to allow invalid certificates ? In future, my server will not be in localhost and i will access it with a real DNS but however the server will not have a trusted certificate (will be a private server).

Thanks in advice

**Comment by p2** [comment]
Yes, you can do this:

```swift
oauth2.sessionDelegate = OAuth2DebugURLSessionDelegate(host: ...)
```

This delegate will accept any authentication challenge from the given host. See [OAuth2Request.swift:53](https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2Request.swift#L53)
