### ISSUE TITLE
Authorising with google api

### ISSUE THREAD

**Issue by plspalding** [p2/OAuth2#109]
I am currently having issues authorising my app with the google api. I have posted a question on Stackoverflow which can be found here: http://stackoverflow.com/questions/37187874/authenticating-with-oauth2-on-ios

Any help would be much appreciated.

**Comment by p2** [comment]
See my response there:

> Set `oauth2.verbose = true` on your OAuth2 instance and post the log, it should tell you what it does with the keychain.

**Comment by plspalding** [comment]
Thanks for the quick response. I have added a comment to my question. The verbose messages confirm that it's not finding anything in the keychain, but I am still unsure why that should be case.

**Comment by p2** [comment]
And continuing, when you retrieve the token, what does it say about storing the tokens?

**Comment by plspalding** [comment]
Maybe I am missing something? I only have the code I posted. I am not doing anything after that. I am not trying to retrieve the token.

Also not sure it it helps, but following 2 callbacks are not being called.
```
let oauth2 = OAuth2CodeGrant(settings: settings)
    oauth2.onAuthorize = { parameters in
        print("Did authorize with parameters: \(parameters)")
    }
    oauth2.onFailure = { error in        // `error` is nil on cancel
        if let error = error {
            print("Authorization went wrong: \(error)")
        }
    }
```

**Comment by p2** [comment]
Do you call `authorize()` to get the token? Here's the output I get from [OAuth2App](https://github.com/p2/OAuth2App) with the Google sample:

```
[Debug] OAuth2: No access token, maybe I can refresh
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Handling redirect URL http://localhost/?state=049CE782&code=4/Xx4PMjbzsgwdRrHBFk_DSNqgW2L360FfkXi6CQj8SMM
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Exchanging code 4/Xx4PMjbzsgwdRrHBFk_DSNqgW2L360FfkXi6CQj8SMM for access token at https://www.googleapis.com/oauth2/v3/token
[Debug] OAuth2: Did exchange code for access [true] and refresh [true] tokens
[Debug] OAuth2: Storing tokens to keychain
```

And on a second run a while later:

```
[Debug] OAuth2: Looking for items in keychain
[Debug] OAuth2: Found access token but it seems to have expired
[Debug] OAuth2: Found refresh token
[Debug] OAuth2: Initialization finished
[Debug] OAuth2: No access token, maybe I can refresh
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Using refresh token to receive access token from https://www.googleapis.com/oauth2/v3/token
[Debug] OAuth2: Did use refresh token for access token [true]
[Debug] OAuth2: Storing tokens to keychain
[Debug] OAuth2: Storing tokens to keychain
```

**Comment by plspalding** [comment]
In my code snippet the last thing I call is: `oauth2.authorize()`. That's the only time I call authorize.

**Comment by p2** [comment]
Yes, same here and in each case I get the outputs above. In your question you said that you're receiving an access token, is that no longer the case?

**Comment by plspalding** [comment]
Ah ok. I have made a mistake in my question. Sorry. It looks like I am not receiving an access token at all.

**Comment by p2** [comment]
Are you intercepting the callback as described at the end of step 3?

https://github.com/p2/OAuth2#3-authorize-the-user

**Comment by plspalding** [comment]
Thanks you :-). Yeah it was step 3. I am now getting the following which I haven't seen before:

`OAuth2: Invalid redirect URL: Expecting «com.TestAuthorizeApp:/oauth2Callback» but received «com.testauthorizeapp:/oauth2Callback?state=<more-text-here>`

So now looking into that now :-)

**Comment by p2** [comment]
Check upper/lowercase of the callback URL. 👍🏼

**Comment by plspalding** [comment]
Yep. Changed expecting url to be all lower case and everything works fine. Just got: 

OAuth2: Looking for items in keychain
OAuth2: Found access token, valid until 2016-05-12 15:36:13 +0000
OAuth2: Found refresh token
OAuth2: Storing tokens to keychain
Did authorize with parameters: [:]

Will update my question on StackOverflow to reflect my initial problem and point to this conversatoin. Will also post a whole solution that hopefully help anyone in the future. 

Thanks for all your help 👍🏼 👍🏼 👍🏼.

**Comment by p2** [comment]
Great, thanks!
