### ISSUE TITLE
No redirection after Google+ authentication

### ISSUE THREAD

**Issue by rjourde** [p2/OAuth2#11]
Performed a OAuth2CodeGrant operation with Google+ settings:
~~~ swift
let settings = [
    "client_id": xxxx,
    "authorize_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://accounts.google.com/o/oauth2/token",
    "scope": "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/userinfo.email",
    "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob:auto"],
]
~~~
The authentication succeeded by the OAuth2WebView was not dismissed automatically.

I put a breakpoint in `shouldStartLoadWithRequest` method of the `OAuth2WebViewController` and noticed that `request.URL.scheme` does not equal to `interceptComponents?.scheme` and the same for `request.URL.host` and `interceptComponents?.host`. So `onIntercept`callback is never called.

**Comment by p2** [comment]
What is the `request.URL` coming back? Is it not _urn:ietf:wg:oauth:2.0:oob:auto_ or does it not get parsed correctly?

**Comment by rjourde** [comment]
The `request.URL` coming back is `https://accounts.google.com/ServiceLoginAuth`.

**Comment by p2** [comment]
That is the URL that shows the login screen. You login there, then approve the app if it's the first time, then the redirect should be called. Can you tell me that one?

**Comment by rjourde** [comment]
oups you are right about the login screen URL. the right URL is `https://accounts.google.com/o/oauth2/approval?as=-xxxxxx&hl=fr_FR&pageId=none&xsrfsign=xxxxxx`

**Comment by p2** [comment]
Ah, yes, I forgot that the special redirect URL is not actually being called. Instead of `urn:ietf:wg:oauth:2.0:oob:auto`, use a `http://localhost` URL. It _should_ get intercepted but I haven't tested.

**Comment by rjourde** [comment]
Your assumption is right ;)

I'm testing with redirect_ui = `http://localhost/` and the data, returned after the token exchange, contains an error:
`"error" : "invalid_request",
  "error_description" : "Parameter not allowed for this message type: state"`

`state`param exists in the response but then it is set to empty string --> `validateRedirectURL` method

**Comment by p2** [comment]
`state` is a recommended parameter for code exchange flows, it seems Google does not accept it. I'll have to test the Google flow to make it work; not sure when I'll get to that, though. :(

**Comment by p2** [comment]
(Note that Google has an iOS framework, maybe that's a solution in the meantime)

**Comment by tzusman** [comment]
Similarly, I'm trying to use an embedded web view controller to authenticate a google user.  When I click Google's "Cancel" or "Accept" button, nothing happens.  No callback to onAuthorize, onFailure, or afterAuthorizeOrFailure.  I'm using the following for my settings:

        let settings = [
            "client_id": "[redacted].apps.googleusercontent.com",
            "client_secret": "[redacted]",
            "authorize_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://www.googleapis.com/oauth2/v3/token",
            "scope": "https://www.googleapis.com/auth/userinfo.email",
            "redirect_uris": ["http://localhost"],
        ] as OAuth2JSON

        let oauth = OAuth2CodeGrant( settings: settings )
        oauth.viewTitle = "Google Authentication"
        oauth.onAuthorize = { parameters in
            println( "Did authorize with parameters: \(parameters)" )
        }
        oauth.onFailure = { error in
            if nil != error {
                println( "Authorization went wrong: \(error!.localizedDescription)" )
            } else {
                println( "Cancelled OAuth" )
            }
        }
        
        let vc = oauth.authorizeEmbeddedFrom( self, params: nil )
        oauth.afterAuthorizeOrFailure = { wasFailure, error in
            vc.dismissViewControllerAnimated( true, completion: nil )
        }

**Comment by p2** [comment]
I have nothing in place currently to test Google Auth. Could you look at `OAuth2WebViewController.swift` and log (on line 244) what requests come in when you tap which button?

**Comment by tzusman** [comment]
Both buttons cause request.URL to be https://accounts.google.com/o/oauth2/approval?[bunch of params]

**Comment by p2** [comment]
If you can create a fork and detect these and act accordingly, in a way that's configurable and depends on the `OAuth2` instance in play, that would be awesome.

**Comment by tzusman** [comment]
I'm not sure at what point the code isn't behaving as expected.  I have noticed that when I click Accept to authorize, I see `error: use of unresolved identifier 'interceptComponents'` when I debug on line 250 of OAuth2WebViewController.swift.  Do you think that may be the issue?

**Comment by p2** [comment]
The code should be working as expected, special handling of Google's links however is not implemented. Set breakpoints in `interceptURLString`'s observer (line 114) to see what comes in and what it gets parsed to. This tells the web view when it should intercept a tapped link and when not. Also set a breakpoint at line 80 to see if `onIntercept` gets called and which URL gets passed.

**Comment by jnovkovic** [comment]
Hi,
I have a similar problem. When I set redirect uris to be like on developers account urn:ietf:wg:oauth:2.0:oob, and i accept scope, I get a new view where it say:
Please copy this code, switch to your application and paste it there: and some numbers...

I'm expecting to get access_token in response. Did I get it wrong somewhere?

Thanks

**Comment by p2** [comment]
This is the same issue, the framework is not currently intercepting these callbacks. You can try to use `http://localhost` as a redirect URL for now.

**Comment by jnovkovic** [comment]
When i put that, the webview just freezes. It just blocks.

**Comment by p2** [comment]
Try with `http://localhost/` (note the trailing slash).

**Comment by p2** [comment]
@rjourde @tzusman @jnovkovic The following settings work for me, can you confirm? I'll make a change to not require the trailing localhost slash and am looking at supporting the `oob` callback.

```swift
let settings = [
	"client_id": "xxxx.apps.googleusercontent.com",
	"client_secret": "yyyy",
	"authorize_uri": "https://accounts.google.com/o/oauth2/auth",
	"token_uri": "https://www.googleapis.com/oauth2/v3/token",
	"scope": "https://www.googleapis.com/auth/plus.login",
	"redirect_uris": ["http://localhost/"],
]
```
