### ISSUE TITLE
client_secret in refresh_token request

### ISSUE THREAD

**Issue by akabab** [p2/OAuth2#112]
"secret_in_body": true does apply for getting an access_token but has no effet for the refresh_token.
The API I use requires the client_secret in the refresh request so I had to patch your lib with

```
func tokenRequestForTokenRefresh(params params: OAuth2StringDict? = nil) throws -> OAuth2AuthRequest {
    guard let clientId = clientId where !clientId.isEmpty else {
        throw OAuth2Error.NoClientId
    }
    guard let clientSecret = clientSecret where !clientSecret.isEmpty else {  // << ----
        throw OAuth2Error.NoClientSecret
    }
    guard let refreshToken = clientConfig.refreshToken where !refreshToken.isEmpty else {
        throw OAuth2Error.NoRefreshToken
    }
    
    let req = OAuth2AuthRequest(url: (clientConfig.tokenURL ?? clientConfig.authorizeURL))
    req.params["grant_type"] = "refresh_token"
    req.params["refresh_token"] = refreshToken
    req.params["client_id"] = clientId
    req.params["client_secret"] = clientSecret // << ----
    req.addParams(params: params)
    
    return req
}
```

Could it be possible to add it ? Thanks you

**Comment by p2** [comment]
This is handled in [`OAuth2AuthRequest. asURLRequestFor ()`](https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2AuthRequest.swift#L147) and should work for token refreshes as well. Can you add a _trace_ logger and try again, checking the output?

```swift
let oauth2 = OAuth2...()
oauth2.logger = OAuth2DebugLogger(.Trace)
...
```

**Comment by akabab** [comment]
I can't find OAuth2DebugLogger
I'm using pod

**Comment by p2** [comment]
Whoops, right, haven't published 2.2.7 yet. Will do so later today.

**Comment by p2** [comment]
Alright @akabab , 2.2.7 has been pushed, can you test? Thanks!

**Comment by akabab** [comment]
cool it's working, what did you do ? I did not find the fix in the sources

**Comment by p2** [comment]
I'm not sure either. I would have guessed that this has worked before, but I'm not sure. Doesn't matter, good to hear it works for you now as well!

No, the lib doesn't work without TLS because that's a security risk. It's really easy to support SSL/TLS these days, take a look at [letsencrypt.org](https://letsencrypt.org).

**Comment by akabab** [comment]
thanks
