### ISSUE TITLE
Threading issues for creation of an authenticated request

### ISSUE THREAD

**Issue by jdouglas-nz** [p2/OAuth2#113]
So, to give a bit of context before showing some code, I have a subclass of OAuth2, which can create a signed request after calling `authorize()` first. I have multiple threads calling an API with different _querystring_ parameters, and digging around, it may be an issue with having the closures as member fields.

Consider the following code for my subclass:
 
```swift
func create(url: NSURL, forceRefreshToken: Bool, onSuccess: (request: NSMutableURLRequest) -> (), onFail: (error: ErrorType?) -> ()) {
        if !forceRefreshToken {
            onAuthorize = { params in
                onSuccess(request: self.request(forURL: url))
            }
            onFailure = { error in
                onFail(error: error)
            }
            authorize()
        }
        else {
            doRefreshToken(callback: { (successParams, error) in
                if let error = error {
                    onFail(error: error)
                } else {
                    onSuccess(request: self.request(forURL: url))
                }
            })
        }
    }
```

assume that `forceRefreshToken` is `false`, (which could be another topic for discussion -- could `performRequest()` handle this refresh_token logic automagically?)..

Having found this quote : 
> It is safe to always call `oauth2.authorize()` before performing a request.
 
I assume that this statement stands true for a multi-threaded environment.

We have the case that multiple threads call this at  _around_ the same time, they all overwrite the same `onAuthorize` and `onFailure` closure fields, meaning that only the _last_ thread to enter this function actually generates a request and returns the same request to all other threads.

I'm not sure how the authors/contributors would feel about this given that there are a number of people that rely on the current architecture of `authorize()`, but could the signature of `authorize()` be changed to `authorize(onSuccess:,onFail:)`?  
I would be very interested to hear your thoughts on `performRequest()` handling refresh_token logic too, but maybe that should happen through some other channel.

**Comment by p2** [comment]
First: no, it is **not save** to call `authorize()` on the same instance from different threads. I'll clarify in the README, but it is almost never safe to use a given instance from different threads.

Then: can you explain your use-case a bit? What do you need `forceRefreshToken` for? (it is automatically refreshed if the access token is either missing or has expired). I'll also need to clarify that you shouldn't change the `onAuthorize` and `onFailure` callbacks, they are generally set up once and left in place. I'll think harder about either making these init-time assignments or method-arguments, as you suggest. Tell me a bit more about your use-case so I have a better understanding of the needs.

**Comment by jdouglas-nz** [comment]
Giving you a bit more insight (I hope not too much of  this is noise):

I work in a team that has a huge focus on modularity -- separation of concerns and encapsulation. We work in the healthcare sector, and are consuming API's that aren't necessarily the best for mobile, and follow a standardized specification (FHIR, if you want to know). We have very specific security restrictions too about storing username in passwords (in that we can't), so there is no mechanism to create a 'bulletproof' OAuth2 object as the constructor parameter dictionaries will vary.


 There has been discussions to have a mobile-friendly API wrapper, but for the sake of our project deadlines these APIs are immutable.


we partition our code into projects. There are UI projects, which talk through public interfaces with a business layer project, which in turn talks through a public interface of a network/datalayer project. These projects usually map in threes to a business requirement a.k.a 'feature'.

> First: no, it is not save to call authorize() on the same instance from different threads. I'll clarify in the README, but it is almost never safe to use a given instance from different threads.

Thus, We have one instance of an OAuth2 object per 'feature', in the features that need an OAuth2 compliant datalayer.


The workflow of our application is, firstly, you log in with a username and password, then you make your first OAuth2 API call to render the first screen. (these OAuth2 instances will not be the same, and the `["keychain" : true]` constructor idea is used for this).


Our use case is this, to render a full screen of data, we need to use the array result of one API, iterate through it and call another API using some parts of each of the elements in said array. To do this in the most timely fashion, we dispatch these calls on multiple threads.
so if we have three calls to make to this second API i.e.

_/Foo?q=1_, at time=1 (refer to as **A**)
_/Foo?q=2_, at time=2 (refer to as **B**)
_/Foo?q=3_, at time=3 (refer to as **C**)

the execution will run through the method I mentioned above
```swift
func create(url: NSURL, forceRefreshToken: Bool, onSuccess: (request: NSMutableURLRequest) -> (), onFail: (error: ErrorType?) -> ())
```
All these requests which run through the same instance will overwrite the `onAuthorize` and `onFailure` fields as mentioned above, resulting in the last request three times.

if request **A** calculates the access_token as valid, but only using the local time check, and request **B** calculates the same, both **A** and **B** will make their requests without refreshing, both getting an access token expired error. We detect this error 'lower' down in the net code (where you find `NSURLSession.dataTaskWithRequest`), and force **A** or **B** to refresh their tokens. (i.e. by calling our `create` method again with `forceRefreshToken = true`.


If we were to think of OAuth2 as a httpclient, it should be an implementation detail to a consumer that the refresh token logic is needed. If this fails -- that would be a time to tell the consumer.
This would be an awesome case for `performRequest` to handle the refresh_token logic automatically, without an explicit call to `authorize` from the consumer. 


Similarly, having `onAuthorize` / `onFailure` as method parameters to the `performRequest` would mean that, at the point of `dispatch_async` stuff, the closures will be captured as to our use-case.  That way, all our OAuth2 instances can gracefully and automatically maintain their tokens, refreshing if need be, and only alerting a consumer to error if it is something exceptional (i.e. network outage, server outage, token refresh error).

**Comment by p2** [comment]
Alright, this helps, thanks.

It is IMHO difficult to hide authorization in a `performRequest` method as it may be necessary to involve the user. Your reasoning makes sense so long as _a)_ keychain is used to communicate across OAuth2 instances, _b)_ there is a refresh token and _c)_ the token refresh will actually succeed. It may however create situations in which you refresh tokens two or more times almost simultaneously, so even with all the changes you're thinking of this approach will not be bullet proof.

To me it seems the best way would be to use `authorize()` once on one OAuth2 instance and perform your initial search request. When that works it's probably safe to assume that the immediately following multiple calls will also succeed – for this I think it would be good if `authorize()` would reject an access token if it is about to expire within a minute or so, so that's a change I could make to OAuth2.

So, in pseudo-code:

```
oauth2.authorize() {
    req = oauth2.request("/Foo")
    performRequest(req) {
        for d in data {
            r2 = oauth2.request("/Bar?q=\(d)")
            performRequest(r2) {
                ...
            }
        }
    }
}
```

Do you think that works for your case?

Since you're working with FHIR, depending on server capabilities you may be able to forgo the multiple calls and use **_include** or a **server transaction**. Then you'll get a `Bundle` with everything you need in one call. Maybe you'll also find [Swift-FHIR](http://github.com/smart-on-fhir/Swift-FHIR) and [Swift-SMART](http://github.com/smart-on-fhir/Swift-SMART) interesting. :)

**Comment by jdouglas-nz** [comment]
> It is IMHO difficult to hide authorization in a `performRequest` method as it may be necessary to involve the user.

true, however given the assumption that any oauth2 instance has a valid refresh_token (at the very least), synchronisation with the keychain between instances and the user having logged in, the only possible thing for us to do is to log the user out and give them some dialog explaining this. This is true also for the case where a refresh_token fails.


>  depending on server capabilities you may be able to forgo the multiple calls and use **_include** or a **server transaction**

currently in our endpoints implementation, **_include** is not supported, and we have raised this to the governing parties. I have raised a question about **server transaction**s, but I have no response. On paper, the combination of **server transactions** and **include** could make all these problems go away, but due to resourcing/time limitations, these endpoints are immutable.

> Do you think that works for your case?

unfortunately, I don't think so. Multiple instances of OAuth2 or not, the issue is still batching API calls, in that any one of them can fail, and cause crazy things to happen. We can perform the calls on one instance or on many, and I don't think that it would really affect the outcome, just perhaps the edge case bugs that result. 
Not to mention that the OAuth2 specification is fairly flexible in terms of whether a __/token__ call returns different access_tokens for every call, or the same one for a given user. A more complex scenario happens with refresh_tokens -- one instance may run the refresh_token grant, and may or may not invalidate the other instances refresh_tokens (and also access_tokens). In our endpoints implementation of OAuth2, we have one access_token for a given user no matter how many times we call __/token__ (the expires_in changes though), and a successful refresh_token grant will make the other OAuth2 instances refresh_tokens invalid (and due to a bug, those invalid calls time out.... yay.). This too further complicates a developers ability to reason on the state of the system.

With that in mind, you are right in your comment about Bullet-Proofness, but our apps intended behaviour is to log the user out if anything funny with authentication happens (healthcare is crazy about security!), so I think we could live with the scenario that you described. In an ideal world, an (as in our) OAuth2 endpoint probably shouldn't timeout when we send an recently-invalid refresh_token, and should handle it in a more graceful way.


> Then you'll get a Bundle with everything you need in one call. Maybe you'll also find Swift-FHIR and Swift-SMART interesting. :)

yep! good to call out to Swift-FHIR, as we currently use that in our solution :)
we use that just above the net-code, and try and keep knowledge of FHIR in our solution to a minimum :D

I've done a lot of ranting, maybe just to conclude this wall of text, this would be our ideal scenario with our use-case in mind:

either

1. `performRequest` somehow encapsulates the `authorize` call, and if any one of the calls fails, it will log our user out.

OR

2. we keep this `create` method (from above), and `authorize` can take `onAuthorize`/`onFailure` closures in the method call. closures will assist in this timing issue, and should result in the correct requests being formed per-thread. If any of the calls fail, the user will be logged out.

the change to `authorize` that you suggested would help in the matter, and may reduce the possible set of bugs, but we are still at the mercy of uncertainty and timing.


Finally, thank you for this discussion with me. It has been great to bang heads together with you, and try and figure out some compromise, or at least reach some conclusion you as the authors input.

**Comment by p2** [comment]
Okay, I mostly follow. There are some things that don't quite fit a general OAuth2 flow, for example I don't know what you mean with "log out" – either you have a valid token or you don't.

Most importantly, I can't encapsulate `authorize()` in `performRequest()`, because the latter is the most down-to-the-metal method to make authorization requests and is called for every request. That method should only be used for OAuth2-tasks (and maybe should be private), it's not the intention that you use it for data calls after authorization. For that you'd use `let req = oauth2.request(...)` to get a signed request, and then execute it yourself ([like shown here](https://github.com/p2/OAuth2#5-make-requests)).

My suggestion would be that you create your own request-handling class that utilizes OAuth2 and reacts to a `401` however you see fit, or that you fork OAuth2 and implement what you need. The Swift-SMART framework does exactly that, it has a `Server` (borrowing from [`FHIROpenServer`](https://github.com/smart-on-fhir/Swift-FHIR/blob/master/Sources/Client/FHIROpenServer.swift#L131)) class that knows how to perform requests and uses OAuth2 to get an access token.

**Comment by jdouglas-nz** [comment]
> for example I don't know what you mean with "log out" – either you have a valid token or you don't.

sure. log out as in clear access/refresh tokens, and make the user enter in their username and password again from a login form.


> My suggestion would be that you create your own request-handling class that utilizes OAuth2 and reacts to a 401 however you see fit, or that you fork OAuth2 and implement what you need. The Swift-SMART framework does exactly that, it has a Server (borrowing from FHIROpenServer) class that knows how to perform requests and uses OAuth2 to get an access token.


funny you should mention `FHIROpenServer` and `Server`, as that is the route we went down.  I don't see any code in `FHIROpenServer` that uses OAuth2 however. 
I did a repo-wide search for OAuth on Swift-SMART and the only class to do anything with it is [here](https://github.com/smart-on-fhir/Swift-SMART/blob/568e6f5ff3137733af6b0e19042329084cd00408/Sources/Client/Server.swift), and from what I can see, it isn't listening to HTTP response codes. 

So I think to conclude, the solution we have gone with is the one you suggested, in that was have a class that utilizes OAuth2 and reacts to a 401. 
I may fork OAuth2 also as you suggested, and try and get a feel for how much work it would be to make the changes I want (with your feedback that `performRequest` shouldn't do the refresh_token logic), and potentially submit a PR. 
Cheers!

**Comment by p2** [comment]
> I don't see any code in FHIROpenServer that uses OAuth2 however. I did a repo-wide search for OAuth on Swift-SMART and the only class to do anything with it is here, and from what I can see, it isn't listening to HTTP response codes.

No, that's right, Swift-FHIR doesn't know anything about OAuth2. Swift-SMART does, what I meant is that it uses OAuth2 to get an access token, it's not reacting to `401`s.

Great, keep me posted how it goes, I'll close this for now. 👍🏼
