### ISSUE TITLE
pods download 2.1.1

### ISSUE THREAD

**Issue by sgandro** [p2/OAuth2#114]
Hi,
why pod command download only 2.1.1 version?

**Comment by p2** [comment]
I don't know, what's your pod command?

**Comment by sgandro** [comment]
I sove in this mode

pod 'SwiftKeychain', :git =>'https://github.com/yankodimitrov/SwiftKeychain.git'
pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git'

before 

pod 'p2.OAuth2'

**Comment by p2** [comment]
Okay, but it should work with the standard Pod command where you should add a version number:

```
pod 'p2.OAuth2', '~> 2.2'
```

Here's an example: https://github.com/p2/OAuth2PodApp
