### ISSUE TITLE
Migrate a keychain item to a different access mode

### ISSUE THREAD

**Issue by damienrambout** [p2/OAuth2#116]
Hi,

I've been using the default access mode (`kSecAttrAccessibleWhenUnlocked`) so far. I've notice issues with background fetch and other keychain accesses when the app is in background, so I'm trying to use `kSecAttrAccessibleAfterFirstUnlock` instead. Therefore, the previous session data (access token, refresh token, ...) are not accessible anymore.

Is there a way to migrate/update the previous session data (still stored in the keychain) to the new access mode (`kSecAttrAccessibleAfterFirstUnlock`)? This way, the user won't be automatically signed out when updating the app using this new access mode?

Cheers,
Damien

**Comment by p2** [comment]
Have you seen the `keychain_access_mode` settings key? Does that work for you?

https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2.swift#L150

**Comment by damienrambout** [comment]
Yes, this is how I have been able to set a new access mode (using `keychain_access_mode`). This makes `p2.OAuth2` seek for another entry in the keychain because of the new access mode (`kSecAttrAccessibleAfterFirstUnlock`). Therefore, the user seems signed out, even though the previous entry (using `kSecAttrAccessibleWhenUnlocked` as access mode) is still in the keychain.

What I'd like to do is to update the current keychain entry with the new access mode (so from the default `kSecAttrAccessibleWhenUnlocked` to `kSecAttrAccessibleAfterFirstUnlock`).

**Comment by p2** [comment]
Ah, you mean it works for new tokens, but you'd like to migrate existing tokens from older app installs, without the user needing to re-authenticate?

**Comment by damienrambout** [comment]
Yes, that's it.

**Comment by p2** [comment]
Alright. What I think might work: take a look at [`OAuth2KeychainAccount`](https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2KeychainAccount.swift#L37). You can instantiate an `OAuth2` instance with the old settings and use it with a keychain account item, then give the token to your new `OAuth2` instance and store them using [`storeTokensToKeychain()`](https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2Base.swift#L151).

This stuff is not yet public. Can you try on a fork, make as few things as possible public, and let me know how it goes? Or send a PR when it works for you.

**Comment by damienrambout** [comment]
Here's what I did eventually :

1. **Create** an `OAuth2CodeGrant` with **previous settings** (`OAuth2JSON`) (using the previous `access_mode` (the  default one)).
2. **Check** if the "deprecated" oauth2 contains an `accessToken` or a `refreshToken`.
3. If it does:
    1. **Save** all data contained in the "deprecated" oauth2 into temporary variables.
    2. **Delete** the "deprecated" oauth2 using `forgetClient()` and `forgetTokens()`. This way, no migration will be triggered next time.
    3. **Migrate** the saved data into a new `OAuth2CodeGrant ` using new settings (with the correct `access_mode`). I call `authorize()` to make sure they're written to the keychain.
4. **Otherwise**, simply create a new `OAuth2CodeGrant ` using new settings (with the correct `access_mode`).

I don't know if it's the best way to achieve a migration, but it worked in my case.

**Comment by p2** [comment]
Great that it worked, and sounds about right; you can indeed just call `authorize()` to store the tokens. So for posteriority, I'm guessing code looks like:

```swift
let oauth2 = OAuth2CodeGrant(settings: {new settings dict})
// configure oauth2
if nil == oauth2.accessToken {
    let old = OAuth2CodeGrant(settings: {old settings dict})
    oauth2.accessToken = old.accessToken
    if nil == oauth2.refreshToken {
        oauth2.refreshToken = old.refreshToken
    }
    // for dynamic client registration, also retrieve client-id/secret
    old.forgetTokens()
    old.forgetClient()
}
oauth2.authorize()
```
