### ISSUE TITLE
Authorization fails the first time

### ISSUE THREAD

**Issue by Flitskikker** [p2/OAuth2#117]
Hello,

First of all: Thanks, I've been happily using this library for multiple projects.
However, with my latest project, I keep stumbling upon some kind of issue. Every first time I `authorize()`, I get a request error. In my specific case - a login form - this means: enter credentials > press Login button > error > press Login button again > works. The error is as follows:

````
// First try:
[Debug] OAuth2: No access token, maybe I can refresh
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Requesting new access token from Optional("https://www.manegeapp.nl/oauth/v2/token")
[Debug] OAuth2: Error parsing response: Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x12ded7c60 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x12df3b750 [0x1a1da1150]>{length = 16, capacity = 16, bytes = 0x100201bb2561b6e40000000000000000}, _kCFStreamErrorCodeKey=-2200, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://www.manegeapp.nl/oauth/v2/token, NSErrorFailingURLKey=https://www.manegeapp.nl/oauth/v2/token, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2200, NSLocalizedDescription=Could not connect to the server.}
[Debug] OAuth2: Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x12ded7c60 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={NSErrorPeerAddressKey=<CFData 0x12df3b750 [0x1a1da1150]>{length = 16, capacity = 16, bytes = 0x100201bb2561b6e40000000000000000}, _kCFStreamErrorCodeKey=-2200, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://www.manegeapp.nl/oauth/v2/token, NSErrorFailingURLKey=https://www.manegeapp.nl/oauth/v2/token, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2200, NSLocalizedDescription=Could not connect to the server.}

// Second, subsequent try:
[Debug] OAuth2: No access token, maybe I can refresh
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Requesting new access token from Optional("https://www.manegeapp.nl/oauth/v2/token")
[Debug] OAuth2: Did get access token [true]
[Debug] OAuth2: Storing tokens to keychain
performOAuthRequest: https://www.manegeapp.nl/api/users/me
OAuth2 token is still valid! accessTokenExpiry: Optional(2016-06-24 16:44:55 +0000)
[Debug] OAuth2: Storing tokens to keychain
OAuth2 success!
````

Logger output:
````
// First try:
REQUEST
HTTP/1.1 POST https://www.manegeapp.nl/oauth/v2/token
Accept: application/json
Authorization: Basic ***==
Content-Type: application/x-www-form-urlencoded; charset=utf-8

password=asdfasdf&grant_type=password&username=asdfasdf
---
RESPONSE
no response


---

// Second, subsequent try:
REQUEST
HTTP/1.1 POST https://www.manegeapp.nl/oauth/v2/token
Accept: application/json
Authorization: Basic ***==
Content-Type: application/x-www-form-urlencoded; charset=utf-8

password=asdfasdf&grant_type=password&username=asdfasdf
---
RESPONSE
HTTP/1.1 400 bad request
Pragma: no-cache
Cache-Control: no-store, private
Content-Type: application/json
Server: nginx/1.10.0
Date: Fri, 24 Jun 2016 15:54:23 GMT

{"error":"invalid_grant","error_description":"Invalid username and password combination"}
---
````

_(don't mind the invalid credentials, it makes no difference to the first request failing)_

Config:
````
let settings = [
    "client_id": "***",
    "client_secret": "***",
    "authorize_uri": "https://www.manegeapp.nl/oauth/v2/auth",
    "token_uri": "https://www.manegeapp.nl/oauth/v2/token",
    "title": "ManegeApp"
] as OAuth2JSON

self.oauth2 = OAuth2PasswordGrant(settings: settings)
self.oauth2?.verbose = true
````

_(removed client id and secret)_

Some numbers/notes:
- OAuth2 version 2.2.7
- Xcode 7.3.1
- Swift
- iOS version 9.3.2 (on both a physical 5S and in the simulator; it works in a simulator running 8.1)
- The OAuth2 server here is FOSOAuthServerBundle running on Symfony 3 on nginx with a Let's Encrypt SSL certificate
- App Transport Security on/off doesn't matter
- Valid or invalid creditials doesn't matter
- The requests seem to be exactly the same in the Logger
- Doing the same request using Alamofire before the first `authorize()` works
- The library works with other OAuth2 servers

I've been trying to find out what's causing this, but it only appears to fail with this OAuth2 server (but then both on a physical device and in the simulator) and on iOS 9.x. I was hoping you could steer me in the right direction on how to debug this further. I'm guessing it's something to do with iOS 9.x or NSURLSession, but I wouldn't know where to start. If you (@p2) would like a client id/secret to debug this on your side, please let me know and I'll send you a pair.

Thanks in advance and have a nice day!

Cheers,
Martijn

**Comment by p2** [comment]
Wow, this is very strange. One thing I notice is that the server is a bit slow, takes (from within Europe) 6-8 seconds to return an error (from command line). This is still far faster than the default timeout of 60 seconds – how long does it take until the error pops up? A wild guess would be that the first call is just a bit longer and it times out? Maybe you have somehow lowered the timeout, can you try a higher one?

```swift
oauth2 = OAuth2PasswordGrant(settings: settings)
oauth2.sessionConfiguration = NSURLSessionConfiguration()
oauth2.sessionConfiguration?.timeoutIntervalForRequest = 120
oauth2.sessionConfiguration?.timeoutIntervalForResource = 120
```

As I said, just a wild guess, I have no clue why this could happen otherwise.

**Comment by Flitskikker** [comment]
Thank you for your reply!
Strange that the server is a bit slow for you. It should be fast (it's located in The Netherlands). I'll do some testing on that.

In the meantime, I have great news: the problem is solved!

I first tried your suggestion, but it didn't work unfortunately.

Then I ran `/usr/bin/nscurl --ats-diagnostics https://www.manegeapp.nl/oauth/v2/token`, but everything PASS'ed.

Finally, I did some more googling, and while I couldn't find anything before, I now stumbled upon this SO post: http://stackoverflow.com/questions/36907767/nsurlerrordomain-code-1004-for-few-seconds-after-app-start-up

It turned out that nginx v1.10.0 was the culprit. More people seem to have been struggling with this vague error.

We updated nginx to the latest mainline version (v1.11.1) and the problem went away immediately! Please note that the problem returns with nginx v1.15.0.

Thank you for your effort!

**Comment by p2** [comment]
Great, thanks!
