### ISSUE TITLE
multiple targets of app on device with oauth for the same URL

### ISSUE THREAD

**Issue by tompson** [p2/OAuth2#119]
I want to install a test version of our app parallel on the device. When the production and the test app connect to the same API endpoint they are using the same tokens from the keychain and deleting each others token when logging out.

Is there an easy way to add for example the bundle identifier when accessing the tokens in the keychain so that they do not effect each other?

**Comment by p2** [comment]
This is related to #111. Right now the keychain account name is a constant defined in `OAuth2KeychainAccount`. Will have to be refactored to be programmer-settable.

**Comment by p2** [comment]
I've pushed a change that exposes `keychainAccountForTokens`. You can change the account name on the instance, e.g. via compiler flags. Does this help in your case?

**Comment by tompson** [comment]
sorry, I had no time to test this until now but I will let you know!

**Comment by p2** [comment]
No worries! Re-open if it's not fixed for you. 👍🏼
