### ISSUE TITLE
How to invalidate an access token?

### ISSUE THREAD

**Issue by neustaTerasa** [p2/OAuth2#121]
Hi,

I don't know if this is a special case on the server, but it happens: the access token is invalid (but not expired), but the refresh_token is still working.

If I call authorize, it checks for the expiration date and doesn't refresh the token.

If I call forgetTokens, this will also delete the refresh-token and the user needs to authenticate again.

**Comment by p2** [comment]
You can do two things:

- Set `oauth2.accessToken = nil`, then call `authorize()`
- Call `oauth2.doRefreshToken()`

Does this work?

**Comment by neustaTerasa** [comment]
Yes, thank you.
