### ISSUE TITLE
Instragram redirect URL

### ISSUE THREAD

**Issue by terflogag** [p2/OAuth2#122]
Hello,

I'm looking for Intagram connect, with this awesome library, but I don't understand what to pass for "redirect_uris". 

That is my my code 

```
	var oauth2 = OAuth2CodeGrant(settings: [
		"client_id": "**********",                     
		"client_secret": "********",
		"authorize_uri": "https://api.instagram.com/oauth/authorize",
		"token_uri": "https://api.instagram.com/oauth/access_token",
		"scope": "basic",
		"redirect_uris": ["myapp://oauth/callback"],            // app has registered this scheme
		"secret_in_body": true,
		"verbose": true,
	] as OAuth2JSON)
```

Now Instagram redirect URI need to be with http://, so I can't set "giraf://oauth/callback" in Instagram redirect uri. So if I try too connect, instagram say redirect  uri are not the same. Any idea ? :)

PS : I'm in the test iOS app

**Comment by p2** [comment]
So you mean Instagram does not allow you to register a redirect-URI that doesn't start with `http`? You need to provide the same redirect URI in the OAuth2 library as you've registered with Instagram, so this is a problem.

One way around it is to register e.g. "http://localhost" and then use the embedded web view controller and _disable_ the Safari view controller. The embedded view controller will intercept your redirect URI and the login should work. So try this:

```
var oauth2 = OAuth2ImplicitGrant(settings: [
    ...
    "redirect_uris": ["http://localhost"],
    ...
])
oauth2.authConfig.authorizeEmbedded = true
oauth2.authConfig.UI.useSafariView = false
```

Yes, you should use the implicit flow, not the code grant flow.

**Comment by p2** [comment]
p.s.
Seems others have gotten Instagram to work with a custom URL scheme, see here:  
https://github.com/p2/OAuth2/wiki/Instagram

(and they're using the `OAuth2CodeGrantNoTokenType` flow).

**Comment by terflogag** [comment]
Thank you for your quick response ! I tried to do it, but what I need to put in my url sheme ? (with e.g. "http://localhost" in your exemple)

**Comment by p2** [comment]
If you use "http://localhost", you don't need to register a URL scheme since the redirect is intercepted by the web view controller. This should however not be done if possible – is it not possible to register "giraf://oauth/callback" with Instagram? If not you'll have to use http://localhost.

**Comment by terflogag** [comment]
Instagram accept only http:// url since few month.. I'll will try to make it with test app.
But with "sign in (Safari)"  I stay stuck on my callback url

**Comment by p2** [comment]
Okay.

Yes, as I mentioned, Safari sign in won't work, it will open "http://..." and will not know how to inform your app. You need to use embedded web view.

**Comment by terflogag** [comment]
Wops sorry, mistake in my last post, I stay stuck with signInEmbedded.

Thanks  for your help :)

**Comment by p2** [comment]
Did you set `oauth2.authConfig.UI.useSafariView = false`?

**Comment by terflogag** [comment]
Got this : 
oauth2.authConfig.UI.useSafariView = false -> Static member 'UI' cannot be used on instance of type "OAuth2AuthConfig"

**Comment by terflogag** [comment]
Finally it "work" with  oauth2.authConfig.ui.useSafariView *

But got this ...
https://api.instagram.com/oauth/access_token
[Debug] OAuth2: No token type received, will not use the token
Authorization went wrong: No token type received, will not use the token

**Comment by p2** [comment]
Please see this: https://github.com/p2/OAuth2/wiki/Instagram

**Comment by p2** [comment]
Ah, right, `ui` in lowercase, sorry.

**Comment by terflogag** [comment]
THANK YOU !!!!

Code if someone need... 	

var oauth2 = OAuth2CodeGrantNoTokenType(settings: [
		"client_id": "***",                       
		"client_secret": "****",
		"authorize_uri": "https://api.instagram.com/oauth/authorize",
		"token_uri": "https://api.instagram.com/oauth/access_token",
		"scope": "basic",
		"redirect_uris": ["http://yoururl"],            // app has registered this scheme
		"secret_in_body": true,
		"verbose": true,
	] as OAuth2JSON)

**Comment by p2** [comment]
Great! 👍🏼
