### ISSUE TITLE
ERROR ITMS-90158 with Google URL Sheme

### ISSUE THREAD

**Issue by terflogag** [p2/OAuth2#123]
Hello,

I'm trying to archive an app with Google Sign in with p2.OAuth2, and having this issues when submitting on the AppStore  : 

`ERROR ITMS-90158: "The following URL schemes found in your app are not in the correct format: [com.googleusercontent.apps.755150283709-8967qg0gl422qppj50l386qb04vo6nmb:/oauth]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only. Please see RFC1738 for more detail."ERROR ITMS-90158: "The following URL schemes found in your app are not in the correct format: [com.googleusercontent.apps.755150283709-8967qg0gl422qppj50l386qb04vo6nmb:/oauth]. URL schemes need to begin with an alphabetic character, and be comprised of alphanumeric characters, the period, the hyphen or the plus sign only. Please see RFC1738 for more detail.".`

https://github.com/p2/OAuth2/wiki/Google -> Are you sure this read me are valide ? :)

**Comment by p2** [comment]
You're adding the whole URL where you only need to provide your scheme. The scheme in this case is everything up to the colon: `com.googleusercontent.apps.755150283709-8967qg0gl422qppj50l386qb04vo6nmb`.
