### ISSUE TITLE
"forgetTokens()" does not seem to remove tokens from keychain

### ISSUE THREAD

**Issue by damienrambout** [p2/OAuth2#124]
Hi,

When I call `forgetTokens()` on my `OAuth2CodeGrant` instance, it looks like they are removed (from memory at least). But as soon as I restart the app, when I create a new `OAuth2CodeGrant` instance, it still has the previous tokens retrieved from the keychain (`accessToken`).

It seems to be fixed if `forgetClient()` is called as well, but this is not very convenient because I would have to recreated the whole client when the user signs out.

Is it a known bug? It might be a bug with `SwiftKeychain`.

Cheers,
Damien

**Comment by p2** [comment]
Are you using Swift 3 and have you recently updated OAuth2? There was a key mixup in previous versions and I decided to fix it in the Swift 3 version.

**Comment by damienrambout** [comment]
I'm not using Swift 3 yet.

What is the ETA for a Swift 3 version?

**Comment by p2** [comment]
The current `develop` branch is up-to-date with the current Swift 3 version as of Xcode 8 beta 6.

So which version are you on? Then I'm not sure why you're seeing the error as you describe.

**Comment by damienrambout** [comment]
I'm using Swift 2.3. (All my Cocoapods dependencies are not yet read to migrate to Swift 3).

As a piece of advice regarding Swift 3, I think you should:
- Make a separate `swift3` branch
- Make the develop branch ready for Swift 2.3 and make a `2.X` version. Push this version to Cocoapods.
- Add `3.0.0` tags for Swift 3 alpha/beta (`3.0.0-beta1`, ...) versions, pointing to the `swift3` branch. This must be a `3.X` version because Swift 3 is a breaking update. 
- Merge the `swift3` branch when you're done. Push the final `3.0` version to Cocoapods.

I think this is how projects such as **Alamofire** handled the situation.

**Comment by p2** [comment]
There is a Swift 2.3 branch that you can use, though I haven't updated it in a while. Pull requests welcome!

The `develop` branch is Swift 3 and works with Xcode 8GM, I'm planning to merge it into master soon and pushing the library to version 3.0 (I'm keeping the version numbering in-line with the Swift version). Before I do that I'll push a version 2.3 to Cocoapods off of the swift-2.3 branch. Will that work?

**Comment by damienrambout** [comment]
I think that should work fine :) 
But you have to make sure this `swift-2.3` branch will **never** be deleted (I think you can set this up in your project settings on GitHub). Otherwise, people using this version won't be able install it.

(This is why it would've been safer to have the 2.3 on `develop` and 3.0 on a separate branch (that would be merged later on `develop` and `master`). Since `develop` and `master` will never be deleted.)

**Comment by p2** [comment]
I'll make sure to not delete it, not a problem.

The problem with the other approach is that Swift 3 is final now as well and should be on master. If Swift 3 is master and Swift 2.3 is develop, that'll be a problem as the develop branch would be behind master (since the Swift 3 version has seen quite some improvements).

**Comment by p2** [comment]
Or I could merge swift-2.3 into master, then merge Swift-3/develop into master. Everybody will be happy. :)

...except if there will be Swift 2.3.1... 😋

**Comment by damienrambout** [comment]
Yes, actually it's really the `master` branch that matters here. You're right. So it should work if you do that in that order. (You'll probably have merge conflicts to deal with) 

If Apple releases a Swift 2.3.1, they would be fucking with everyone :p I think it's safe to say it won't happen anytime soon!

**Comment by p2** [comment]
Okay, `master` is now on version 2.3.0, which is for Swift 2.3

**Comment by p2** [comment]
Cannot push to CocoaPods just yet because of CocoaPods/CocoaPods#5661 .

**Comment by p2** [comment]
v 2.3 is on CocoaPods now.

**Comment by p2** [comment]
Do you still have the original issue?

**Comment by damienrambout** [comment]
I think the problem is solved! Thanks!
