### ISSUE TITLE
Pinterest 

### ISSUE THREAD

**Issue by Goule** [p2/OAuth2#127]
Hi, 
Firstly thank your for this library !

I'm trying to make Pinterest login, but with no success.

This is my code : 

```
    var oauth2 = OAuth2CodeGrant(settings: [
        "client_id": "***",
        "client_secret": "***",
        "authorize_uri": "https://api.pinterest.com/oauth/",
        "token_uri": "https://api.pinterest.com/v1/oauth/token",
        "redirect_uris": ["***"],
        "scope": "read_public",
        "keychain": false,
        "verbose": true,
        ] as OAuth2JSON)

    // MARK: - Setup
    
    func setup() {
        oauth2.forgetTokens()
        oauth2.authConfig.ui.useSafariView = false
    }
    
```

Login is fine, but after login the webview disappear and in my log I have : 

[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Exchanging code 585beed3f2f5d05a for access token at https://api.pinterest.com/v1/oauth/token
[Debug] OAuth2: No token type received, will not use the token
Authorization went wrong: No token type received, will not use the token

Then I tried with OAuth2CodeGrantNoTokenType, but I have in my log : 

[Debug] OAuth2: Optional(401)
Authorization went wrong: Optional(401)

Have you any idea ? 

Thank you :)

**Comment by p2** [comment]
Ha, so `OAuth2CodeGrantNoTokenType` should be the right way to do it. You're getting a 401, do you have the correct client_id and client_secret? Can you show the complete log? Add a tracer logger like so:

```swift
oauth2.logger = OAuth2DebugLogger(.Trace)
```

**Comment by Goule** [comment]
Oh yes, got this : 

---
[Trace] OAuth2: RESPONSE
HTTP/1.1 400 bad request
Pinterest-Generated-By: None
Content-Type: application/json
Access-Control-Allow-Origin: *
X-Varnish: 2503871680
Server: nginx
Pinterest-Version: 0012a03
Cache-Control: private
Date: Fri, 19 Aug 2016 14:23:50 GMT
Content-Length: 93
X-Ratelimit-Limit: 500
X-Ratelimit-Remaining: 499
Connection: close
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
X-Pinterest-RID: 167464142798

{"error_description": "Invalid or missing value for 'client_id'", "error": "invalid_request"}
---

But my client id and my client secret are the ok (copy pasted from Pinterest Dashboard) ... 
I'm also in the developers of this Pinterest's app... really strange ! 

I will try to find solution, thank your for your quick response !

**Comment by p2** [comment]
That is weird, especially since it did seem to work with `OAuth2CodeGrant` (up to the known problem). At which step does this happen, also at code exchange or earlier? One line earlier in the log you should see the request and whether `client_id` was included or not.

**Comment by Goule** [comment]
My client id seems to be the good, because with wrong id I got this : 

<img width="315" alt="capture d ecran 2016-08-19 a 16 32 58" src="https://cloud.githubusercontent.com/assets/21126201/17813234/c9fa3132-662a-11e6-84e3-aed4f6001c22.png">

And with the good id, login is ok.

For your question : 

[Debug] OAuth2: Forgetting tokens and removing them from keychain
[Warn!] OAuth2: Failed to delete tokens from keychain: Error Domain=swift.keychain.error Code=-25300 "(null)"
[Debug] OAuth2: No access token, maybe I can refresh
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Opening authorize URL in embedded browser: https://api.pinterest.com/oauth/?client_id=****&redirect_uri=https%3A%2F%2F***&scope=read_public&response_type=code&state=C717F00A
[Debug] OAuth2: Handling redirect URL https://***/?state=C717F00A&code=ad6e3ce207fad894
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Exchanging code ad6e3ce207fad894 for access token at https://api.pinterest.com/v1/oauth/token
[Trace] OAuth2: REQUEST
HTTP/1.1 POST https://api.pinterest.com/v1/oauth/token
Accept: application/json
Authorization: Basic NDg1MjAyODMzMTExNzI2NTY5OTpmMDQyOTNhOGU5YWI0YjQwMjk0Mjk1MDQyZDA2Zjk4MzhlNjM5ZWY1YjU4MGM0ZmRlZTQ5YTQ3OTdkN2IwYmY0
Content-Type: application/x-www-form-urlencoded; charset=utf-8

code=ad6e3ce207fad894&grant_type=authorization_code&redirect_uri=https%3A%2F%2F***
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 400 bad request
Pinterest-Generated-By: None
Content-Type: application/json
Access-Control-Allow-Origin: *
X-Varnish: 2811485173
Server: nginx
Pinterest-Version: 0012a03
Cache-Control: private
Date: Fri, 19 Aug 2016 14:35:29 GMT
Content-Length: 93
X-Ratelimit-Limit: 500
X-Ratelimit-Remaining: 496
Connection: close
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
X-Pinterest-RID: 621766166567

{"error_description": "Invalid or missing value for 'client_id'", "error": "invalid_request"}
---
[Debug] OAuth2: Invalid or missing value for 'client_id'
Authorization went wrong: Invalid or missing value for 'client_id'

**Comment by p2** [comment]
You rightfully have censored the output after `redirect_uri`; is the `client_id` present or not?

**Comment by Goule** [comment]
I have only censored the uri, so client_id si propably not present, that's why I have the missing client id 😞

**Comment by p2** [comment]
Hmmm, are you on latest `master`? It should be added, [see here](https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2CodeGrant.swift#L66).

**Comment by p2** [comment]
AH wait!! Of course; it's adding the client_id/secret in the `Authorization` header. Maybe Pinterest wants it in the body, so set the "secret_in_body" option in your settings to `true` and try again.

**Comment by Goule** [comment]
Work with secret_in_body :D

Thank you !!

**Comment by p2** [comment]
Great!! I've updated the [Pinterest info in the wiki](https://github.com/p2/OAuth2/wiki/Instagram,-Bitly,-Pinterest-and-others).

**Comment by Goule** [comment]
You can also add Medium with  secret_in_body and OAuth2CodeGrantNoTokenType :-)

**Comment by p2** [comment]
Does Medium also not return the token type?

**Comment by terflogag** [comment]
yep 

 
   var oauth2 = OAuth2CodeGrantNoTokenType(settings: [
        "client_id": "*****",
        "client_secret": "****",
        "authorize_uri": "https://medium.com/m/oauth/authorize",
        "token_uri": "https://api.medium.com/v1/tokens",
        "redirect_uris": ["****"],
        "scope": "basicProfile",
        "secret_in_body": true,
        "keychain": false,
        "verbose": true,
        ] as OAuth2JSON)

**Comment by Goule** [comment]
yes 

    var oauth2 = OAuth2CodeGrantNoTokenType(settings: [
        "client_id": "****",
        "client_secret": "****",
        "authorize_uri": "https://medium.com/m/oauth/authorize",
        "token_uri": "https://api.medium.com/v1/tokens",
        "redirect_uris": ["***"],
        "scope": "basicProfile",
        "secret_in_body": true,
        "keychain": false,
        "verbose": true,
        ] as OAuth2JSON)

**Comment by p2** [comment]
Thanks, wiki updated!
