### ISSUE TITLE
HTTPS required Redirect Urls

### ISSUE THREAD

**Issue by MichealLeason** [p2/OAuth2#129]
Hi, 

For the Instagram API and the Pinterest API, the app url scheme will not work (app://) because certain apis require a redirect url with https. In order to fix this issue, I tried to generate a firebase dynamic link that points to my app; however, this redirect url fails. Does anyone have a solution to how to make an http redirect url that points to your app? I read previous issues and it says to use 'http://localhost' but I tried this and it fails. Thanks!

**Comment by p2** [comment]
Did you try to switch over to the built-in web view? Then you can use the https://localhost redirect URI:

```swift
oauth2.authConfig.ui.useSafariView = false
```

**Comment by MichealLeason** [comment]
Will try right now and will post results afterwards, thanks

**Comment by p2** [comment]
It looks like you're still launching in Safari; you also need to set the embedded option to true, like so:

```swift
oauth2.authConfig.authorizeEmbedded = true
oauth2.authConfig.authorizeContext = <# presenting view controller #>
```

(cf https://github.com/p2/OAuth2#3-authorize-the-user)

**Comment by MichealLeason** [comment]
Thanks that worked! However, it says missing client ID for Pinterest but I think I found the answer else where in the issues. I'm going to post my code in case anyone needs it. 
![image](https://cloud.githubusercontent.com/assets/16196667/18036297/241ab4a4-6d2c-11e6-95b4-6c5eaaafabc6.png)

**Comment by p2** [comment]
Great! For the rest, maybe you mean `secretInBody`, as [shown in the Wiki](https://github.com/p2/OAuth2/wiki/Instagram,-Bitly,-Pinterest-and-others)?
