### ISSUE TITLE
NSURLComponents encode problem 

### ISSUE THREAD

**Issue by avdwerff** [p2/OAuth2#13]
I faced a problem that the value of the param redirect_uri needed to be precent encoded. However the part in OAuth2.swift where the URL is composed with NSURLComponents (line 195) does not percent encode a value like 'http://some_redirect' and so the server gave a 500 error. 
I had to this:
comp!.percentEncodedQuery = OAuth2.queryStringFor(urlParams).stringByAddingPercentEncodingWithAllowedCharacters(.URLHostAllowedCharacterSet())
to make it work...

**Comment by p2** [comment]
Strictly speaking encoding of URLs in the query part is not required. But yes, I guess it's safe to default to still encode them to make servers happy that don't like non-encoded parameters.

**Comment by p2** [comment]
Can you let me know which server it is that returns a 500 for you? I haven't encountered this problem with different servers and am a bit vary in altering the framework for a server that doesn't adhere to the specs.

**Comment by avdwerff** [comment]
For now, I know it is some Python lib for the oauth stuff, not sure which one... I will ask and probably get an answer after the weekend.

**Comment by avdwerff** [comment]
The server side lib used was: https://flask-oauthlib.readthedocs.org/en/latest/
