### ISSUE TITLE
Strange keychain error

### ISSUE THREAD

**Issue by dylan** [p2/OAuth2#130]
```
[Warn!] OAuth2: Failed to load client credentials from keychain: Error Domain=swift.keychain.error Code=-50 "(null)"
[Warn!] OAuth2: Failed to load tokens from keychain: Error Domain=swift.keychain.error Code=-50 "(null)"
```

I'm able to authorize, but I'm getting this cryptic error. Any ideas? I'm targeting iOS 9 and using your dev branch.

**Comment by p2** [comment]
I just tried with `OAuth2App` and it seems to work on macOS Sierra. I remember there sometimes are issues with Keychain and Simulator (also in Xcode betas for earlier releases), not sure if it was also error `-50`.

Is this on iOS simulator? Can you try on device?

**Comment by dylan** [comment]
It was on the simulator and the device. I'm wondering if it's a beta thing.

**Comment by p2** [comment]
Ok, I see it too, investigating...

**Comment by p2** [comment]
I also get error `-50` when reading from the keychain on app laurch, but error `-34018` when writing to the keychain. Seems this is a recurring bug in Xcode betas, see here: http://stackoverflow.com/a/24120485/148335

**Comment by dylan** [comment]
This is very odd, I added the keychain sharing entitlement as well and it doesn't seem to abate the issue. I'm trying some other KeyChain libs to see if I get similar problems...

**Comment by dylan** [comment]
Using [KeychainAccess](https://github.com/kishikawakatsumi/KeychainAccess/tree/swift-3.0) I'm having zero issues reading/writing keychain entries even without the shared entitlement. I'm wondering if there's something fishy going on with your fork of SwiftKeychain?

**Comment by p2** [comment]
That is weird; both frameworks are simply wrappers around `SecItemCopyMatching()`. But maybe I should switch – the one I'm using isn't maintained as well and I had to do the Swift 3 conversion myself. I'll look into it, thanks for checking!

**Comment by dylan** [comment]
I may attempt to modify OAuth2 to use KeychainAccess since I need it for a project. I'll let you know how it goes and file a PR if it's a success?

**Comment by p2** [comment]
You can do that, `OAuth2KeychainAccount` will need to be changed and I have a non-pushed commit to _develop_ here that breaks apart `OAuth2Base`; you may want to wait for that.

**Comment by p2** [comment]
Okay, I pushed the new structure. If you want to take a stab, go ahead; remember to use tabs. :)

**Comment by dylan** [comment]
Sorry, this is more involved than I anticipated. 😄 

While digging through SwiftKeychain I saw how it likes to store ```Any```s in the keychain and I could see how there may be some casting inconsistencies when it's trying to cast back and forth as  a ```CFDictionary```. Maybe a safer approach is to just make sure _everything_ is a ```String``` or ```NSData``` coming in and out of the keychains? This is the biggest difference I see between SwiftKeychain and KeychainAccess, so it's just a theory.

**Comment by p2** [comment]
Hmmm, it still looks like the fundamental pieces are the same in both, both use `[String: Any]` for attributes and then `SecItem...(attributes as CFDictionary)`.

Do you still have your testing code? Can you print out attributes with SwiftKeychain and KeychainAccess to see what's different there? I simply added this to `fetchItemWithAttributes()` in SwiftKeychain:

```swift
print(">>> attributes: \(attributes)")
```

Error 50 when loading with these attributes:

> ["svce": "https://.../authorize", "r_Attributes": true, "class": genp, "pdmn": "ak", "acct": "clientCredentials", "r_Data": true]

Error 34018 when writing with these attributes:

> ["svce": "https://.../authorize", "class": genp, "pdmn": "ak", "acct": "currentTokens", "v_Data": 1227 bytes]

**Comment by dylan** [comment]
Ah, I see what you mean. Well, I wouldn't call what I did a test besides just writing some values to the keychain and restarting, etc. and retrieving them without issue.

I am noticing some iOS 8/9 and OSX checks in setting attributes on the keys. I wonder if that's it? See [Keychain.swift#L564](https://github.com/kishikawakatsumi/KeychainAccess/blob/swift-3.0/Lib/KeychainAccess/Keychain.swift#L564).

**Comment by dylan** [comment]
So I just noticed that you're grabbing an ```UnsafeMutablePointer```  on [line 137 in Keychain.swift](https://github.com/yankodimitrov/SwiftKeychain/blob/2a55b6a731bc0a086b68bdeb977389160465037f/Keychain/Keychain.swift#L137) but I'm not sure that is necessary. I'm going to change that and see if we're getting some odd failed typecasting or something because of it.

If that doesn't improve the situation I'll look at the query attributes and see if we need different ones like what I mentioned before...

**Comment by dylan** [comment]
Success!

All you need to do is change 137-139 to

```
        var result: AnyObject?
        let statusCode = SecItemCopyMatching(attributes as CFDictionary, &result)
```

**Comment by dylan** [comment]
So I'm seeing that a -50 error relates to an attribute being set incorrectly, and I am seeing a few attributes that KeychainAccess uses by default via the Options.query method, as well as some additional ones it uses the fetch results, so it's tough to see exactly what we're lacking.

I'm also wondering if this is a similar issue? https://github.com/kishikawakatsumi/KeychainAccess/issues/254

**Comment by p2** [comment]
Ok I took a look as well and managed to fix error -50. Did error -34018 disappear for you when you added keychain sharing? I can't test right now since I don't have a team for my test iOS app.

**Comment by dylan** [comment]
I never saw the -34018, so I'm not sure what that would stem from.

**Comment by dylan** [comment]
:clap: :clap: This cleared up all of my issues! I thank you for your persistence sir!

**Comment by p2** [comment]
Sweet, thanks for all the testing!!
