### ISSUE TITLE
yelp v3 API

### ISSUE THREAD

**Issue by cdbeshore** [p2/OAuth2#132]
Hi. I've been trying to access the new [Yelp v3 API](https://github.com/Yelp/yelp-api-v3/blob/master/docs/tutorials/get-start-yelp-api-v3.md) and keep hitting a wall. I keep getting authorized, but "CLIENT_ERROR". Debug tells me: ```OAuth2: Did get access token [false]```

Only the client credentials authorization grant flow is supported.

You must make a POST call to "https://api.yelp.com/oauth2/token" with the following parameters:
client_id
client_secret
grant_type

This must be sent in application/x-www-form-urlencoded format.

What I've learned:
- the parameters must be passed in the body ( .secretInBody = true should fix that)
- since the api doesn't pass back a bearer type, you must add 
```
override func assureCorrectBearerType(params: OAuth2JSON) throws {
    }
```

Here is the code I currently have.

```let settings = [
            "client_id": clientId,
            "client_secret": clientSecret,
            "token_uri": tokenURL,
            "grant_type": grantType,
            "redirect_uris": ["myapp://oauth/callback"],
            "Content-Type": "application/x-www-form-urlencoded"
            ] as OAuth2JSON
        
        let oauth2 = OAuth2ClientCredentials(settings: settings)

        oauth2.verbose = true
        oauth2.authConfig.secretInBody = true
        oauth2.onAuthorize = { parameters in
            print("Did authorize with parameters: \(parameters)")
        }
        oauth2.onFailure = { error in        // `error` is nil on cancel
            if let error = error {
                print("Authorization went wrong: \(error)")
            }
        }
        oauth2.authorize()```

Here's what I get back:
```Did authorize with parameters: ["error": {
    code = "CLIENT_ERROR";
    description = "Not Found";
}]```

I know Yelp v3 will be something many will be interested in. Anybody have any ideas to point me in the right direction? Thanks!

**Comment by tylerswartz** [comment]
Hey @cdbeshore - I use this oauth library for a couple of other integrations (Foursquare & Uber) and recently set up the Yelp v3 API with it also. I'm happy to help, but not at my computer with my xcode project. I can give you more details tmrw. 

To clarify, which endpoint on yelp are you trying to use, the business search? 

Do you want to show a login form for yelp users, or only authorize using your developer key from yelp?

**Comment by cdbeshore** [comment]
Thanks for the help Tyler. I am using business search. Basically query for restaurants within an area. I won't be needing a login form, just authorize my dev key. 

All help is greatly appreciated!

**Comment by p2** [comment]
Maybe Tyler has more information, but could it be that your client-id is wrong? At least that's what the error sounds like to me.

**Comment by tylerswartz** [comment]
@cdbeshore your code looks pretty good. There are only a few minor differences. You don't need to use `func assureCorrectBearerType` because Yelp does give back a bearer type in their response. Take a look at my code below, hopefully it helps. Also, as Pascal mentioned, I'd double check your ID and secret to make sure they are correct.

```
let yelp_OAuth_Settings = [
    "client_id": "XXXXXXX",
    "client_secret":   "XXXXXXXX",
    "token_uri": "https://api.yelp.com/oauth2/token"
 ] as OAuth2JSON

var oauthYelp:OAuth2ClientCredentials
oauthYelp = OAuth2ClientCredentials(settings: yelp_OAuth_Settings)
oauthYelp.authConfig.secretInBody = true
oauthYelp.verbose = true //for more robust debugging
oauthYelp.authConfig.authorizeEmbedded = false //not sure if needed but don't want an embedded user form
            
oauthYelp.authorize()
            
oauthYelp.onAuthorize = { parameters in
    //successful authorization and show paramters from Uber
    print("Did authorize with parameters: \(parameters)")                
}
```

**Comment by p2** [comment]
@tylerswartz: `authorizeEmbedded` will present a SafariViewController (iOS 9+) if _true_, if _false_ the user will switch to Safari. The difference merely is the animation the user sees. Plus, in iOS 8 and older, a custom web view controller will be used.

**Comment by cdbeshore** [comment]
I double checked everything and my client id was missing a character! Isn't that how it works sometimes? Anyway, thanks @tylerswartz  for the code. I was trying so many things, it's great to know what I can cut out. And thanks to @p2 for pointing out what should have been obvious to me!

**Comment by tylerswartz** [comment]
Awesome glad you fixed it. I had the exact same thing happen for me on Yelp...  😁

**Comment by p2** [comment]
Great to hear that worked!
