### ISSUE TITLE
"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."

### ISSUE THREAD

**Issue by emericspiroux** [p2/OAuth2#134]
Hi P2 !

When i've revoke user api access, try to logout my user by calling forgetToken() method, i've got this error message : "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method" when he try to authorize the oauth connection of api in safari web view from an OAuth2Grant type. What's the problem exactly ? I can't found any serious explanation to fix this problem...
Thanks for your work and replying ! 

Swift version 2.2
Build on IOS 9.3.

**Comment by p2** [comment]
`forgetToken()` is only local, it does not do an API call. When exactly are you getting this error? Can you set `oauth2.verbose = true`, then give the complete log here?

**Comment by emericspiroux** [comment]
[Debug] OAuth2: Opening authorize URL in embedded Safari: https://api.intra.42.fr/oauth/authorize?client_id=<hidden client_Id>&redirect_uri=correct42%3A%2F%2Foauth-callback%2Fintra&response_type=code&state=FC5DFE26
[Debug] OAuth2: Handling redirect URL correct42://oauth-callback/intra?code=<hidden code>&state=FC5DFE26
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Exchanging code <#hidden code#> for access token at https://api.intra.42.fr/oauth/token
[Debug] OAuth2: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

**Comment by p2** [comment]
So you're getting the code but code exchange fails. Is there an API documentation for their OAuth2 implementation somewhere? Or you could just try `oauth2.authConfig.secretInBody = true` and see if that helps.

**Comment by emericspiroux** [comment]
The 42 api documentation web site is here : https://api.intra.42.fr/apidoc/guides/web_application_flow

Step 0 - User is logged in and application worked.
Step 1 - He revoke his api access from 42 web site.
Step 2 - User fetch an 405 and go to the connect view at the next request.
Step 3 - Try to logged in again, safari will be displayed with id/password fields.
Step 4 - After typing my id/password he was redirect to authorization page web site in Safari.
Step 5 - He was Redirect to my redirect_uri and application displayed the error message.

oauth2.authConfig.secretInBody = true // doesn't work. 😢

**Comment by p2** [comment]
Wait, you're revoking access – do you revoke access for the client-id? Then it would be expected that you're not getting a token again.

**Comment by emericspiroux** [comment]
No, only user authorization. I'll waiting for reply of api dev team tomorrow at 11:00am GMT+1. I'll give you some details about revoking user authorization dark sides as soon as possible. You can count on me ! Maybe a pull request why not ? ;)

**Comment by p2** [comment]
Sure, keep me posted on what you find!

**Comment by emericspiroux** [comment]
Ok, i've a problem with the api !

In fact, he can't get deepLink because system was made for Website and revoke create a problem in Api redirect_uri in 42 BDD and returning an 401.
But this human issue occurred because we can't see http status code in error receive by "afterAuthorizeOrFailure" callback. Maybe you should send `(error: NSError?) -> Void` instead of `(wasFailure: Bool, error: ErrorType?) -> Void` to let the dev' know what kind of error his oauth request receive... If you setting this feature you can use negative status code to explain an P2_OAuth error with a beautiful array in readme and a message in userInfos dictionary ;) (yes i trying a little idea inception 👍 ). Or a faster way : simply display request response in verbose mode. ;) Do you want me to add this issue ? 
Thanks for you're work and the moment spend for my problem. Your project is really easy to use and the best tools for oauth on IOS that i ever seen ! Keep me posted on the feature ! (Normally, i'll see it when my Xcode will report a bug at P2_oauth cocoapod update ;))

**Comment by p2** [comment]
Good to know!

So actually, the `ErrorType` is what you want, it will tell you the [exact error](https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2Error.swift) that was returned. You got `Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`, which is what the server said, probably with a 401.

If you want to see the full request and response you can do so with a [trace logger](http://p2.github.io/OAuth2/Classes/OAuth2Base.html#/s:vC6OAuth210OAuth2Base6loggerGSqPS_12OAuth2Logger__), which you can use like:

```swift
oauth2.logger = OAuth2DebugLogger(.Trace)
```

I think I need to write better documentation. 🙂

Does this help?

**Comment by emericspiroux** [comment]
I've got some fresh news ! I am the only one to have this error on the api (No problem with Android deep link after revoke user authorization or on web) and it's work on iphone 4s but i've got 401 on Iphone 5. The ball is on p2_oauth camps now. 

After analyze:
I can do the token request manually (with postman) and get a Token !
For this request i don't need any Header, client_id and client_secret are in the body in x-www-form-urlencoded.
So i activated oauth.authConfig.secretInBody but it doesn't work too.
After debugging secret/client token give to OAuth initializer, i've seen that the secret token was empty oO. I fetching the plist row "secret" and not "Secret" TT and after solving this... it's work.
I think XCode compilation cache give me some wrong clues about my problem because it's work sometime and in other time it's didn't. The biggest time past on debug, cause by a word mismatch case, of my life. I'm proud to say that is my personal record, what your ? ^^

It's really my bad, p2.oauth work perfectly !
Thanks for ErrorType i've not seen this detail and specially for you're patience. =D

**Comment by p2** [comment]
Great, thanks for confirming!

**Comment by mtiller** [comment]
I also ran into this issue and I'd like to point out that implicit flow has been deprecated by Gitlab (and new applications will not allow it).  But if more so, [it is removed from OAuth 2.1](https://oauth.net/2.1/).  So it really seems like using OIDC is going to get harder and harder as a result which is a bummer because it works very well with our SSO system.
