### ISSUE TITLE
Overwhelmed Dev - Trouble Implementing 

### ISSUE THREAD

**Issue by jpcguy89** [p2/OAuth2#135]
Hey,

I'm developing an app, and stressing out hard :P . I'm having trouble figuring out exactly how to authorize a user in my app. Right now I'm trying to implement it like this:

`var success : Bool = false`
`        let serviceOAuth2 = OAuth2CodeGrant(settings: serviceSettings)`
`        serviceOAuth2.onAuthorize = { parameters in`
`            success = true`
`        }`
`        serviceOAuth2.onFailure = { error in`
`            if let error = error {`
`                print("Authorization failed: \(error)")`
`            }`
`            success = false`
 `       }`
`        serviceOAuth2.authorizeEmbeddedFrom(UIViewController())`
`        return success`

Do I need a dedicated ViewController to pass to it? Does the ViewController need to have a webview inside of it? Any tips?

**Comment by p2** [comment]
The view controller you have to pass is the one **from which to present the login screen**. So it must be one that's already on screen; you can simply use the root view controller: `window.rootViewController`.
