### ISSUE TITLE
OAuth2 for tvOS 

### ISSUE THREAD

**Issue by basha121** [p2/OAuth2#141]
I see title : OAuth2 frameworks for macOS, iOS and tvOS written in Swift 3.0.

but not actual code for tvOS, so is there any possibility for tvOS?

**Comment by p2** [comment]
There is a `tvOS` target, just select it top left in Xcode or check it out using Carthage/CocoaPods. 👍🏼

**Comment by basha121** [comment]
Thanks for your reply. 

I see code for tvOS, 

	public func openAuthorizeURLInBrowser(_ url: URL) throws {
		throw OAuth2Error.generic("Not implemented")
	}
	
	public func authorizeEmbedded(with config: OAuth2AuthConfig, at url: URL) throws {
		throw OAuth2Error.generic("Not implemented")
	}

I'm not sure, is this target ready to use with tvOS or not?

**Comment by p2** [comment]
Yes, it can be used, but since there is no browser on tvOS you can not use flows that require display of a web page, like password and client credentials grants.
