### ISSUE TITLE
Can not link framework to app

### ISSUE THREAD

**Issue by stephen-talari** [p2/OAuth2#142]
My environment is `xcode 8`, `p2/OAuth2 branch => swift-2.3`,  `legacy swift => yes`
I am able to compile successfully with pod p2.OAuth2 installed but i am not able to link the framework to my app. **I can not find the library in _Target Dependencies_**. 

I couldn't find the same linking options as shown in the https://github.com/p2/OAuth2#installation

![](https://raw.githubusercontent.com/p2/OAuth2/master/assets/step-linking.png)

**My project settings are as below:**

![screen shot 2016-09-23 at 3 07 43 pm](https://cloud.githubusercontent.com/assets/1725945/18781494/94932cf2-819f-11e6-9330-112ee371be33.png)

how to i properly link in xcode 8 and make it work.

**Comment by p2** [comment]
You only need to do the manual linking when using OAuth2 from Github directly. If you use Cocoapods, all you need to do is correctly initialize your pod (which sounds like you have already done) and then open the **workspace** (not the _xcodeproj_). Cocoapods will take care of linking.

**Comment by stephen-talari** [comment]
Thank you. I was trying with `extension p2_OAuth2`. Naming conventions is little bit confusing. Its `import p2_OAuth2`, but for extension it is `extension OAuth2`.

**Comment by p2** [comment]
This is only for CocoaPods and only applies to the framework name, not class names.
