### ISSUE TITLE
authorize() callbacks not triggered

### ISSUE THREAD

**Issue by stephen-talari** [p2/OAuth2#143]
After authorize() call, callbacks are never executed. Neither error or timeout happens.

This is my code snippet (called on button tap), line `print("Authorize is called.")` is executed, but not callbacks. 

```

        let settings = [
            "client_id": "ZHkr4WZNdhUMReRvQEq9bn98Y3QQE2GyxOsQ",
            "client_secret": "bsdU7KNkd86S4ZMxybErgm2rbG7MZ6X5vaeIkSf6F8ky0RK",
            "token_uri": "http://xx.xx.xx.xx/oauth/token",
            "username": "stephen",
            "password": "steve123",
            "keychain": false,
            "verbose" : true
            ] as OAuth2JSON
        
        let p2oauth2 = OAuth2PasswordGrant(settings: settings)
        
        p2oauth2.authorize()
        
        print("Authorize is called.")
        
        // callback on SUCCESSFUL authorization
        p2oauth2.onAuthorize = { parameters in
            print("\n onAuthorize parameters : \(parameters) \n")
        }
        
        // callback on authorization FAILURE
        p2oauth2.onFailure = { error in
            print("Authorization went wrong: \(error.debugDescription)")
            
        }
```
**Note: No request is received on server side**

Debug prints only this

```
[Debug] OAuth2: Initialization finished
[Debug] OAuth2: No access token, maybe I can refresh
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: You MUST use HTTPS/SSL/TLS

```

Environment: `xcode 8`, `pod branch 2.3`

**Comment by p2** [comment]
Your OAuth2 instance is deallocated immediately, you need to hold on to it, for example in a property on a view controller or app delegate.

**Comment by stephen-talari** [comment]
Issue still exists even after using a class property. Callback are never executed.

Class members:
```
    var authSettings:OAuth2JSON! = nil
    var p2oauth2:OAuth2PasswordGrant! = nil
```

Authorization call:
```
    @IBAction func loginButtonTapped(sender: AnyObject) {
        authSettings = [
            "client_id": "ZHkr4WZNdZ0rqhUMReRvQEq9bn98Y3QQE2GyxOsQ",
            "client_secret": "bsdU7KNkd86S4ZMxybErgm2rb9t6G7MZ6X5vaeIkSf6F8ky0RK",
            "token_uri": "http://10.32.16.32:5000/oauth/token",
            "username": "stephen",
            "password": "steve123",
            "keychain": false,
            "verbose" : true
            ] as OAuth2JSON
        
        p2oauth2 = OAuth2PasswordGrant(settings: authSettings)
        
        p2oauth2.authorize()
        
        print("Authorize is called.")
        
        p2oauth2.onAuthorize = { parameters in
            print("\n onAuthorize parameters : \(parameters) \n")
        }
        
        p2oauth2.onFailure = { error in
            print("Authorization went wrong: \(error.debugDescription)")
        }
    }

```

Doubt if authorize() reading settings from its class members?

**Comment by p2** [comment]
This should call the failure callback with _You MUST use HTTPS/SSL/TLS_. What is it logging?

**Comment by stephen-talari** [comment]
i am not using https. Is that why it is failing? 

log:
```
[Debug] OAuth2: Initialization finished
[Debug] OAuth2: No access token, maybe I can refresh
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: You MUST use HTTPS/SSL/TLS
Authorize is called.
```

**Comment by stephen-talari** [comment]
Even though https is not configured on server, i tried https in `token_uri `, now i can see the request coming to server. So now i have to implement https on server. Previously this library used with http also.

**Comment by p2** [comment]
The library should not work with `http` since that is illegal in OAuth2. Weird that the error callback hasn't been called for you.

Anyway, all development is in Swift 3 now, the 2.3 branch is not maintained. I'm waiting on CocoaPods to fix a bug so version 3.0 can be pushed.

**Comment by stephen-talari** [comment]
@p2 Thank you for your quick responses. 
As we can not move our entire app to swift 3 quickly, for now we moved to swift 2.3. Hopefully will be moving to swift 3 soon. Thank you

**Comment by p2** [comment]
Sure, I understand the Swift versioning problem, just wanted to point out that this framework focuses on Swift 3 at this point. :)

**Comment by ryanwaggoner** [comment]
This is closed, but just curious as to whether maybe the callbacks weren't being executed because they were setup after authorize() was called...

**Comment by p2** [comment]
Yes, you're exactly right - since the call never went over the wire, the callback fired immediately, which is before the closure is/was assigned.

**Comment by ryanwaggoner** [comment]
Huzzah! I'm a real programmer!! :)
