### ISSUE TITLE
Why does the library use Keychain.swift twice?

### ISSUE THREAD

**Issue by chanhyeoni** [p2/OAuth2#144]
When I tried to bulid the project, the following error came out.

filename "Keychain.swift" used twice: '~/Desktop/Programming/iOS/OAuth2/SwiftKeychain/Keychain/Keychain.swift' and '~/Desktop/Programming/iOS/OAuth2/Sources/SwiftKeychain/Keychain.swift'

Is it that I included the library in a wrong way? I used git by the way. Please give me the reason ASAP.

**Comment by p2** [comment]
One is just a symlink for the Swift package manager. The class is only included once. How did you build the framework?

**Comment by chanhyeoni** [comment]
I did as the manual says. I didn't get the pod command installed, so I
manually dragged & dropped the library. Then, I added the framework files
to the target dependencies, link binaries with libraries, and embed
frameworks

[image: Inline image 1]

**Comment by chanhyeoni** [comment]
I did as the manual says. I didn't get the pod command installed, so I
manually dragged & dropped the library. Then, I added the framework files
to the target dependencies, link binaries with libraries, and embed
frameworks
![screen shot 2016-09-25 at 6 26 38 pm](https://cloud.githubusercontent.com/assets/5059539/18819197/77ea789c-8359-11e6-813f-4f01148d67f9.png)

**Comment by p2** [comment]
Looks like you embedded all source files manually, you're not using the Xcode project file. If you do that, only include the files in the `Sources` directory, skipping `macOS` and `tvOS`, or [follow the instructions](https://github.com/p2/OAuth2#git) to properly add the framework.
