### ISSUE TITLE
Update library to be Protocol Oriented 

### ISSUE THREAD

**Issue by cyr-lepottier** [p2/OAuth2#146]
Hello,

The inclusion of final methods, notably in OAuth2, prevents me from mocking and Unit Testing my project. Since Swift doesn’t have readwrite reflection, subclassing remains the only way to Mock. 

Could the code be updated to use protocols and make the projects that uses the library testable ?

Thanks,
Cyril

**Comment by p2** [comment]
That's a rather broad request. The library uses protocols in many places, what exactly are you unable to test, what do you need changed so you can implement your tests?

**Comment by cyr-lepottier** [comment]
Thanks for you quick answer,

We have some classes responsible of implementing Authorization via OAuth2, they use your library and implement our protocols.
```swift
import OAuth2
func class OAuth2Implementation: OAuth2Service {
    func setOAuth2Client(client: OAuth2) //Here we inject your library
}
```
That way, we ensure that any library can be swapped easily at any time. The rest of the app has indeed no knowledge about any library, but just about the protocol we expose.

So far, so good. Now, we aim to unit test our OAuth2Implement, but we don't want it to perform any network call. Plus, we want to test our implementation, not your library. It is where we start to use Mock/Double:
```swift
import OAuth2
func class OAuth2Mock: OAuth2 {
    // Here we override some methods, basically the one that are used by OAuth2Implementation
     override func authorize(params params: OAuth2StringDict? = nil) //This won't compile
}
```

Mock + dependency injection should allow us to test OAuth2Implementation:
```swift
import XCTest
class OAuth2ImplementationTests: XCTestCase {
    func test_GivenSomeStuff_WhenAuthorizing_ThenItDoesStuff() {
       let service = OAuth2ServiceImpl()
       let oauth2 = OAuth2CodeGrantMock()
       service?.setOauth2Client(oauth2)

      service.authorize() // At the moment, this will call your implementation rater than a mock one
   }
}
```

Hope this help, I will be happy to clarify some points if needed. 
To summaries the answer to your question, I need to be able to mock the OAuth2 class and notably its authorize() method (potentially some more) in order to perform my tests.

**Comment by p2** [comment]
This makes sense. You don't need to subclass `OAuth2` since it has a `requestPerformer` property, a type adhering to the `OAuth2RequestPerformer` protocol. You can replace the request performer with your own implementation that doesn't round-trip via the web. There is an example in our own unit tests in [`Tests/DataLoaderTests/OAuth2DataLoaderTests.swift#46`](https://github.com/p2/OAuth2/blob/master/Tests/DataLoaderTests/OAuth2DataLoaderTests.swift#L46).

This way you can use the "real" OAuth2Xy class that you'll be using anyway. Does this help?

**Comment by cyr-lepottier** [comment]
Thank you, it actually helps a lot. OAuth2RequestPerformer sounds a nice way to achieve what I want, it is unfortunately not available to me, surely because I don't use the latest version, so no issue, I should upgrade  it very shortly anyway.

Looking around for it, I have found this nicely documented method that should do the job for now
```swift
/**
Method to actually start authorization. The public `authorize()` method only proceeds to this method if there is no valid access token and if optional client registration succeeds.
    	
Can be overridden in subclasses to perform an authorization dance different from directing the user to a website.
    	
- parameter params: Optional key/value pairs to pass during authorization
*/
public func doAuthorize(params params: OAuth2.OAuth2StringDict? = default) throws
```

Thanks again and congrats for your nice library.

**Comment by p2** [comment]
Alright, sounds good, I'll close this then, re-open if you're still stuck so I can make the library more test-friendly. 👍🏼
