### ISSUE TITLE
Swift 3 OAuth2Grant has no member oauth.authorizeEmbeddedFrom and oauth.afterAuthorizeOrFailure

### ISSUE THREAD

**Issue by qadirsuh** [p2/OAuth2#149]
I just updated the code to swift 3. I want to am getting errors

_OAuth2Grant has no member oauth.authorizeEmbeddedFrom and oauth.afterAuthorizeOrFailure_

I have tried alot to resolve this.

`//        Native webview Controller Authenticaion
            
            let vc   = appDelegate.window!.rootViewController
            var web:OAuth2WebViewController!
            
            
            if let uber_login_status  = UserDefaults.standard.string(forKey: "uber_login"){
                
                print(uber_login_status)
                
                //Clear Uber Login Credentials
                if(uber_login_status == "0"){
                    
                    let appDelegate = UIApplication.shared.delegate as! AppDelegate
                    appDelegate.oauth.forgetTokens()
                }
            }
            
            if(appDelegate.oauth.hasUnexpiredAccessToken()){
                
                print("Un-Expired Access Token")
                self.navigationController?.pushViewController(self.UberPersonalDriver_VC, animated: true)
                
            }else{
                print("Expired Access Token")
                web = appDelegate.oauth.authorizeEmbeddedFrom(vc!, params: nil)
            }
            
            // OAuth2 URL Handler
            appDelegate.oauth.afterAuthorizeOrFailure = { wasFailure, error in
                
                if(!wasFailure){
                    
                    
                    web.dismiss(animated: true, completion: nil)
                    self.personalDriverLoader.stopAnimating()
                    self.navigationController?.pushViewController(self.UberPersonalDriver_VC, animated: true)
                    
                    
                    print("accessToken \(self.appDelegate.oauth.accessToken)")
                    print("accessTokenExpiry \(self.appDelegate.oauth.accessTokenExpiry)")
                    print("authConfig \(self.appDelegate.oauth.authConfig)")
                    print("refreshToken \(self.appDelegate.oauth.refreshToken)")
                    
                    
                }else{
                    print("Failed Or Canceled")
                    self.personalDriverLoader.stopAnimating()
                }
                
            }`

I am using Pods method

**Comment by p2** [comment]
These methods have been deprecated in version 3, please see the readme for updated usage patterns.

**Comment by qadirsuh** [comment]
Does this lib available in on Pods

I read the REAM.me file its mention that

_#pod 'p2.OAuth2', '~> 3.0'  # NOT YET AVAILABLE_

How should I install this? what you recommend?

**Comment by p2** [comment]
The line right below that one explains how to do it via CocoaPods. ;)
