### ISSUE TITLE
Data Loader vs Alamofire

### ISSUE THREAD

**Issue by sigursalt** [p2/OAuth2#150]
Hey Pascal,

Is there a benefit to using Alamofire over your Data Loader?   Your included loader seems less verbose.   Is it just an option for those who may already be using Alamofire to keep their network calls under one umbrella?  

Thanks!

**Comment by liltimtim** [comment]
@sigursalt Hello!

Under section 2 of the read me, it offers the solution you seek specifically [this](https://github.com/p2/OAuth2/wiki/Alamofire-4) wiki article.  It explains how to use some new features in Alamofire 4.0.0

**Comment by sigursalt** [comment]
Thanks for that.   I have the included Data Loader working just fine - I'll create one using the Alamofire piece just for the fun of it.

Keep up the great work on this library!

**Comment by p2** [comment]
So yes, this is just for those who have been using Alamofire or really want to use it. I also use the DataLoader myself. 😏
