### ISSUE TITLE
Use of undeclared type 'HTTPURLResponse'

### ISSUE THREAD

**Issue by aadilimperoit** [p2/OAuth2#153]
Hi,

I have just installed the Pod using 

pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2', :submodules => true'

And i simply run the app it showed me 445 errors, I have attached screenshot herewith. 

![screen shot 2016-10-13 at 10 17 47 am](https://cloud.githubusercontent.com/assets/21188912/19337016/540a5f04-912e-11e6-9cc4-bc4055a20e08.png)
 
![screen shot 2016-10-13 at 10 16 00 am](https://cloud.githubusercontent.com/assets/21188912/19337006/3e1e29dc-912e-11e6-88cc-398dc94cb7fb.png)

**Comment by p2** [comment]
Are you using Xcode 8?

**Comment by aadilimperoit** [comment]
No i am on xCode 7.3

**Comment by p2** [comment]
See the README; Xcode 7.3 uses Swift 2.2, so you must use version 2.2 of the OAuth2 library:
https://github.com/p2/OAuth2#swift-version

**Comment by aadilimperoit** [comment]
Thanks for the info, however i am using 2.3, i tried installing the pod for 2.3,

  pod 'p2.OAuth2', '2.3.0', :git => 'https://github.com/p2/OAuth2', :submodules => true

But i am getting following issues :  [!] A dependency with an external source may not specify version requirements (p2.OAuth2).

Even tried   pod 'Alamofire', '3.5.0'

Can you help ?

**Comment by p2** [comment]
For version 2.3, simply use:

```
pod 'p2.OAuth2', '~> 2.3`
```

**Comment by aadilimperoit** [comment]
Hi,

I have tried that but getting following error : 

[!] Unable to satisfy the following requirements:

- `p2.OAuth2 (~> 2.3)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `p2.OAuth2 (~> 2.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default

**Comment by p2** [comment]
Did you try `pod repo update`?

**Comment by aadilimperoit** [comment]
Yes i did that 

Imperos-iMac:iAuth imperoit$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `p2.OAuth2 (~> 2.3)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `p2.OAuth2 (~> 2.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

[!] CocoaPods was not able to update the `Specs` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

**Comment by p2** [comment]
You get a warning in the end that your specs could not be updated, please follow that advice and try again.

**Comment by aadilimperoit** [comment]
Hi,

But warning says 

"out-of-date source repos which you can update with pod repo update.
mistyped the name or version.
not added the source repo that hosts the Podspec to your Podfile."

**Comment by p2** [comment]
No I mean the warning at the end:

> [!] CocoaPods was not able to update the Specs repo. If this is an unexpected issue and persists you can inspect it running pod repo update --verbose

**Comment by p2** [comment]
Do you need to use CocoaPods or can you switch to something better, like Carthage?

**Comment by aadilimperoit** [comment]
Other pods update and install its issue with this version only. So i dont think its issue with POD As i am able to install latest version of this POD.

**Comment by p2** [comment]
What's happening is that your local Pods Specs are not up to date. Your other pods have not been updated in the meantime, so they still work, but OAuth2 has and your local Pod does not see the version. But it must be there since version `2.3.0` is on the website: https://cocoapods.org/?q=oauth2

**Comment by aadilimperoit** [comment]
I tried downloading code and compiling the swift 2.3. version (via https://github.com/p2/OAuth2/releases/tag/2.3.0), it says 

Error: no such file or directory: '/Users/XXX/Downloads/OAuth2-2.3.0 3/SwiftKeychain/Keychain/Keychain.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by p2** [comment]
That's because OAuth2 uses submodules. Use the following git commands instead of downloading manually:

```
git clone --recursive https://github.com/p2/OAuth2.git
cd OAuth2
git checkout tags/2.3.0
```

**Comment by p2** [comment]
By the way, the [OAuth2PodApp](https://github.com/p2/OAuth2PodApp/tree/swift-2.3) test app works with CocoaPods and OAuth2 version 2.3. The error is in your local CocoaPods repo.

**Comment by aadilimperoit** [comment]
Hi,

I followed you for git clone and here is the output : 

![screen shot 2016-10-13 at 12 34 41 pm](https://cloud.githubusercontent.com/assets/21188912/19339521/8206e0b8-9141-11e6-8308-7b5bf8508ae5.png)
![screen shot 2016-10-13 at 12 34 27 pm](https://cloud.githubusercontent.com/assets/21188912/19339522/820f487a-9141-11e6-9ee2-01297efbddf5.png)

**Comment by p2** [comment]
You are on version 3.0, not on version 2.3. Did you do `git checkout tags/2.3.0`?

**Comment by aadilimperoit** [comment]
I followed the test app and double clicked on workspace to open project and here is the output :  

![screen shot 2016-10-13 at 12 33 20 pm](https://cloud.githubusercontent.com/assets/21188912/19339540/9efcbcc4-9141-11e6-86e8-47ef0e4c8a37.png)

**Comment by aadilimperoit** [comment]
I followed : 
git clone --recursive https://github.com/p2/OAuth2.git
cd OAuth2
git checkout tags/2.3.0

**Comment by p2** [comment]
Wait; you're on Xcode 7.3, does this even have Swift 2.3? Should it not be Swift 2.2? Did you try OAuth2 version `~> 2.2`?

**Comment by aadilimperoit** [comment]
It does support swift 2.3, however I migrated to 2.2 seems to removed other errors but got one :  

![screen shot 2016-10-13 at 12 45 01 pm](https://cloud.githubusercontent.com/assets/21188912/19339768/fdfc993c-9142-11e6-936a-5779439228e8.png)

I really appreciate your followup replies. Thanks mate

**Comment by p2** [comment]
This is a difference between Swift 2.2 and 2.3. If you check out OAuth2 version 2.2.9 with `get checkout tags/2.2.9` this should resolve.

**Comment by aadilimperoit** [comment]
I know the difference, I did checkout with 2.2.9 here is the screenshot for the same 

![screen shot 2016-10-13 at 12 52 18 pm](https://cloud.githubusercontent.com/assets/21188912/19339956/09d3eb88-9144-11e6-8b57-526ddfafe5a8.png)
![screen shot 2016-10-13 at 12 52 56 pm](https://cloud.githubusercontent.com/assets/21188912/19339955/09d4132e-9144-11e6-9b25-d531e39b3bec.png)

**Comment by p2** [comment]
Do a `git submodule update`

**Comment by aadilimperoit** [comment]
Thanks mate, It worked like charm 👍  💯

**Comment by p2** [comment]
Alright great!! 👍🏼
