### ISSUE TITLE
Error fetching from Keychain: Error Domain=swift.keychain.error Code=-25300

### ISSUE THREAD

**Issue by Collibhoy** [p2/OAuth2#154]
On OSX El Capitan, Mac application using version 3 of OAuth2 (Swift 3)

Logs in and appears to store to keychain but fails to get it back out again so returns me to login.  Custom web app with OAuth2 using PasswordGrant

Debug logging;
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: No username
[Debug] OAuth2: Forgetting tokens and removing them from keychain
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Requesting new access token from https://bonzapi.io/oauth/token
[Debug] OAuth2: Did get access token [true]
[Debug] OAuth2: Storing tokens to keychain
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: Have an apparently unexpired access token
[Debug] OAuth2: Storing tokens to keychain

Closing the app and opening again just follows the same flow, so never seems to get the stored token from the Keychain - did I miss something to enable the keychain?

**Comment by Collibhoy** [comment]
I enabled Keychain sharing, compiled, disabled keychain sharing, and now it's working.

**Comment by p2** [comment]
Related: #147
