### ISSUE TITLE
Popup support in embedded login view

### ISSUE THREAD

**Issue by emreoktem** [p2/OAuth2#155]
I am developing a OSX app that connects to multiple services with Oauth. Some of them uses urn:ietf:wg:oauth:2.0:oob format.

As far as I read from the documentation I must use embedded login view to handle redirect from the service.

On the other hand there are multiple login types on some of these services' login pages which allows users also to use OAuth of another service. For example, 

https://app.asana.com/-/oauth_authorize 

On this example, when the user wanted to login with Google, page opens a popup in order to let the user using his Google account and this process is not supported by the current embedded view.

Do you have a workaround for this case or is it possible to support the popup cases in the current embedded view?

**Comment by p2** [comment]
Ha, that's really special. So you want your users to be able to authorize via Asana, which uses a `urn:ietf:...` callback, but Asana allows users to authenticate via Google, and this opens a popup? This being macOS it might work without embedded web-view, with the users copying code from the browser. The mac sample app does this with the Google demo login, maybe you can take a look and try to build it similarly for your implementation?

https://github.com/p2/OAuth2App/blob/master/OAuth2App/ViewController.swift#L138

**Comment by emreoktem** [comment]
I have one minor and one major problems with this method.

Minor problem: In my case, my app is trying to authorize seamlessly in the background and I don't have an interface to let user paste. 

Major problem: I cannot know if the user will use Asana login or Google login when he's redirected to the login page.

Do you have any another idea or a workaround to handle this in embedded view?

**Comment by p2** [comment]
Afraid I don't have experience with such mechanisms, I'm only using the library directly with OAuth2 providers.

**Comment by emreoktem** [comment]
Thanks for the feedback
