### ISSUE TITLE
Keychain choice

### ISSUE THREAD

**Issue by Goule** [p2/OAuth2#156]
Hello,

It is possible to have keychain proposition for login (for Google, Facebook etc...) ? 
Like in this screen : 

![03](https://cloud.githubusercontent.com/assets/21126201/19832396/088d0b60-9e23-11e6-9cff-e09df9501712.png)

Or there are simple way to do it ? 
Thank you :)
Goule

**Comment by p2** [comment]
Sorry for the delay.

Since it's a design feature of OAuth2 that the client app does not actually know the login credentials of the user – except if using _client credentials_ flow – I do not think this should be part of an OAuth2 framework. So no, I do not want to add this I'm afraid.
