### ISSUE TITLE
Issue with exchangeCodeForToken with Google

### ISSUE THREAD

**Issue by stefanhp** [p2/OAuth2#160]
Hi,

I don't know how else to ask a question, so opening an issue.

I've successfully authorised an iOS app with Google. I'm getting the callback on a custom scheme. From there I call handleRedirectURL(url) on my OAuth2CodeGrant instance, which validates the received code. But the call then fails in ```exchangeCodeForToken``` with a JSON parsing error, but more importantly the actual response content from Google is a 400 error with the reason "Required parameter is missing: response_type".

I've setup the OAuth2CodeGrant settings with an entry "response_type": "code" but this seems not to be copied into the post request of exchangeCodeForToken:
```let post = try accessTokenRequest(with: code).asURLRequest(for: self)```

Is this a bug or am I missing a step somewhere?

Thanks

**Comment by stefanhp** [comment]
It's weird, because according to https://developers.google.com/identity/protocols/OAuth2InstalledApp#handlingtheresponse the request is properly formed and has all the right parameters, that is "grant_type", "code", "redirect_uri" and "client_id"...

**Comment by stefanhp** [comment]
I'm sorry, I missed ```"token_uri": "https://www.googleapis.com/oauth2/v4/token"``` in the config.
All is working now, closing this issue.

**Comment by p2** [comment]
Great! Also take a look [at the Google page in the Wiki](https://github.com/p2/OAuth2/wiki/Google), maybe it has some more hints. And if something is out of date I'd be glad if you'd ping me. 😎

**Comment by stefanhp** [comment]
Actually, since v4, Google is no longer accepting an "Other" client ID, you MUST create an iOS Client ID (it detects then web view user agent and returns a 400 error if you are using "Other").

**Comment by p2** [comment]
Great, thanks, I've updated the wiki.
