### ISSUE TITLE
Embedded not working

### ISSUE THREAD

**Issue by rezasham** [p2/OAuth2#164]
In my view controller which is a modal one, I have a button that triggers the authentication flow. I set these:

oauth2.authConfig.authorizeEmbedded = true
oauth2.authConfig.authorizeContext = self

However, the safari window opens. I would like to run this in a webview style with no address field etc.
I´m using Xcode 8.1 with IOS 10 

Appreciate any help.

R

**Comment by p2** [comment]
See here [towards the end of the “Advanced Settings” paragraph](https://github.com/p2/OAuth2#advanced-settings) on how to not use Safari View Controller. But please note that you are **strongly discouraged** from using the built-in web view, this should not be done any more.
