### ISSUE TITLE
Client id and client secret should not be www-form-url-encoded before UTF-8 and Base 64 encoding in Authorization Header

### ISSUE THREAD

**Issue by gudavo** [p2/OAuth2#165]
In OAuth2AuthRequest.swift, client id and secret are www-form-url-encoded and concatenated with :, then UTF-8 and Base 64 encoded and put in Authorization Header
```
oauth2.logger?.debug("OAuth2", msg: "Adding “Authorization” header as “Basic client-key:client-secret”")
let pw = "\(clientId.wwwFormURLEncodedString):\(secret.wwwFormURLEncodedString)"
if let utf8 = pw.data(using: String.Encoding.utf8) {
    req.setValue("Basic \(utf8.base64EncodedString())", forHTTPHeaderField: "Authorization")
}
```
The part www-form-url-encoded is wrong, according to what is done by major browsers:
http://stackoverflow.com/a/9056877
And it causes a 401 error in my case.

**Comment by p2** [comment]
Hmmm, it seems it's a little bit complicated: https://tools.ietf.org/html/draft-ietf-httpauth-basicauth-update-07#section-2.1

Against which server are you using the library? I'll have to look into above link more closely and/or make the encoding to use configurable. Clearly we _should_ be using UTF-8 at this point in time, but if it breaks it should fall back to ancient times.

**Comment by gudavo** [comment]
I am using the library against an OpenAM server. I think this behavior is server-dependent, and as you pointed not very clear in the RFC spec, so it should be configurable in the library.

**Comment by p2** [comment]
Sorry this took a while – if you're still in need of this, you could set `oauth2.clientConfig.authStringEncoding` to another encoding than UTF-8 to see if that satisfies your server.

(Just to note, the problem seems not to be the form-encoding, but the defaulting to UTF-8)
