### ISSUE TITLE
Can't login using OAuth2PasswordGrant class.

### ISSUE THREAD

**Issue by bibekdari** [p2/OAuth2#167]
I am using this library in Swift 3 project. I initialized OAuth2PasswordGrant with settings with username, password, client_id, client_secret, authorize_uri and keychain. And called the authorize function. the error I got was unsupported_grant_type.

self.oAuth = OAuth2PasswordGrant(settings: settings)
self.oAuth.authorize { (json: OAuth2JSON?, error: OAuth2Error?) in
    // did sth here           
}

Did I missed anything?

**Comment by p2** [comment]
This usually means the auth server does not support a password grant. Which OAuth2 server are you trying to authorize with?

**Comment by bibekdari** [comment]
When I used Alamofire request using  POST method, I was able to get expected response (success with access_token and all) with password grant_type.
let path:String = BaseURL + "login"
        
        let parameters:[String:String] = ["grant_type": "password","client_id": "1", "client_secret": clientSecret, "username": username, "password": password, "scope":""]
        let headers:[String:String] = ["Content-Type": "application/json"]
        
        Alamofire.request(path, method: .post, parameters: parameters, encoding: JSONEncoding.default, headers: headers).validate(statusCode: 200..<500).responseJSON { response in
            print(path)
            print(parameters)
            switch response.result {
            case .success(let value):
                switch response.response?.statusCode {
                case 200?:
                    if let login: Login = JSON(value).map() {
                        print(login)
                        success(login)
                    }
                default:
                    if let serverError: ServerError = JSON(value).map(), let error = serverError.error {
                        failure(error)
                    }else {
                        failure(undefinedError)
                    }
                }
            case .failure(let error):
                failure(error)
            }
        }

**Comment by p2** [comment]
Can you turn on logging to see where it might go wrong? Like this:

    oauth2.logger = OAuth2DebugLogger(.trace)

**Comment by bibekdari** [comment]
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Requesting new access token from <URL Here>
[Trace] OAuth2: REQUEST
HTTP/1.1 POST <URL Here>
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Authorization: Basic MToxUGhsSHdUQkRES0M3R0dIZERVM2FVZnBoNWMxSG5nWmZYUVhZVUcy

grant_type=password&username=salina&password=salina100
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 400 bad request
Content-Type: application/json
Connection: close
Content-Length: 163
Vary: Authorization
Server: Apache/2.4.7 (Ubuntu)
Date: Tue, 03 Jan 2017 10:22:50 GMT
Cache-Control: no-cache

{"error":"unsupported_grant_type","message":"The authorization grant type is not supported by the authorization server.","hint":"Check the `grant_type` parameter"}
---
[Debug] OAuth2: Error obtaining access token: Authorization error: unsupported_grant_type
[Debug] OAuth2: Authorization error: unsupported_grant_type

**Comment by p2** [comment]
This is weird since `grant_type` is the same as what you're supplying when using Alamofire directly.

So the server is giving the wrong error; maybe it's confused by the _Authorization_ header, try setting client-id/secret in the request body (like you did with Alamofire):

    oauth2.authConfig.secretInBody = true

Or in the settings dict:

    "secret_in_body": true

**Comment by bibekdari** [comment]
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Adding “client_id” and “client_secret” to request body
[Debug] OAuth2: Requesting new access token from <URL here>
[Trace] OAuth2: REQUEST
HTTP/1.1 POST <URL Here>
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept: application/json

grant_type=password&client_id=1&client_secret=<ValidClientSecretIsHere>&username=salina&password=salina100
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 400 bad request
Content-Type: application/json
Content-Length: 163
Connection: close
Server: Apache/2.4.7 (Ubuntu)
Date: Tue, 03 Jan 2017 10:33:46 GMT
Cache-Control: no-cache

{"error":"unsupported_grant_type","message":"The authorization grant type is not supported by the authorization server.","hint":"Check the `grant_type` parameter"}
---
[Debug] OAuth2: Error obtaining access token: Authorization error: unsupported_grant_type
[Debug] OAuth2: Authorization error: unsupported_grant_type

**Comment by p2** [comment]
As you can see, this is almost literally the same request as the one you're sending with Alamofire. Just to be sure, are you trying against the same OAuth2 endpoint?

**Comment by bibekdari** [comment]
Yes the endpoint is the same. And also, I checked where the request is created (parameter encoding and all) for OAuth request, there was password grant_type. I don't know why is this behaving like this.

**Comment by p2** [comment]
Last thing you can try is to add an empty `scope` parameter, other than that it'll be hard to figure out what's going on without being able to look at the server.

    "scope": ""

**Comment by bibekdari** [comment]
yes I did that. Still I am getting the error.

**Comment by p2** [comment]
Try to copy/paste the exact request, as logged, into `curl` or a browser. Do you get the same error? Does Alamofire generate the exact same request?
