### ISSUE TITLE
Any straightforward way to get the JSON response when authorize() fails?

### ISSUE THREAD

**Issue by ryanwaggoner** [p2/OAuth2#170]
I'm integrating against a custom and slightly off-kilter OAuth2 API (two-legged, specifically).

I have a situation where calling authorize() can fail because the user needs to validate their account. So the API won't return valid tokens until this is done, but the info needed to validate the account is in the error response that authorize() is calling.

Is there any way for the authorize() callback to get access to the API response / JSON in the case of authorization failure? 

Alternatively, any clues about the best way to subclass and override to accomplish this would be helpful. It looks like there are multiple levels that expect a failure to only have an error object.

Just want to make sure I'm not making a huge mistake or missing something obvious before I tackle this!

**Comment by p2** [comment]
Interesting. What will happen is that [`parseAccessTokenResponse(params:)`](https://github.com/p2/OAuth2/blob/c62593dd287d0cdadc4a31b67a1bdd1be50ed4bf/Sources/Base/OAuth2Base.swift#L366-L373) will call [`assureNoErrorInResponse()`](https://github.com/p2/OAuth2/blob/c62593dd287d0cdadc4a31b67a1bdd1be50ed4bf/Sources/Base/OAuth2Base.swift#L329-L340), which will throw and that's the end of it.

I think you should be able to override `assureNoErrorInResponse()`, check for your specific error key and throw something useful in your case, like `prerequisiteFailed("{ data you need}")`. Then when authorize fails, you can intercept this error and act appropriately. Could that work?

**Comment by ryanwaggoner** [comment]
Interesting, I'll try that!

**Comment by p2** [comment]
Did this work?
