### ISSUE TITLE
JSON Deserialisation issue when getting token

### ISSUE THREAD

**Issue by primarchhorus** [p2/OAuth2#174]
Hi

I'm having an issue when attempting to get the access token.

After the SFSafariViewContoller  has loaded the login url and i click approve for my app I can see in the log trace that the code has successfully been extracted from the callback and i can see that the authorizer has attempted to exchange the code for the access token but the response from the POST request to get the access token is reporting an error that it is unable to deserialise the input json data, is there anyway to check or control the json data that is being sent to the get token URL?

**Comment by p2** [comment]
Yes:

    oauth2.logger = OAuth2DebugLogger(.trace)

**Comment by primarchhorus** [comment]
Ok thanks, i can see that it's sending

grant_type=authorization_code&code=3517da3dc954328b1a16732f5041e912&redirect_uri=ppoauthapp%3A%2F%2Foauth%2Fcallback&client_id=255

But that does not seem to be in json format or at least when the post request goes to exchange the code for token the website has an issue with it.

**Comment by p2** [comment]
That's not OAuth2 conformant though, the code exchange call is supposed to be form-encoded.

Which service is this? You'll need to subclass `OAuth2CodeGrant` and override `accessTokenRequest(with code: String, params: OAuth2StringDict? = nil) throws -> OAuth2AuthRequest` in [`OAuth2CodeGrant.swift:57`](https://github.com/p2/OAuth2/blob/master/Sources/Flows/OAuth2CodeGrant.swift#L57), creating the correct JSON body.

**Comment by p2** [comment]
Actually, it'll be harder than this since the form-encoding is built-in to the auth request.

**Comment by primarchhorus** [comment]
I'm new to swift and OAuth but from what i have read so far, it's a custom implementation and seems to follow the general flow of OAuth but any input is required to be JSON. I ended up getting it working by just doing all the requests with alamofire and callback url catching myself, but thanks you for your help anyway.

**Comment by p2** [comment]
Yes, OAuth2 is simple enough to be done by hand, unless you want to cover all edge cases. 👍🏼
