### ISSUE TITLE
How to add custom parameter to request querystring? 

### ISSUE THREAD

**Issue by techbits00** [p2/OAuth2#175]
Is there a way to add custom parameter to request querystring? Currently I see there is a customParameters but it does not add parameters to the request querystring? 

I am trying to use this library with ADFS 3.0 - i see there is an AzureAD implementation which adds the resource parameter to the body for AzureAD - however ADFS 3.0 requires the resource parameter to be part of the URL querystring. 

GET /adfs/oauth2/authorize?response_type=code&client_id=some-uid-or-other&resource=relying_party&redirect_uri=XXXXXX

**Comment by p2** [comment]
This is what the `params` parameter of the [`authorize(params:callback:)`](https://p2.github.io/OAuth2/Classes/OAuth2.html#/s:FC6OAuth26OAuth29authorizeFT6paramsGSqGVs10DictionarySSSS__8callbackFTGSqGS1_SSP___GSqOS_11OAuth2Error__T__T_) method is for.
