### ISSUE TITLE
Can't get past Authorize

### ISSUE THREAD

**Issue by jcedman** [p2/OAuth2#176]
I have been stuck for days now. This is a site-specific issue. I am trying to obtain an access token using MacOS and embedded view.  I can log in to the site and it asks me properly to authorize access. However, clicking authorize does nothing. I don't even see a response (i have used .trace to get the initial "no access token" response from the server. Any ideas on how to find where the hang up is?  

I have modified the BitBucket data loader to accept embedding, my client id, secret, etc. 

Any ideas? 

Is this redirect_uri issue? 

Thanks

<img width="509" alt="screen shot 2017-01-26 at 3 07 36 pm" src="https://cloud.githubusercontent.com/assets/16310316/22354464/4bbb9abc-e3da-11e6-97f3-ed9eb76087a0.png">

**Comment by p2** [comment]
Yes, this does sound like your app is not called when you do something. So you're working off of the macOS sample app? What happens after you click “Authorize”, in the web view? Have you tried using Safari, so you can see what it's trying to load? Set a break point in [`OAuth2WebViewController`](https://github.com/p2/OAuth2/blob/master/Sources/macOS/OAuth2WebViewController.swift#L230) where it intercepts the callback, is it hit at all?

**Comment by jcedman** [comment]
I modified the macOS sample app with my configuration. 

After I click "Authorize" in the web view, nothing  happens (either on the web view or logger). Here is the output:

```
 [Debug] OAuth2: Initialization finished
 [Debug] OAuth2: Looking for items in keychain
[Debug] OAuth2: Initialization finished
VC: start loading 1
VC: start loading 2
VC: start loading 3
running requestUserdata(callback:  (Function)
2017-01-28 08:03:33.672927 DocSenderMac[2934:96075] Cannot sign request, access token is empty
func request(path: String, callback: @escaping ((OAuth2JSON?, Error?) -> Void))
[Trace] OAuth2: REQUEST
HTTP/1.1 GET https://drchrono.com/api/patients/user
Accept: application/json
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 401 unauthorized
Content-Type: text/html; charset=utf-8
Www-Authenticate: Bearer error="invalid_token"
Set-Cookie: __cfduid=d269a9cdf7808edaebb6fe96faa3f85791485619413; expires=Sun, 28-Jan-18 16:03:33 GMT; path=/; domain=.drchrono.com; HttpOnly
cf-ray: 3285acd889fe511c-SJC
x-xss-protection: 1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains ; preload
x-frame-options: sameorigin
x-content-options: nosniff
Server: cloudflare-nginx
Date: Sat, 28 Jan 2017 16:03:34 GMT
Vary: User-Agent, Authorization, Cookie

Authorization failed.
---
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
params:  nil
authorizeRequest start
[Debug] OAuth2: Opening authorize URL embedded: https://drchrono.com/o/authorize/?state=5FA364EE&response_type=code&scope=user%3Aread+patients%3Aread+patients%3Awrite&redirect_uri=http%3A%2F%2Flocalhost%2Foauth&client_id=xxxxxxxxxxmyIDxxxxxxxxxx
running public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) 
end public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) 
running public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) 
end public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) 
running public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) 
end public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) 
```

I haven't been successful using the SafariView because my provider requires an "http" or "https" redirect.

I have tried setting breakpoints in OAuth2WebViewController, but I am not certain where the intercept comes in as nothing happens after I hit "Authorize". Is there any way to log the intercept? Do I need to modify anything within OAuth2WebViewController to intercept? 

As am I getting a "not authorized response" to my initial request without a token, I am not clear on why I shouldn't be getting a response during the authorization process.

Many thanks!!! Jeff

**Comment by p2** [comment]
The very first 401 is okay, the loader just tries and intercepts a 401, launching the authorization dance afterwards.

Have you set a breakpoint in [`OAuth2WebViewController.swift#L230`](https://github.com/p2/OAuth2/blob/master/Sources/macOS/OAuth2WebViewController.swift#L230)? Is it being hit?

**Comment by jcedman** [comment]
I have put breakpoints  all over  OAuth2WebViewController:

 Here is the sequence AFTER the 401:

**First:**

` public func loadURL(_ url: URL) { ` is hit and loads the following url:

```
https://drchrono.com/o/authorize/?state=F90DDD27&response_type=code&scope=user%3Aread+patients%3Aread+patients%3Awrite&redirect_uri=http%3A%2F%2Flocalhost%2Foauth&client_id=SPEd6RWQEdsob1Ubxfqzvlg6CXd3GBAo8YxVDDHd
```
**Then:**

`public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) ` is hit (and doesn't appear to do anything).

**This window appears:**

<img width="271" alt="screen shot 2017-01-29 at 9 30 08 am" src="https://cloud.githubusercontent.com/assets/16310316/22406315/097623c4-e606-11e6-8053-b5e39296436d.png">

**Then**

 `public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) ` is hit again and the "Authorize App" page comes up:

<img width="371" alt="screen shot 2017-01-29 at 9 30 38 am" src="https://cloud.githubusercontent.com/assets/16310316/22406323/33ccae7c-e606-11e6-92e3-f1de2ad0397f.png">

Hitting "Authorize" does nothing. Nothing is logged. The mac app stays in the "Authorizing mode". The "Cancel" button from the app (not web page) will cancel. "Cancel" from web page does nothing.
		
I assume by line 230 you mean 
`public func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: (WKNavigationActionPolicy) -> Void)` 
No. It has never been hit.

Thanks again,

Jeff

**Comment by jcedman** [comment]
Okay. But then after hitting that "Authorize" button, I get:

<img width="591" alt="screen shot 2017-01-29 at 10 09 57 am" src="https://cloud.githubusercontent.com/assets/16310316/22406863/01f6d170-e610-11e6-95e0-5f3b0aba390d.png">

```
public func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: (WKNavigationActionPolicy) -> Void)
```
is still not being hit.

Remember I have to use either http or https. I have tried several variations of http://localhost/ . Always get the same "localhost not found".

Is there somewhere other than the data loader config settings that needs to be set to intercept "http://localhost/x? plist?

One slow step at a time...   Thanks.

Jeff

**Comment by p2** [comment]
Okay, that's good, at least it seems to load the correct callback URL.

The only place you need to configure the callback is in the settings dict, and it needs to be exactly the same as configured in the drchrono console. I have tested the macOS sample app with Google and it's working with Google's non-custom-scheme callback, so it should also work with `http://localhost` callbacks.

Okay, I have just signed up for a drchrono account, and just changing the Google example is working for me (okay, almost – I'm getting the error "not authorized to request an access token using this method"). It does hit the `webView(decidePolicyFor:...)` delegate method, I'm not sure why it's not doing that for you. The callback it's calling for me right after I click “Authorize” is:

    http://localhost/oauth2?state=229E76BB&code=71N...

Does this get you a step further?

**Comment by p2** [comment]
I do get an access token, but when I use it drchrono rejects it. Not sure why, here's the trace:

```
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Opening authorize URL embedded: https://drchrono.com/o/authorize/?state=3A0CC7A2&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%2Foauth2&client_id=0PwbwMGA...
[Debug] OAuth2: Handling redirect URL http://localhost/oauth2?state=3A0CC7A2&code=MsadCvf8....
[Trace] OAuth2: Checking state, got “3A0CC7A2”, expecting “3A0CC7A2”
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Exchanging code MsadCvf8... for access token at https://drchrono.com/o/token/
[Trace] OAuth2: REQUEST
HTTP/1.1 POST https://drchrono.com/o/token/
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Authorization: Basic MFB3YndN...==

grant_type=authorization_code&code=MsadCvf8...&redirect_uri=http%3A%2F%2Flocalhost%2Foauth2
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 200 no error
Date: Mon, 30 Jan 2017 08:46:10 GMT
...
Server: cloudflare-nginx
Content-Encoding: gzip
Cache-Control: no-store

{"access_token": "jgtiC25w...", "token_type": "Bearer", "expires_in": 172800, "refresh_token": "ccq90WWh...", "scope": "user:write messages:read labs:write patients:write billing:write user:read labs:read patients:read calendar:write labs patients:summary:write patients patients:summary:read user clinical:read billing:read messages:write clinical:write calendar patients:summary calendar:read"}
---
[Debug] OAuth2: Did exchange code for access [true] and refresh [true] tokens
[Debug] OAuth2: Storing tokens to keychain
[Trace] OAuth2: REQUEST
HTTP/1.1 GET https://drchrono.com/api/users/current
Authorization: Bearer jgtiC25w...
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 401 unauthorized
Content-Type: text/html; charset=utf-8
Www-Authenticate: Bearer error="invalid_token"
cf-ray: 3293a6e48fa9157d-FRA
x-xss-protection: 1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains ; preload
x-frame-options: sameorigin
x-content-options: nosniff
Server: cloudflare-nginx
Date: Mon, 30 Jan 2017 08:46:10 GMT
Vary: User-Agent, Authorization, Cookie

Authorization failed.
```

**Comment by p2** [comment]
p.s.
Using `https://drchrono.com/api/users` (omitting `current`) does work:

```
[Trace] OAuth2: REQUEST
HTTP/1.1 GET https://drchrono.com/api/users
Authorization: Bearer h7Qm...
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 200 no error
Date: Mon, 30 Jan 2017 09:00:02 GMT
Strict-Transport-Security: max-age=31536000 ; includeSubDomains ; preload
Vary: User-Agent, Authorization, Cookie
Content-Type: application/json
allow: GET, HEAD, OPTIONS
...
Server: cloudflare-nginx
Content-Encoding: gzip
Cache-Control: no-cache

{"previous":null,"results":[{"username":"...","is_staff":false,"is_doctor":true,"doctor":123,"id":123,"practice_group":456}],"next":null}
```

**Comment by jcedman** [comment]
Pascal. Thanks for all the effort. I tried again and couldn't get any further. I removed the downloaded OAuth2 macApp, cleaned up references, and downloaded again. I modified the google loader as follows:

```
class GoogleLoader: OAuth2DataLoader, DataLoader {
	
	let baseURL = URL(string: "https://drchrono.com/api/")!
	
	public init() {
		let oauth = OAuth2CodeGrant(settings: [
			"client_id": "SPEd6RWQEdsob1Ubxfqzvlg6CXd3GBAo8YxVDDHd",
			"client_secret": "eFOvY1FVpKlVtGTwyDHSqJGRD2v9Pet3hub5xskcw8m1vvJ2xYH3oKAsXLkhkIcZIhDlFLPux4OteJqk4X634OpjFpvVhjxDpvodMsWewIWNtroP2HxDbmXjUcTKsF60",
			"authorize_uri": "https://drchrono.com/o/authorize/",
			"token_uri": "https://drchrono.com/o/token/",
			"scope": "user:read patients:read patients:write",
			"redirect_uris": ["http://localhost/oauth2"],
		])
		oauth.authConfig.authorizeEmbedded = true
		oauth.logger = OAuth2DebugLogger(.debug)
        oauth.logger = OAuth2DebugLogger(.trace)
		super.init(oauth2: oauth)
		alsoIntercept403 = true
	}
	
	/** Perform a request against the API and return decoded JSON or an Error. */
	func request(path: String, callback: @escaping ((OAuth2JSON?, Error?) -> Void)) {
		let url = baseURL.appendingPathComponent(path)
		let req = oauth2.request(forURL: url)
		
		perform(request: req) { response in
			do {
				let dict = try response.responseJSON()
				var profile = [String: String]()
				if let name = dict["displayName"] as? String {
					profile["name"] = name
				}
				if let avatar = (dict["image"] as? OAuth2JSON)?["url"] as? String {
					profile["avatar_url"] = avatar
				}
				if let error = (dict["error"] as? OAuth2JSON)?["message"] as? String {
					DispatchQueue.main.async {
						callback(nil, OAuth2Error.generic(error))
					}
				}
				else {
					DispatchQueue.main.async {
						callback(profile, nil)
					}
				}
			}
			catch let error {
				DispatchQueue.main.async {
					callback(nil, error)
				}
			}
		}
	}
	
	func requestUserdata(callback: @escaping ((_ dict: OAuth2JSON?, _ error: Error?) -> Void)) {
		request(path: "users", callback: callback)
	}
}

```

then ran, logged in, and hit "Authorize" ---> nothing . Just sits, waiting for authorization.

Log:

```
[Debug] OAuth2: Initialization finished
2017-01-31 07:22:11.135533 OAuth2App[895:13371] Cannot sign request, access token is empty
[Trace] OAuth2: REQUEST
HTTP/1.1 GET https://drchrono.com/api/users
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 401 unauthorized
Content-Type: text/html; charset=utf-8
Www-Authenticate: Bearer error="invalid_token"
Set-Cookie: __cfduid=d57a37452ffb4833fd4cb9650bdd64c871485876131; expires=Wed, 31-Jan-18 15:22:11 GMT; path=/; domain=.drchrono.com; HttpOnly
cf-ray: 329e285cd9851ebf-SJC
x-xss-protection: 1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains ; preload
x-frame-options: sameorigin
x-content-options: nosniff
Server: cloudflare-nginx
Date: Tue, 31 Jan 2017 15:22:11 GMT
Vary: User-Agent, Authorization, Cookie

Authorization failed.
---
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Opening authorize URL embedded: https://drchrono.com/o/authorize/?state=4DCE9077&response_type=code&scope=user%3Aread+patients%3Aread+patients%3Awrite&redirect_uri=http%3A%2F%2Flocalhost%2Foauth2&client_id=SPEd6RWQEdsob1Ubxfqzvlg6CXd3GBAo8YxVDDHd
```

I am at a complete loss at this point. There has to be some setting somewhere if my modifications to the googleLoader are correct. I have tried downloading the app with git and with copying, restarted computer, cleaned projects, etc.  Still nothing.

Oh, and it never hits the "decidePolicy" breakpoint.

Appreciate your help. 

Jeff

**Comment by p2** [comment]
Very strange, I have virtually the same setup and it works for me. I'm on latest `master` for _OAuth2App_ and on `develop` for _OAuth2_. Can you retry from these two branches?

**Comment by p2** [comment]
I just used your client-id and -secret, and it also worked – apart from the fact that the token I'm getting is then refused with a 403 and _Application is not live_. Not sure where that comes from. Changing back to my client-id and -secret and it works again.

**Comment by jcedman** [comment]
Thanks Pascal. I give up. I don't know how to download the develop branch and reconnect it to my OAuthApp. I have spent way too many days on this. Keep up the good and I appreciate your help.

Cheers,

Jeff

**Comment by p2** [comment]
Okay sure. All you'd have to do is use git to get the sample app, then:

```
cd OAuth
git checkout develop
git pull
```

And build and run.

**Comment by p2** [comment]
Okay, I see now – same issue if I use the `master` branch of the library! I will wrap up the develop branch and publish an update to the master branch, bumping the version.

**Comment by jcedman** [comment]
That makes sense. I have configured a bunch of other OAuths on iOS and thought I understood most of it. Please let me know when update the master.

**Comment by p2** [comment]
The issue is that the Swift methods of the web view delegate have changed slightly, I'm guessing that's why they're not called.

**Comment by p2** [comment]
Okay, version 3.0.2 is up and should work correctly, whew!

Thanks for your persistence. 👍🏼

**Comment by jcedman** [comment]
Yes!!!

```
[Trace] OAuth2: RESPONSE
HTTP/1.1 200 no error
Date: Wed, 01 Feb 2017 00:03:36 GMT
cf-ray: 32a124245ff9142b-LAX
Strict-Transport-Security: max-age=31536000 ; includeSubDomains ; preload
x-content-options: nosniff
Vary: User-Agent, Authorization, Cookie
Content-Type: application/json
allow: GET, HEAD, OPTIONS
Set-Cookie: __cfduid=d4c57f19d4b29d8718993d5f788e594d91485907415; expires=Thu, 01-Feb-18 00:03:35 GMT; path=/; domain=.drchrono.com; HttpOnly
x-xss-protection: 1
x-frame-options: sameorigin
Server: cloudflare-nginx
Content-Encoding: gzip
Cache-Control: no-cache

{"previous":null,"results":[{"username":   etc, etc, ...
```

Pascal,

Many thanks, vielen Dank, merci, grazi, gracias, etc. I am in your debt. Now I can do some coding rather than you.

Jeff

**Comment by p2** [comment]
Nothing to thank for, have fun with your project!

**Comment by jcedman** [comment]
I wouldn't ask you this, but you actually have seen it already...

Using the loader as current set up, i can get to most of the endpoints in drChrono except for `https://drchrono.com/api/users/current` . You had the same problem when you tried. I do need to get to this endpoint. 

While this request works fine:

```
[Trace] OAuth2: REQUEST
HTTP/1.1 GET https://drchrono.com/api/users
Authorization: Bearer ETdvWzAu6xliplIgwOqv7NAwSfaI8u
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 200 no error
```

This one does not:

```
[Trace] OAuth2: REQUEST
HTTP/1.1 GET https://drchrono.com/api/users/current
Authorization: Bearer ETdvWzAu6xliplIgwOqv7NAwSfaI8u
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 401 unauthorized
Content-Type: text/html; charset=utf-8
Www-Authenticate: Bearer error="invalid_token"
```

I asked drChrono about this in the past and got the following:

```

The api/users/current endpoint returns a redirect which your app needs to handle to redirect the user to the given url. Here is an example response headers from api/users/current

< HTTP/1.1 302 Found
< Server: nginx
< Date: Mon, 03 Oct 2016 18:02:31 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: close
< X-XSS-Protection: 1
< X-Content-Options: nosniff
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains ; preload
< Vary: User-Agent, Authorization, Cookie
< Location: /api/users/1
< Allow: GET, HEAD, OPTIONS
< Cache-Control: no-cache
< X-Frame-Options: sameorigin
< X-static: miss

I am not sure why you are getting an Authorization failed, are you supplying the correct authorization headers?
```

Seems to me there are two errors here (but probably the same)

1. Somehow the access token isn't working

2. loader is not handling the `https://drchrono.com/api/users/current` redirect properly

I did handle this previously in Alamofire and iOS by capturing the redirect url and "re-requesting" using that url (the url looks like ``https://drchrono.com/api/users/28201`` and it works fine with the dataLoader:
```
HTTP/1.1 GET https://drchrono.com/api/users/28201
Authorization: Bearer ETdvWzAu6xliplIgwOqv7NAwSfaI8u
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 200 no error
``` 

 I prefer your data loader  to Alamofire (seems a lot simpler, but all I need). That said, before I undertake incorporating all the Alamofire code that i will need, is there a way to capture the redirect?
In Alamofire (iOS), I would use `currentUserUrl = result.response?.url` to process the response.
I don't see a `response?.url` in the ` perform(request: req) { response` function and trying to capture with `responseData()` doesn't seem to work because of the access token being "invalid". 

Any thoughts?

**Comment by p2** [comment]
Thanks for reporting. I tried with the token that you use in your example, and from command line requesting `/users` works and `/users/current` does return a 302 temp redirect. I'll see if the loader can follow that correctly – not sure why it's reporting a 401.

**Comment by jcedman** [comment]
Thanks. BTW. I just killed that token and changed the redirect_uri.

**Comment by p2** [comment]
I'm not sure what's going on, but I don't seem to receive a redirect, but a 401 immediately. When using the same URL with the same token, I do get a 302 redirect. I also tried to mimic the request from the command line by adding the exact same headers, but I'm getting a 401 and the redirect delegate method is not being hit.

Not sure what's going on, have to dig deeper.

**Comment by p2** [comment]
Alright, I figured it out – the redirect was automatically handled, but the request was **not** automatically signed again, hence the 401. Just implemented a delegate that can handle that, all you need to do is provide an additional `host` parameter when initializing the data loader (line 27 in Google Data loader, where it calls `super`).

This is now on `master` and it works for me with drchrono, let me know how it works for you!

**Comment by jcedman** [comment]
Perfect. Works like a charm!
