### ISSUE TITLE
Navigation bar style 

### ISSUE THREAD

**Issue by terflogag** [p2/OAuth2#177]
Hello,

Is there a way to change the color of the navigation bar of the 0Auth controller ? 
In my app I have a lot of social networks and I would like to set the main social network color for the navigation bar for each social network. 

I think the better way to deal with it is to set something in `oauth2.authConfig.ui`, like : 
`oauth2.authConfig.ui.controllerColor = UIColor.black`

What do you think about it ? 
If you are ok with this implementation, I can make a pull request with this feature.

**Comment by p2** [comment]
Great idea – I've gone ahead and added two properties to `authConfig` but also added a hook to `OAuth2AuthorizerUI` to do even more customizations. Hope this works!

**Comment by terflogag** [comment]
Nice ! Thank you !
