### ISSUE TITLE
Using a custom viewController in a PasswordGrant flow

### ISSUE THREAD

**Issue by amaurydavid** [p2/OAuth2#178]
I'm currently using this lib in an iOS app with a server that doesn't provide any web page to authenticate, the only way is to use a custom UIViewController and to link it to the API.
Unfortunately, I don't see any feature here to use a custom UIViewController, there is only the possibility to show a web page by either presenting an embedded webview or opening safari.

As a workaround, I perform authorization requests and update the token in the keychain manually. In the end, the lib just refreshes the auth token.

Is there any technical limitation that would prevent a such feature to exist? I'm in fact kind of surprised it doesn't already exist.

**Comment by p2** [comment]
The password grant flow is a bit special in that it doesn't follow OAuth2's pragma of making sure that the client (app) does never have access to the user's password. But yes, it's necessary to be able to provide hooks for your own login screen if you use that flow, I'll have to check how to best implement that.

**Comment by amaurydavid** [comment]
In that case i'm actually working on a solution for that, i'll let you in touch ;)

**Comment by p2** [comment]
Thanks David, this is now on `master` and will be in the next release (> 3.0.2).
