### ISSUE TITLE
Cannot set client ID with basic integration

### ISSUE THREAD

**Issue by pyrabbit** [p2/OAuth2#182]
Thanks for the great open source project. I am having issues with getting my client_id set. What am I missing?

```
let oauth2 = OAuth2CodeGrant(settings: [
    "client_id": "someClientId",
     "client_secret": "someClientSecret",
     "authorize_uri": "https://myWebsite.com/authorize",
     "token_uri": "https://myWebsite.com/token",   // code grant only
     "redirect_uris": ["myapp://appDidAuthorize"] // register your own "myapp" scheme in Info.plist
] as OAuth2JSON)

oauth2.authorize() { authParameters, error in
       if let params = authParameters {
            print("Authorized! Access token is in `oauth2.accessToken`")
            print("Authorized! Additional parameters: \(params)")
        } else {
            print("Authorization was cancelled or went wrong: \(error)")   // error will not be nil
        }
}
```

This returns `Authorization was cancelled or went wrong: Optional(Client id not set)`

**Comment by p2** [comment]
What service are you authorizing against? Maybe you need to put the client_id in the body with the `secret_in_body` setting? See [advanced settings](https://github.com/p2/OAuth2#advanced-settings) and [the wiki](https://github.com/p2/OAuth2/wiki).

**Comment by pyrabbit** [comment]
@p2 thanks for the quick reply. I think I am using `OAuth2CodeGrant` when I should be using `OAuth2ImplicitGrant`

I am trying to use this with my colleagues web application that expects the client_id to be a URL query field item. For example `https://localhost:8080/authorize?response_type=token&client_id=MYID123456790&state=random_state_string&redirect_uri=myapp://strDidAuthorizeApp"`  

Since he does not require me to get a code, I switched to the `OAuth2ImplicitGrant` class but still experiencing at the same error. When I put a break point in Xcode it appears that none of the settings within the instantiation of OAuth2CodeGrant are actually getting set within the OAuth2.OAuth2ClientConfig class, everything in there seems to be nil

**Comment by p2** [comment]
Use a _trace_ logger to see exactly what is going on:

    oauth2.logger = OAuth2DebugLogger(.trace)

No worries about the names of the frameworks. The framework will be available as `OAuth2` but internally the targets are named OAuth2iOS and co. Xcode has changed how these two names are shown repeatedly in the past – at least one can now see which one is chosen, previously you'd just see "OAuth2" three times.

**Comment by pyrabbit** [comment]
Thanks @p2 I think we can close this now :)

**Comment by p2** [comment]
So does it work for you now? Can you share what the issue was?
