### ISSUE TITLE
Can we use CodeGrant to make an OpenId connexion ?

### ISSUE THREAD

**Issue by emericspiroux** [p2/OAuth2#183]
Hi p2,

I need to use a library to make an OpenId connexion. Normally the protocol use oauth2 with code grant. The question is, can i do an OpenId connexion with p2/oauth2 ? 

Thanks a lot !

**Comment by p2** [comment]
Do you mean you want to use OpenID Connect on top of OAuth2 or do you want to use OpenID by itself?

**Comment by emericspiroux** [comment]
I want to use OpenID Connect on top of OAuth2. :+1:

**Comment by p2** [comment]
That's possible, just set `scope` accordingly, then inspect the return parameters that you get in the `authorize()` callback for the JWT. You will have to decode that by yourself, however. I've had good success with the “JSONWebToken.swift” framework.

**Comment by emericspiroux** [comment]
Nice ! Perfect ;) Thank you very much for this precision !
Have a nice day !
