### ISSUE TITLE
OAuth2DataLoader doesn't handle refresh token

### ISSUE THREAD

**Issue by RemiGuyon** [p2/OAuth2#184]
I am using OAuth2DataLoader to handle the authorization logic.
But then I saw that if I get a 401, tokens are forgotten just before calling authorize. This makes the whole refresh token process useless with OAuth2DataLoader.
I don't get why the tokens have to be forgotten here. Am I missing something?

**Comment by p2** [comment]
You're right of course! I have just pushed a small change, have yet to test if that's a good solution. Can you give `master` branch a shot?

**Comment by RemiGuyon** [comment]
Thanks for the update! I just tried the master branch but KeychainGenericPasswordType is not found anymore.

**Comment by p2** [comment]
Do a `git submodule update` if you haven't already.
