### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by dirk777** [p2/OAuth2#185]
After granting successfully access token the request produces the error "Error parsing JSON"
The response.data holds a valid json expression which is in my case
`[{"account":"12345678.3333.444","alias":"alias-7274"}]`

**Comment by p2** [comment]
Is this a request for data that produces the error? In which class is it occurring? Against which service?

Can you post the output of a trace logger, which you can install like so:

    oauth2.logger = OAuth2DebugLogger(.trace)

**Comment by dirk777** [comment]
I adapt the OAuth2-App Example and use the <Provider>DataLoader class and implement a Loader for Strato's HiDrive. In the line response.responseJSON with OAuth2JSON as result type the error will be thrown.  
If I go with JSONSerialization.jsonObject(with: response.data!, options: []) it works fine

This is the trace of the DebugLogger

```
[Debug] OAuth2: Initialization finished
[Debug] OAuth2: Looking for items in keychain
[Debug] OAuth2: Found access token but it seems to have expired
[Debug] OAuth2: Found refresh token
[Debug] OAuth2: Initialization finished
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
[Debug] OAuth2: Using refresh token to receive access token from https://www.hidrive.strato.com/oauth2/token
[Trace] OAuth2: REQUEST
HTTP/1.1 POST https://www.hidrive.strato.com/oauth2/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Authorization: Basic <access_token>

grant_type=refresh_token&refresh_token=<refresh_token>
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 200 no error
Content-Type: application/json
Content-Length: 173
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
X-STG-WWW-Version: 198-10d66e6
X-STG-FE: 10.4.1.27:24081
Server: Mojolicious (Perl)
Date: Tue, 28 Feb 2017 10:20:15 GMT
Cache-Control: max-age=0, no-store
[Debug] OAuth2: Did use refresh token for access token [true]
[Debug] OAuth2: Storing tokens to keychain
```

**Comment by p2** [comment]
Ah I see:

> In the line response.responseJSON with OAuth2JSON as result type the error will be thrown

Your response has an array as a top level item, not an object, so this will throw. Instead of using `response.responseJSON()` try this:

    let data = try handler.responseData()
    let json = try JSONSerialization.jsonObject(with: data, options: [])

**Comment by dirk777** [comment]
Beside using handler.data this approach using handler.responseData works also.

**Comment by p2** [comment]
Alright great! I'll close this issue, maybe I will make this clear in the docs at one point.
