### ISSUE TITLE
Class PLBuildVersion is implemented in both........One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by zhao15** [p2/OAuth2#186]
I have installed OAuth2 to my targets as a model, and it built successfully but Xcode showed massage as below, what's wrong with it, any advice would be appreciated, thanks.
objc[7609]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x1136ce910) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x1134f8210). One of the two will be used. Which one is undefined.

**Comment by p2** [comment]
This is a known problem with Xcode 8 and you can safely ignore it. See [here for discussion](http://stackoverflow.com/questions/39520499/class-plbuildversion-is-implemented-in-both-frameworks).

**Comment by zhao15** [comment]
Thank you very much.
