### ISSUE TITLE
Is there a way to use HTTP in development

### ISSUE THREAD

**Issue by nick-nz** [p2/OAuth2#187]
I don't have an HTTPS deployment of my server (identity server and api) available during development (for various reasons). This means I get the following error when trying to get a token:

> Optional(You MUST use HTTPS/SSL/TLS)

Is there a setting I can change to temporarily use HTTP to request a token during development?

**Comment by p2** [comment]
This check is hardcoded and you cannot override by subclassing nor via a setting I'm afraid. The intention is to make it impossible to use non-TLS connections, but I see how that complicates development in some cases.

My advice is to either get a free certificate for your dev server via [letsencrypt](https://letsencrypt.org) or to checkout OAuth2 and [override the https check](https://github.com/p2/OAuth2/blob/master/Sources/Base/OAuth2AuthRequest.swift#L148) while testing.

**Comment by nick-nz** [comment]
OK cool, thanks for the reply.

**Comment by moger777** [comment]
Would you accept a PR where this was optional for development? This can be very inconvenient for teams where the iOS developers also do some of the back end development on a localhost server.

**Comment by p2** [comment]
The reason it's not in as an option is because I know people will use it to ship insecure code. :)

Use the solutions suggested above while testing.

**Comment by quiin** [comment]
Another solution is to use [Ngrok](https://ngrok.com/) for development as it provides _"Secure tunnels to localhost"_

**Comment by axelguilmin** [comment]
⚠️ Never do that in production, it's absolutely unsecure.

It made a fork to introduce a flag : https://github.com/p2/OAuth2/commit/6783d291295ef25674d7be6d0d9670f4df472778
Using like so in Cocoapods : 
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'p2.OAuth2' && config.name == 'Dev'
        config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = "$(inherited) OAUTH2_ALLOW_UNSECURE"
      end
    end
  end
end
```
