### ISSUE TITLE
Google and OAuth..

### ISSUE THREAD

**Issue by terflogag** [p2/OAuth2#188]
Hello,

Referring to this : https://developers.google.com/identity/sign-in/auth-migration
If I understand this link, now we can't use this library to make login for Google/Youtube/Blogger ? :'(

**Comment by terflogag** [comment]
Ho, finaly it just need to pass with : 
oauth2.authConfig.ui.useSafariView = true (instead of web view)...

**Comment by p2** [comment]
Yes, for reference: https://github.com/p2/OAuth2/wiki/Google
