### ISSUE TITLE
Fitbit and OAuth

### ISSUE THREAD

**Issue by Moo1234** [p2/OAuth2#189]
Hi p2, 

 I followed your instructions, but sadly I don't get any callbacks from the authorize-methode. Do you see my mistake or do I have to add something? 
Here is my Code:

`let oauth2 = OAuth2CodeGrant(settings: [
    "client_id": "******",  //ID from Fitbit
    "client_secret": "***************************", //Secret from Fitbit
    "authorize_uri": "https://www.fitbit.com/oauth2/authorize",
    "token_uri": "https://api.fitbit.com/oauth2/token",  
    "redirect_uris": ["http://google.com/"],   
    "scope": "profile settings activity nutrition heartrate location nutrition profile settings sleep social weight",
    "secret_in_body": true,
    "keychain": false,        
    ] as OAuth2JSON)

... 
func startAuthorization() {
    oauth2.logger = OAuth2DebugLogger(.trace)

    oauth2.authorize() { authParameters, error in
        if let params = authParameters {
            print("Authorized! Access token is in `oauth2.accessToken`")
            print("Authorized! Additional parameters: \(params)")
        }
        else {
            print("Authorization was cancelled or went wrong: \(error)")   // error will not be nil  
        }
    }
}`
Here is my Log-Trace:
`[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Opening authorize URL in system browser: (URL)`

Best regards!

**Comment by p2** [comment]
You're redirecting to google.com, that can't work. See [1. Instantiate OAuth2 with a Settings Dictionary](https://github.com/p2/OAuth2#1-instantiate-oauth2-with-a-settings-dictionary), especially the sentence about redirect URLs.
