### ISSUE TITLE
Can't get past Authorize iOS version

### ISSUE THREAD

**Issue by trpmap93** [p2/OAuth2#191]
Hi,

I am having almost the exact same issues as jcedman was having with the Mac version.  I can easily pull up my authorization screen, but clicking on authorize does nothing.  Tapping Cancel in the Navigation works fine as expected.  

<img width="618" alt="screen shot 2017-04-16 at 11 14 14 pm" src="https://cloud.githubusercontent.com/assets/13937376/25080640/8440d622-22fa-11e7-88d1-7bf3450b233f.png">

When I change  oauth2.authConfig.ui.useSafariView = true,  I get this screen:

<img width="624" alt="screen shot 2017-04-16 at 12 00 07 pm" src="https://cloud.githubusercontent.com/assets/13937376/25080681/bc6e8ec2-22fa-11e7-91af-88f17311e987.png">

My code is posted below.  Thanks for taking a look!

class ViewController: UIViewController {
	
	fileprivate var alamofireManager: SessionManager?
	
	var loader: OAuth2DataLoader?
	
    let oauth2 = OAuth2CodeGrant(settings: [
        "client_id": "xxxxxxxxxxxxxxxxx",
        "client_secret": "xxxxxxxxxxxxxxx",
        "authorize_uri": "https://platform.carecloud.com/oauth2/authorize?client_id=xxxxxxxxxxxxxxxxx&response_type=code&redirect_uri=https://xxxxxxxx.com/auth/carecloud",
        "token_uri": "https://api.carecloud.com/oauth2/access_token",   // code grant only
        "redirect_uris": ["https://xxxxxxxx.com/auth/carecloud"],   // register your own "myapp" scheme in Info.plist
        "scope": "",
        "secret_in_body": false,
        "verbose": true,
        "keychain": true,         // if you want keychain integration
        ] as OAuth2JSON)
	
	@IBOutlet var imageView: UIImageView?
	@IBOutlet var signInEmbeddedButton: UIButton?
	@IBOutlet var signInSafariButton: UIButton?
	@IBOutlet var signInAutoButton: UIButton?
	@IBOutlet var forgetButton: UIButton?
	
	
	@IBAction func signInEmbedded(_ sender: UIButton?) {
        
        
		if oauth2.isAuthorizing {
			oauth2.abortAuthorization()
			return
		}
		
		sender?.setTitle("Authorizing...", for: UIControlState.normal)
		
		oauth2.authConfig.authorizeEmbedded = true
		oauth2.authConfig.authorizeContext = self
        oauth2.authConfig.ui.useSafariView = false
        
        
      /*  oauth2.authorize() { authParameters, error in
            if let params = authParameters {
                print("Authorized! Access token is in `oauth2.accessToken`")
                print("Authorized! Additional parameters: \(params)")
            }
            else {
                print("Authorization was cancelled or went wrong: \(String(describing: error))")   // error will not be nil
            }
        } */
        
		 let loader = OAuth2DataLoader(oauth2: oauth2)
		self.loader = loader
		
		loader.perform(request: userDataRequest) { response in
			do {
				let json = try response.responseJSON()
				self.didGetUserdata(dict: json, loader: loader)
                print (json)
			}
			catch let error {
				self.didCancelOrFail(error)
			}
		}
	}

**Comment by trpmap93** [comment]
Sorry above meant tapping on continue

**Comment by p2** [comment]
You need to make sure to [intercept the redirect callback](https://github.com/p2/OAuth2#3-make-sure-you-intercept-the-callback), either by using [universal links](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html) or your own custom app scheme (you're using https as far as I can tell).

**Comment by riverbaymark** [comment]
Hey thanks for your reply.  Just wanted to let you know the issue was I missed a email from them where they reset everyones passwords when they revamped their system.  I fixed that part and it works like a charm!
