### ISSUE TITLE
Some websites (like reddit) require http basic authentication to allow tokenRequest

### ISSUE THREAD

**Issue by zackprice** [p2/OAuth2#2]
The function tokenRequest in OAuth2CodeGrant does not allow specification of Headers for http basic authentication.

As a result, when trying to setup OAuth2 with reddit, it fails.

As a hack, I added this to allow it to work. But obviously it needs to be a little smarter about passing around the user/pass rather than doing a hardcoding.

        let username = “username“ //Client ID in Reddit
        let password = “password” //Client Secret in Reddit
        let loginString = NSString(format: "%@:%@", username, password)
        let loginData: NSData = loginString.dataUsingEncoding(NSUTF8StringEncoding)!
        var base64LoginString = "Basic "
        base64LoginString += loginData.base64EncodedStringWithOptions(NSDataBase64EncodingOptions.Encoding64CharacterLineLength)
        post.setValue(base64LoginString,forHTTPHeaderField: "Authorization")

**Comment by p2** [comment]
This finally works. I've also added a bit of sample code for Reddit to the sample app: https://github.com/p2/OAuth2App/blob/master/OAuth2App/RedditLoader.swift

**Comment by zackprice** [comment]
Super Awesome!

*Zack Price*
Quality Assurance Engineer


price@csdisco.com
(713) 231 9100
csdisco.com
