### ISSUE TITLE
Swift4

### ISSUE THREAD

**Issue by ParanoiaWan** [p2/OAuth2#205]
support swift 4?

**Comment by Izzywizz** [comment]
I would second this please 😊

**Comment by p2** [comment]
I'm afraid I'm unable to update the library myself, but would be happy to accept PRs!

**Comment by vilanovi** [comment]
is there a released version compatible with Swift 4 already of this in CocoaPods?

**Comment by p2** [comment]
Version 4 is now in Swift 4 (see #228).

For CocoaPods see https://github.com/p2/OAuth2/issues/230#issuecomment-340287621
