### ISSUE TITLE
How to add multiple scopes for Google OAuth ?

### ISSUE THREAD

**Issue by haithngn** [p2/OAuth2#208]
Hello,

I'm trying to authorize Google OAuth with multiple scopes

> "scope": "https://www.googleapis.com/auth/calendar,https://mail.google.com/"

but safari said

> Error: invalid_scope
> 
> Some requested scopes were invalid. {invalid=[https://www.googleapis.com/auth/calendar,https://mail.googl

![screen shot 2017-06-14 at 5 47 19 pm](https://user-images.githubusercontent.com/22902671/27128671-b96e13de-5129-11e7-8a75-df708a0e73fe.png)

Could you please guide me a correct parameters for scope ?

**Comment by haithngn** [comment]
I replaced comma by space then it work now.

**Comment by sksmsWKd** [comment]
> I replaced comma by space then it work now.

very nice
