### ISSUE TITLE
bundle format is ambiguous (could be app or framework)

### ISSUE THREAD

**Issue by alikazim** [p2/OAuth2#21]
I have implement this library, 
Well I must appreciate the Docs

I am facing an issue here
While Archiving im getting this

CodeSign /Users/shujaathaider/Library/Developer/Xcode/DerivedData/jamesAppV2-hhfnrydqoghbzpgsvepxtuzarqrc/Build/Intermediates/ArchiveIntermediates/Home\ Automation\ Sys\ Swift/IntermediateBuildFilesPath/UninstalledProducts/OAuth2.framework
    cd "/Users/shujaathaider/Desktop/Workspace_qadir/JamesApp - Development/OAuth2-master"
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: Ghulhimam Haanani (HC4WE7XBSD)"

    /usr/bin/codesign --force --sign C72D0E8EEBE104D1EA0AA0D15558EF38808250F3 /Users/shujaathaider/Library/Developer/Xcode/DerivedData/jamesAppV2-hhfnrydqoghbzpgsvepxtuzarqrc/Build/Intermediates/ArchiveIntermediates/Home\ Automation\ Sys\ Swift/IntermediateBuildFilesPath/UninstalledProducts/OAuth2.framework

/Users/shujaathaider/Library/Developer/Xcode/DerivedData/jamesAppV2-hhfnrydqoghbzpgsvepxtuzarqrc/Build/Intermediates/ArchiveIntermediates/Home Automation Sys Swift/IntermediateBuildFilesPath/UninstalledProducts/OAuth2.framework: bundle format is ambiguous (could be app or framework)
Command /usr/bin/codesign failed with exit code 1

Please Help, I have to make an IPA of my App.

I have posted question on stackoverflow also

http://stackoverflow.com/questions/29946706/bundle-format-is-ambiguous-could-be-app-or-framework-while-making-archive

**Comment by p2** [comment]
Looks like you're trying to link the OS X **and** iOS frameworks into your iOS app. Answer on Stackoverflow.
