### ISSUE TITLE
How to use the built-in web view controller

### ISSUE THREAD

**Issue by alikazim** [p2/OAuth2#22]
as Docs suggested, 
either use the built-in web view controller or manually open the authorize URL in the browser:

I am using built-in web view controller approach.

I am trying like this

        let vc   = UberAuthWebViewController(nibName: "UberAuthWebViewController", bundle: nil)
        let web = appDelegate.oauth.authorizeEmbeddedFrom(vc, params: nil)
        appDelegate.oauth.afterAuthorizeOrFailure = { wasFailure, error in
            
            println("Test afterAuthorizeOrFailure")
            web.dismissViewControllerAnimated(true, completion: nil)
        }

But I getting no crash but this warning and nothing open up.
Warning: Attempt to present UINavigationController: 0x166620a0 on jamesAppV2.UberMapViewController: 0x1716e200 whose view is not in the window hierarchy!

may be I am commiting a mistake while making my WebViewController's Object. 
Please help

**Comment by p2** [comment]
The embedded web view controller is included in the client. When calling `authorizeEmbeddedFrom()` you need to provide a view controller **from which** to present the login screen, for example your root view controller. Then the login screen will be modally presented over that one. So your first line should look something like:

```swift
    let vc = appDelegate.window.rootViewController
    let web = appDelegate.oauth.authorizeEmbeddedFrom(vc, params: nil)
    ...
```

**Comment by alikazim** [comment]
Thanks alot, this worked :)

**Comment by p2** [comment]
Great! 👍
