### ISSUE TITLE
Authorization requests to reddit do not include duration parameter on macOS

### ISSUE THREAD

**Issue by abchiaravalle** [p2/OAuth2#221]
Login requests default to the 1hr Reddit-standard parameter since none is defined in the authorization URL. The issue seems to persist whether using the embedded authorization or using Safari to authorize. Same issue exists in the provided OAuth2App Example application for macOS.

Here is the setup of the oauth object in my RedditLoader class.

		let oauth = OAuth2CodeGrant(settings: [
			"client_id": "CLIENT_ID_HERE",                              
			"client_secret": "",
			"authorize_uri": "https://www.reddit.com/api/v1/authorize",
			"token_uri": "https://www.reddit.com/api/v1/access_token",
			"scope": "identity, edit, flair, history, modconfig, modflair, modlog, modposts, modwiki, mysubreddits, privatemessages, read, report, save, submit, subscribe, vote, wikiedit, wikiread",                                        
			"redirect_uris": ["myappurlscheme://oauth/callback"],           
			"parameters": ["duration=permanent"]
			])

**Comment by p2** [comment]
Forgot about this one, sorry.

You have to specify: `"parameters": ["duration": "permanent"]`
