### ISSUE TITLE
Twitch - No Token Type

### ISSUE THREAD

**Issue by jpcguy89** [p2/OAuth2#224]
Hi,

I've been developing an app for Twitch streamers for some time, and OAuth2 has been of immense help, so before I continue with my issue, thank you so incredibly much for all the work you've put into it.

I'm getting the error "no token type" when I try to authorize. I'm assuming this is because...there is no token type in the response? Is there a way for me to deal with this using OAuth2?

Here's the info I think you'll need. Let me know if you need anything else. Thanks!

```
[Trace] OAuth2: RESPONSE
HTTP/1.1 200 no error
Date: Sat, 19 Aug 2017 13:38:53 GMT
Content-Length: 308
access-control-allow-headers: 
Pragma: no-cache
front-end-https: on
x-mh-cache: rails-varnish-api-aws-04b4dbabdd837ed8a; M
Vary: Accept-Encoding
x-varnish: 1397805966
Content-Type: application/json; charset=utf-8
access-control-allow-methods: 
x-request-id: fd1d94fc5287bfba74f009cd9dda9898
Set-Cookie: unique_id=119e7c2bb5ae36fb; domain=.twitch.tv; path=/; expires=Thu, 19-Aug-2027 13:38:52 GMT
x-ua-compatible: IE=Edge,chrome=1
Status: 200 OK
x-frame-options: SAMEORIGIN
Access-Control-Allow-Origin: *
Server: nginx
timing-allow-origin: https://www.twitch.tv
Cache-Control: no-cache, no-store, must-revalidate

{"access_token":"<censored>","refresh_token":"<censored>","scope":["channel_commercial","channel_editor","channel_feed_edit","channel_feed_read","channel_read","channel_subscriptions","chat_login","user_blocks_edit","user_blocks_read","user_read"]}
```

Thanks for your help!

**Comment by p2** [comment]
Yes, please see [this wiki page](https://github.com/p2/OAuth2/wiki/Instagram,-Bitly,-Pinterest-and-others). I've just added “Twitch” to the list of affected services. 👍🏼
