### ISSUE TITLE
Slow UI View Updates

### ISSUE THREAD

**Issue by alikazim** [p2/OAuth2#23]
I am facing strange issue

I have called the method like this

        func callRequestAPI(url:String){
        
        var configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        var session = NSURLSession(configuration: configuration)
        
        let params:[String: AnyObject] = [
            "product_id" : selectedUberProductId,
            "start_latitude" : start_lat,
            "start_longitude" : start_lng,
            "end_latitude" : end_lat,
            "end_longitude" : end_lng]
        
        let request = appDelegate.oauth.request(forURL: NSURL(string:url)!)
        request.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")
        request.HTTPMethod = "POST"
        var err: NSError?
        request.HTTPBody = NSJSONSerialization.dataWithJSONObject(params, options: NSJSONWritingOptions.allZeros, error: &err)
        
        let task = session.dataTaskWithRequest(request) {
            data, response, error in
            
            if let httpResponse = response as? NSHTTPURLResponse {
                if httpResponse.statusCode != 202 {
                    println("response was not 202: \(response)")
                    
                    return
                }
            }
            if (error != nil) {
                println("error submitting request: \(error)")
                return
            }
            
            // handle the data of the successful response here
            var result = NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions.allZeros, error: nil) as! NSDictionary
            
            
            println(result)
            
            if let request_id: String = result["request_id"] as? String{
            
                println(request_id) // This is getting printed very frequently
                self.uber_request_id.text = "Request ID: \(request_id)" // uber_request_id (Lable View) not Update Frequently it takes Approx 1 minute to update

            }
            
            if let driver: String = result["driver"] as? String{
            
                println(driver)
            }
            
            if let eta: Int = result["eta"] as? Int{
            
                println(eta) //This is getting printed very frequently
                self.uber_request_eta.text = String("ETA: \(eta)") //My Lable not Update Frequently
            }
            
            if let location: String = result["location"] as? String{
            
                println(location)
            }
            
            
            if let status: String = result["status"] as? String{
            
                println(status)// This is getting printed very frequently
                self.uber_request_status.text = "Status: \(status)" // My Lable not Update Frequently
            }
            
            
            if let surge_multiplier: Int = result["surge_multiplier"] as? Int{
            
                println(surge_multiplier)
            }
            
            if let vehicle: String = result["vehicle"] as? String{
            
                println(vehicle)
            }
            
        }
        
        task.resume()
    }

Note: See the commented Lables
I am sure im getting the response very frequetly but my Labels are not getting updated ( it takes Approx 1 minute to update my views) 
Whats Wrong with this

Please help

**Comment by p2** [comment]
You always need to perform your UI updates on the main thread. The callback of `session.dataTaskWithRequest()` is **not** called on the main thread, you need to dispatch your label updates to the main queue. Please refer to StackOverflow for this.
