### ISSUE TITLE
Can't get 4.0 from Pods.

### ISSUE THREAD

**Issue by lukaszspaczynski** [p2/OAuth2#230]
[!] Unable to satisfy the following requirements:
- `p2.OAuth2 (= 4.0.0)` required by `Podfile`

Pls update. 3.0.3 has issue with the decisionHandler.

**Comment by akmarinov** [comment]
It's been 20 days, any update on this?

**Comment by akabab** [comment]
+1

**Comment by akabab** [comment]
with
```
pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git'
```
you will get latest changes.
Yet I still have errors on compile
![screen shot 2017-10-20 at 14 02 03](https://user-images.githubusercontent.com/6205705/31824691-629f3dfa-b59f-11e7-95e7-fa15f32d17f7.png)

**Comment by p2** [comment]
Try `pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :submodules => true`

**Comment by akabab** [comment]
Thanks, I noticed it was from Keychain submodule, though I didn't know of that :submodules option ;)

**Comment by akabab** [comment]
Do you plan on releasing to cocoapods ?

**Comment by p2** [comment]
To use latest `master`, use:

```
pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :submodules => true, :branch => 'master'
```

To pin to a specific version:

```
pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :submodules => true, :tag => '4.0.0'
```

Reference: [using the Podfile](http://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo)

**Comment by djbe** [comment]
Right, but that's not actually releasing it on cocoapods. Up to the previous version, we could just use this library like any other pod, without specifying a git url, submodules and branch/tag.

Could you maybe run `pod trunk push` to actually publish the latest podspec?

**Comment by p2** [comment]
Afraid I'm unable to publish that way for the foreseeable future. Use the above lines or, even better, use **Carthage**.

**Comment by djbe** [comment]
Switching to Carthage isn't an option for many users / existing projects, and using the line above won't allow users to automatically get bugfix versions (while excluding major breaking changes).

Could we somehow help with the publishing to CocoaPods? Do you no longer have access to a Mac maybe? I'd be willing to help if need be. 😄

**Comment by p2** [comment]
Actually, if you use `master` with this pod command, you'll always have all the latest bugfixes, as soon as they are live on Github:

```
pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :submodules => true, :branch => 'master'
```

If somebody wants to be in charge of pushing to Cocoapods (and send PR's to update the Podfile) I'd be happy to hand that over, let me know.

**Comment by djbe** [comment]
Pointing to `master` will pull in all changes, including major breaking changes, so that isn't really a solution.

I'll see if I can find some time tonight to make a PR :+1:

**Comment by p2** [comment]
Changes and PR's are usually done against `develop`, but yes, it's not 100% safe to always use `master`.

**Comment by djbe** [comment]
See #240 for a PR and further discussion.

**Comment by djbe** [comment]
4.0.1 has been published to CocoaPods 🎉

**Comment by p2** [comment]
Thanks man!!
