### ISSUE TITLE
Issue with custom logger

### ISSUE THREAD

**Issue by minhhien177** [p2/OAuth2#236]
the current implementation of logger make these methods cannot be overrided

```
	/** Log a message at the trace level. */
	public func trace(_ module: String? = "OAuth2", filename: String? = #file, line: Int? = #line, function: String? = #function, msg: @autoclosure() -> String) {
		log(.trace, module: module, filename: filename, line: line, function: function, msg: msg)
	}
	
	/** Standard debug logging. */
	public func debug(_ module: String? = "OAuth2", filename: String? = #file, line: Int? = #line, function: String? = #function, msg: @autoclosure() -> String) {
		log(.debug, module: module, filename: filename, line: line, function: function, msg: msg)
	}
	
	/** Log warning messages. */
	public func warn(_ module: String? = "OAuth2", filename: String? = #file, line: Int? = #line, function: String? = #function, msg: @autoclosure() -> String) {
		log(.warn, module: module, filename: filename, line: line, function: function, msg: msg)
	}
```

The root cause is due to default values of protocol extension. Can check more details in here https://marcosantadev.com/getting-hurt-protocol-extensions-default-parameter-values/

**Comment by p2** [comment]
What exactly are you trying to do, and what doesn't work?

**Comment by minhhien177** [comment]
I tried to have a custom logger conforming to `OAuth2Logger`. But the logger never call to my overridden methods, logger always call to the default methods of `extension OAuth2Logger`.

**Comment by p2** [comment]
How did you assign your logger?

**Comment by minhhien177** [comment]
here is initial code:

```

        self.oauth2 = OAuth2PasswordGrant(settings: self.settings)
        self.oauth2.sessionDelegate = self
        self.oauth2.logger = OAuth2ToastLogger()
```

`OAuth2ToastLogger` is the custom Logger

**Comment by p2** [comment]
Are you setting `verbose` anywhere after this? This would reset the logger. Also, did you name the overridden methods exactly the same, including the default parameters?

**Comment by minhhien177** [comment]
No I didn't, I put a breakpoint in verbose, code never called to the breakpoint. Please read the article I shared above, the problem is the methods of `OAuth2Logger` extension have default parameters, that made it cannot be overridden.

**Comment by p2** [comment]
I did read the article, and it suggests you add the default parameters in your overridden methods as well in order to avoid the problem. Have you tried that?

**Comment by minhhien177** [comment]
ah yes but I didn't work, the article's solution maybe wrong as well. Btw, I'm using swift 3.

**Comment by p2** [comment]
The problem is that these default parameters are important since you don't want to have to write `#file` and `#line` on every log line. I think you're right though, it at least makes subclassing complicated. So maybe it's better to not make `OAuth2Logger` a protocol but a base class. Can you try to do that, make the protocol a class, make everything in the extension `open` and make `OAuth2DebugLogger` a subclass of `OAuth2Logger` that doesn't override anything?

**Comment by minhhien177** [comment]
Yea it sounds a solution to me as well, I'll try it out and let you know.
