### ISSUE TITLE
how to use hasUnexpiredAccessToken() to avoid login again and again

### ISSUE THREAD

**Issue by alikazim** [p2/OAuth2#24]
I have done like this

      if(appDelegate.oauth.hasUnexpiredAccessToken()){
            
            println("Un-Expired Access Token")
            
            self.navigationController?.pushViewController(self.PersonalDriverUber_VC, animated: true)
            
        }else{
            
            println("Expired Access Token")
            
            appDelegate.oauth.onAuthorize = { parameters in
                println("Did authorize with parameters: \(parameters)")
                
                self.personalDriverLoader.stopAnimating()
                
                self.navigationController?.pushViewController(self.PersonalDriverUber_VC, animated: true)
                
            }
            appDelegate.oauth.onFailure = { error in        // `error` is nil on cancel
                if nil != error {
                    println("Authorization went wrong: \(error!.localizedDescription)")
                }
            }

            
        }

at first time launch I am getting

Did authorize with parameters: [token_type: Bearer, expires_in: 2592000, access_token: laerXXXXX2NcXXXXXXXJc3mtT2t, refresh_token: DqWXXXXXXMBaKKFdPXXXXkZv, scope: request history, last_authenticated: 1431947251]
note:  expires_in: 2592000 in the reponse

I want to know how to use the method hasUnexpiredAccessToken() to avoid login screen again and again. or there is any way to refresh the token 

See my above code every time my ELSE block executes

**Comment by p2** [comment]
If `hasUnexpiredAccessToken` is true, the client has an access token and you can use a signed request immediately. This is **not** yet persisted through app restarts, see the _develop_ branch for that.

**Comment by alikazim** [comment]
I have donwloaded develop branch. imported in in my project
Getting this now

Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

Should I do something pod installation?

**Comment by p2** [comment]
It seems you did not checkout the submodules, you now need to issue the command `git submodule update --init --recursive` from inside the OAuth2 directory.

**Comment by alikazim** [comment]
What I did is Downloaded the SwiftKeyChain from github separately  and included in my project and its build successfully working fine now. 
Thanks for your support

Now if I uninstalled the app and reinstall the app still there is no need to login!
Can we make clear the tokens and credentials when app is uninstalled from keychains. 
is it necessary to explicitly call the forgetTokens() method to deleted the tokens from the keychains?

**Comment by p2** [comment]
You should definitely use `git`, not download the source files yourself, something might break. Yes, you need to explicitly clear the tokens, see here: https://github.com/p2/OAuth2/tree/develop#keychain

**Comment by alikazim** [comment]
I am doing like this now

       // Native webview Controller Authenticaion
        let vc   = appDelegate.window!.rootViewController
        var web:OAuth2WebViewController!
        
        if(appDelegate.oauth.hasUnexpiredAccessToken()){
            
            println("Un-Expired Access Token")
            self.navigationController?.pushViewController(self.PersonalDriverUber_VC, animated: true)
            
        }else{
            println("Expired Access Token")
            web = appDelegate.oauth.authorizeEmbeddedFrom(vc!, params: nil)
        }
        
        // OAuth2 URL Handler
        appDelegate.oauth.afterAuthorizeOrFailure = { wasFailure, error in
            
            if(!wasFailure){
                web.dismissViewControllerAnimated(true, completion: nil)
                self.personalDriverLoader.stopAnimating()
                
                self.navigationController?.pushViewController(self.PersonalDriverUber_VC, animated: true)
            }else{
                println("Failed Or Canceled")
                 self.personalDriverLoader.stopAnimating()
            }
           
        }

Yesterday 
The app was saving the tokens to the keychains and was not asking to relogin,

Today
The app started but with no authentication. Now Im getting the authentication error. 
Looks its not refreshing my token. if the app is closed for long time

I want the Login screen only once. Not again and again, and background refresh token. 
how to do this

**Comment by p2** [comment]
You are not using it correctly, look at the README on the develop branch, especially steps 1-3:
https://github.com/p2/OAuth2/tree/develop#usage

I'll be merging into master soon.

**Comment by phamotcreations** [comment]
Is it merged to master?
