### ISSUE TITLE
Failing to link to SwiftKeychain

### ISSUE THREAD

**Issue by vilanovi** [p2/OAuth2#241]
Currently trying to install a Swift4.0 compatible version, which is not yet on CocoaPods.

Adding this to my podfile to use your custom latest version of SwiftKeychain and the latest version of OAuth2:

    pod 'SwiftKeychain', :git => 'https://github.com/p2/SwiftKeychain.git'
    pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git'

However, when building it fails with an error on:

    Use of undeclared type 'KeychainGenericPasswordType'

Mostly, it fails to link with the Keychain.

However, in your p2.OAuth2.podspec I see you're including the Keychain files directly, which are not in the Pods.xodeproject after running a pod install. 

Therefore I'm confused. How to proceed here?

**Comment by p2** [comment]
See https://github.com/p2/OAuth2/issues/230#issuecomment-340287621

**Comment by p2** [comment]
p.s. `4.0.1` is now on CocoaPods.
