### ISSUE TITLE
How to handle multiple accessToken ?

### ISSUE THREAD

**Issue by amaurydavid** [p2/OAuth2#243]
I need to store multiple accessToken (along with their own refreshToken and expirationDate) at the same time, but I'm not sure how.

Is using a different `accountName` when instantiating an `OAuth2KeychainAccount` a good starting idea?

**Comment by p2** [comment]
It's poorly documented but you can pass a name under which to store the tokens when initializing `OAuth2`: `keychain_account_for_tokens `.

I haven't tested that a lot but if you make one `OAuth2` instance for each account and give them their own storage keys, this should work. Let me know how it goes!

See here: https://github.com/p2/OAuth2/blob/2e3d2e94e45bbd205d259634ff0cb5f0c4635417/Sources/Flows/OAuth2.swift#L51:L77

**Comment by amaurydavid** [comment]
I took the easy way: as I only have to keep 1 accessToken (it can't be refreshed so no refreshToken or expirationDate) and it's only used temporary, I just keep it in a global memory variable. Works perfectly this way ^^
