### ISSUE TITLE
Taking application's ATS configuration into account

### ISSUE THREAD

**Issue by KaiHornung** [p2/OAuth2#245]
The application's ATS configuration are not taken into account when checking if TLS is used:

Apple allows "re-activating" arbitrary loads (without TLS) using the Info.plist file, e.g.
![bildschirmfoto 2017-11-18 um 15 02 21](https://user-images.githubusercontent.com/3863017/32981039-2dc22b30-cc72-11e7-8779-924973970c65.png)
or
![bildschirmfoto 2017-11-18 um 15 02 02](https://user-images.githubusercontent.com/3863017/32981040-31420604-cc72-11e7-8a5d-f7751fc66b2c.png)

But the exception .notUsingTLS is still thrown:
![bildschirmfoto 2017-11-18 um 15 04 40](https://user-images.githubusercontent.com/3863017/32981047-54d56de0-cc72-11e7-91da-a95044899102.png)

Would it be possible to check these settings before throwing the exception?

**Comment by p2** [comment]
OAuth2 depends on TLS, it is no longer secure nor useful if used without. Therefore this library can only be used with TLS.
