### ISSUE TITLE
Crash before closing authorisation webview 

### ISSUE THREAD

**Issue by muuuberg** [p2/OAuth2#249]
Im trying to get access to Stravas API. But as soon as I press on the Authorize button I get the following crash:

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Completion handler passed to -[OAuth2.OAuth2WebViewController webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once'
> 

I'm using the embedded webview since Strava needs a http redirect uri.

**Comment by p2** [comment]
Which version/commit are you on? This seems to have been fixed in #227 .

**Comment by muuuberg** [comment]
Solved! I'm a newbie Carthage user and had version 3.0.3. I thought it automatically would have the latest commit. But now I have 4.0.1 and it works. Thank you!
