### ISSUE TITLE
Logout - oauth2.forgetTokens() doesn't fully remove tokens

### ISSUE THREAD

**Issue by nickvelloff** [p2/OAuth2#25]
With the embedded web view, oauth2.forgetTokens() doesn't seem to clear everything out.

Tried setting keychain to false.

2nd call to oauth2.authorizeEmbeddedFrom(vc, params: nil) immediately returns success with the tokens, but I would like it to force the user to log in again.

Browser caching or something? 

Thanks!

**Comment by p2** [comment]
Can you show the relevant portion of your code?

**Comment by nickvelloff** [comment]
``` Swift    
func wipeOauthTokens() {
        oauth2.forgetTokens()
    }
    
    /** Start the OAuth dance. */
    func requestToken(viewController vc: UIViewController) {
        
        oauth2.onAuthorize = { parameters in
            println("Did authorize: oauth2.onAuthorize")
        }
        oauth2.onFailure = { error in        // `error` is nil on cancel
            if nil != error {
                println("Authorization failed or declined: \(error!.localizedDescription)")
            }
        }
        
        /* --- Safari Redirect Option ---
        let url = oauth2.authorizeURL()
        UIApplication.sharedApplication().openURL(url)
        */
        
        // Embedded option
        let web = oauth2.authorizeEmbeddedFrom(vc, params: nil)
        oauth2.afterAuthorizeOrFailure = { wasFailure, error in
            web.dismissViewControllerAnimated(true, completion: nil)
            if wasFailure {
                println("Oauth2 error: \(error)")
            } else {
                KeychainAccess.sharedInstance.setToken(self.oauth2.accessToken!, key: "oatoken")
                if let scope = self.oauth2.scope {
                    KeychainAccess.sharedInstance.setToken(scope, key: "scopes")
                }
                // We must now register the APN if available
                if KeychainAccess.sharedInstance.oauthTokenViable && KeychainAccess.sharedInstance.scopesViable {
                    println("KeychainAccess.apnTokenViable, attempting to register")
                    AppModel.sharedInstance.didAuthorize = true
                    var operation = RegisterTokenProcess(delay: 0, uuid: NSUUID().lowercaseString)
                    ProcessQueue.sharedInstance.enqueue(operation)
                    
                } else {
                    assertionFailure("KeychainAccess.oauthTokenViable is false, fail loudly")
                }
            }
        }
    }
```
Basically after I "log out" the user (which is just wiping the keychain basically) when I call `requestToken` again it opens then dismissed immediately with success.

**Comment by nickvelloff** [comment]
Also:
``` Swift
private lazy var oauth2 = OAuth2CodeGrant(settings: [
        "client_id": AppConstants.Grid.ClientId,
        "client_secret": AppConstants.Grid.ClientSecret,
        "authorize_uri": AppConstants.Grid.URLS.AuthorizeURI, // /github to limit options
        "token_uri": AppConstants.Grid.URLS.TokenURI,
        "scope": AppConstants.Grid.Scope,
        "redirect_uris": [AppConstants.Grid.URLS.RedirectURI],            // app has registered this scheme
        "keychain": false,
        ])
```

**Comment by p2** [comment]
Note that you're still using the "old" flow, check the instructions for the new methods:  
https://github.com/p2/OAuth2#usage

I see you're disabling keychain completely, so you're right, I'm guessing the web-view still accesses a session it's holding on to and therefore automatically logs the user in. Inside your `wipeOAuthTokens` method, play with `NSHTTPCookieStorage` and have it delete all cookies for the domain you're authenticating against. I'll see if it's useful to have this performed automatically in the framework.

**Comment by nickvelloff** [comment]
Ok I implemented the new flow, and turned on keychain. Same result. I'll fiddle with `NSHTTPCookieStorage`

``` Swift
private lazy var oauth2 = OAuth2CodeGrant(settings: [
        "client_id": AppConstants.Grid.ClientId,
        "client_secret": AppConstants.Grid.ClientSecret,
        "authorize_uri": AppConstants.Grid.URLS.AuthorizeURI, // /github to limit options
        "token_uri": AppConstants.Grid.URLS.TokenURI,
        "scope": AppConstants.Grid.Scope,
        "redirect_uris": [AppConstants.Grid.URLS.RedirectURI],            // app has registered this scheme
        "keychain": true,
        ])
    
    func wipeOauthTokens() {
        oauth2.forgetTokens()
    }
    
    /** Start the OAuth dance. */
    func requestToken(viewController vc: UIViewController) {
        
        oauth2.authConfig.authorizeEmbedded = true
        oauth2.authConfig.authorizeContext = vc
        
        oauth2.onAuthorize = { parameters in
            println("Did authorize: oauth2.onAuthorize")
        }
        oauth2.onFailure = { error in        // `error` is nil on cancel
            if nil != error {
                println("Authorization failed or declined: \(error!.localizedDescription)")
            }
        }
        
        oauth2.afterAuthorizeOrFailure = { wasFailure, error in
            if wasFailure {
                println("Oauth2 error: \(error)")
            } else {
                KeychainAccess.sharedInstance.setToken(self.oauth2.accessToken!, key: "oatoken")
                if let scope = self.oauth2.scope {
                    KeychainAccess.sharedInstance.setToken(scope, key: "scopes")
                }
                // We must now register the APN if available
                if KeychainAccess.sharedInstance.oauthTokenViable && KeychainAccess.sharedInstance.scopesViable {
                    println("KeychainAccess.apnTokenViable, attempting to register")
                    AppModel.sharedInstance.didAuthorize = true
                    var operation = RegisterTokenProcess(delay: 0, uuid: NSUUID().lowercaseString)
                    ProcessQueue.sharedInstance.enqueue(operation)
                    
                } else {
                    assertionFailure("KeychainAccess.oauthTokenViable is false, fail loudly")
                }
            }
        }
        
        oauth2.authorize(params: nil, autoDismiss: true)
    }
```

**Comment by p2** [comment]
As a hint, you don't need to use `afterAuthorizeOrFailure`, you can split your logic between `onAuthorize` and `onFailure` as it seems.

**Comment by nickvelloff** [comment]
Ah great thanks I'll switch to those... 
This worked: 
``` Swift
let storage = NSHTTPCookieStorage.sharedHTTPCookieStorage()
        for cookie in storage.cookies as! [NSHTTPCookie]{
            storage.deleteCookie(cookie)
        }
        NSUserDefaults.standardUserDefaults()
```

**Comment by nickvelloff** [comment]
BTW thank you for this lib... great stuff.

**Comment by p2** [comment]
This deletes all the cookies, but – I think – only the ones the app created. So it should be safe to use. I'll see if I add something similar to the library, with a check to only delete cookies created during login. Won't get to it any time soon though.

Thanks, glad it's useful!

And `afterAuthorizeOrFailure` really is called immediately after either `onAuthorize` or `onFailure`, as a cheap way to always perform something.

**Comment by nickvelloff** [comment]
That is correct according to the apple docs, only the ones the app created. You could just delete the ones you create to be super safe :relaxed:

**Comment by p2** [comment]
Might be better to not piss off devs building elaborate apps with other web views. :)

**Comment by p2** [comment]
This is now [mentioned in the README](https://github.com/p2/OAuth2#7-logout), which is probably the best I can do since it's not possible to delete cookies set by Safari/SafariViewController.

**Comment by OfTheWolf** [comment]
`prompt=login` query parameter should be added to force users to login even if authorized.

So i pass it as custom params when authorize:
` oauth2.authorize(params: ["prompt": "login"]) {...
`

**See related links:**
https://stackoverflow.com/questions/26735602/why-would-oauth2-authorization-code-be-given-without-displaying-the-login-ui
https://openid.net/specs/openid-connect-core-1_0.html#Authenticates

**Comment by vinczebalazs** [comment]
> `prompt=login` query parameter should be added to force users to login even if authorized.
> 
> So i pass it as custom params when authorize:
> `oauth2.authorize(params: ["prompt": "login"]) {...`
> 
> **See related links:**
> https://stackoverflow.com/questions/26735602/why-would-oauth2-authorization-code-be-given-without-displaying-the-login-ui
> https://openid.net/specs/openid-connect-core-1_0.html#Authenticates

Thanks, this solved it for me!
