### ISSUE TITLE
Handle invalid refreshToken?

### ISSUE THREAD

**Issue by everlof** [p2/OAuth2#253]
I don't know what's the standard way to handle the password change, but I'm guessing it's pretty standard to invalidate the `refreshToken`.

I'm authenticating my users against AzureAD, and when the refresh-token is invalidated, the server will replay with status `400` and payload (trace ID, etc removed): 

```
{"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked. The user might have changed or reset their password. The grant was issued on '2018-02-13T08:48:21.2620000Z' and the TokensValidFrom date for this user is '2018-02-14T11:58:50.0000000Z'\r\nTrace ID: ....\r\nCorrelation ID: ...\r\nTimestamp: 2018-02-14 15:22:58Z","error_codes":[50173],"timestamp":"2018-02-14 15:22:58Z","trace_id":"...","correlation_id":"..."}
```

I'm not sure what I expected from the framework or what the framework expects from me. But after digging a bit, this is my conclusion:

The framework expects me catch/handle the errors, delete the `refreshToken` and call `authorize` again, is this correct?

The problem I have with this is that this will (for example when using `OAuth2DataLoader`) always throw an error for the first request after the password was changed.

Wouldn't it be alot better if we could identify the scenarios in which the `refreshToken` is invalidated, and then trigger an authorize immediately, without the round-trip of an error between the framework and the app using the framework?

I will create a PR and perhaps we can discuss it further there?

**Comment by p2** [comment]
Yes, currently that's a manual catch and re-auth process. Happy to look at a PR, just consider that token refresh (and subsequently receiving a 400 if the refresh token has been revoked) could happen in the background on some timed data fetch, so it's not necessarily desirable to call `authorize()` automatically since it requires UI.

**Comment by everlof** [comment]
Alright, good point. I'll see what I can do.

**Comment by everlof** [comment]
#254
