### ISSUE TITLE
Compile warnings in Swift 4.1 XCode 9.3

### ISSUE THREAD

**Issue by jordilaforge** [p2/OAuth2#257]
There are a lot of compiler warnings with using this library in Swift 4.1 with XCode 9.3, regarding characters and String init methods. Are you planning a new release on cocoa to fix this issues?

**Comment by Nadim87** [comment]
That happens because you use an older version. If you are using Cocoapods use
 `pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2', :submodules => true` 
in your Podfile

**Comment by jordilaforge** [comment]
yes but I dont want a git version in my cocoa file. Please release a new version in the cocoapod repo

**Comment by djbe** [comment]
4.2.0 has been released on CocoaPods 🎉
