### ISSUE TITLE
oauth2.authorize(params: ["duration":"permanent"]) not added to auth url <REDDIT>

### ISSUE THREAD

**Issue by nate-ubiquisoft** [p2/OAuth2#26]
I am trying to get a reauth token from reddit however the initial authorization url being generated using the same code flow detailed here - https://github.com/p2/OAuth2App/blob/master/OAuth2App/RedditLoader.swift - shows the following in log:

`OAuth2: Authorizing against https://www.reddit.com/api/v1/authorize.compact?client_id=XXXXXXXXXXX&redirect_uri=reddit%3A%2F%2Fresponse&scope=identity%2Cedit%2Cflair%2Chistory%2Cmysubreddits%2Cprivatemessages%2Cread%2Creport%2Csave%2Csubmit%2Csubscribe%2Cvote&response_type=code&state=66BEFFB7`

which shows no `&duration=permanent` in the url. 

I am calling `oauth2.authorize(params: ["duration":"permanent"])` but that still does not do the trick. Without reauth token support, there is no way to keep a user logged in for more than an hour without a manual relogin.

**Comment by p2** [comment]
Hmm, this works for me. Here is what I get when I run the sample app with `RedditLoader` (you need to change from GitHub to Reddit in AppDelegate **and** in ViewController... yeah, should be improved):

```
OAuth2: Looking for tokens in keychain
OAuth2: Initialized with client id ABC
OAuth2: No access token, maybe I can refresh
OAuth2: I don't have a refresh token, not trying to refresh
OAuth2: Authorizing against https://www.reddit.com/api/v1/authorize?duration=permanent&redirect_uri=ppoauthapp%3A%2F%2Foauth%2Fcallback&client_id=ABC&scope=identity&response_type=code&state=551BA220
OAuth2: Handling redirect URL ppoauthapp://oauth/callback?state=551BA220&code=DEF
OAuth2: Successfully validated redirect URL
OAuth2: Authorizing against https://www.reddit.com/api/v1/access_token?grant_type=authorization_code&client_secret=&scope=identity&code=DEF&client_id=ABC&redirect_uri=ppoauthapp%3A%2F%2Foauth%2Fcallback&state=E11E363D
OAuth2: Adding "Basic" authorization header from base64-encoded client_id:client_secret string
OAuth2: Exchanging code DEF with redirect ppoauthapp://oauth/callback for access token from Optional("https://www.reddit.com/api/v1/access_token")
OAuth2: Did exchange code for access [true] and refresh [true] tokens
OAuth2: Storing tokens to keychain
```

**Comment by p2** [comment]
BTW, note the framework has been updated and you can just use `OAuth2CodeGrant` for Reddit.

**Comment by nate-ubiquisoft** [comment]
That is what I am using. Almost exactly as you have the RedditLoader.swift file. 
##### OAuth2Reddit.swift
```swift
 //Settings for oauth2 object. Add scopes separated by commas.
    var oauth2 = OAuth2CodeGrant(settings: [
        "client_id": "XXXXXXXXXXX",
        "client_secret": "",
        "authorize_uri": "https://www.reddit.com/api/v1/authorize.compact",
        "token_uri": "https://www.reddit.com/api/v1/access_token",
        "scope": "identity,edit,flair,history,mysubreddits,privatemessages,read,report,save,submit,subscribe,vote",
        "redirect_uris": ["reddit://response"],
        "verbose": true,
        ])
    
    //Begin oauth2
    func authorize(callback: (wasFailure: Bool, error: NSError?) -> Void) {
        oauth2.authConfig.authorizeEmbedded = true
        oauth2.authConfig.authorizeContext = UIApplication.sharedApplication().keyWindow?.rootViewController
        oauth2.onAuthorize = { parameters in
            NSLog("Did authorize with parameters: \(parameters)")
        }
        oauth2.onFailure = { error in
            if nil != error {
                NSLog("Failed to authorize: \(error!.localizedDescription)")
            }
        }
        oauth2.afterAuthorizeOrFailure = callback
        //oauth2.authorize(params: ["duration":"permanent"])
        oauth2.authorize(params: ["duration" : "permanent"], autoDismiss: true)
    }

```

##### AppDelegate
```swift
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject?) -> Bool {
        //TODO: you should probably first check if this is your URL being opened
        if true {
            OAuth2Reddit.sharedInstance.oauth2.handleRedirectURL(url)
            return true
        }
    }
```

**Comment by p2** [comment]
Can you clone OAuth2App, change from GitHub to Reddit in both AppDelegate and ViewController, and see if it works? I see "duration=permanent", get asked on Reddit whether I want to authorize indefinitely and the refresh token works.

**Comment by p2** [comment]
BTW you don't need the AppDelegate method when you're using the embedded view controller.

**Comment by nate-ubiquisoft** [comment]
You are correct. When I run your OAuth2App it authorizes against `duration=permanent`. I will compare my project to your sample and see what the difference is. The first and only difference I see is that I am using CocoaPods p2_OAuth2 but that shouldnt make any difference.

**Comment by p2** [comment]
Check if you're on 1.2.4 from CocoaPods. Well, if you're not you wouldn't be able to use CodeGrant by itself with Reddit, you'd need CodeGrantBasicAuth – which would fail but you should still see `duration=permanent`. Weird.

**Comment by nate-ubiquisoft** [comment]
`Downloading dependencies
Using HanekeSwift (0.9.1)
Using p2.OAuth2 (1.2.4)
Generating Pods project
Integrating client project
`
I am using 1.2.4.

### I just found it.

If I comment out 
`//oauth2.authConfig.authorizeEmbedded = true`
`//oauth2.authConfig.authorizeContext = UIApplication.sharedApplication().keyWindow?.rootViewController`

then I get
`OAuth2: Authorizing against https://www.reddit.com/api/v1/authorize.compact?duration=permanent&redirect_uri=reddit%3A%2F%2Fresponse&client_id=XXXXXXXXXXXXX&scope=identity%2Cedit%2Cflair%2Chistory%2Cmysubreddits%2Cprivatemessages%2Cread%2Creport%2Csave%2Csubmit%2Csubscribe%2Cvote&response_type=code&state=71165190`

**Comment by nate-ubiquisoft** [comment]
It seems that using the embedded view doesnt append the additional params to the authorization url.

**Comment by p2** [comment]
Oh wow, great catch, thanks! That will need to be fixed.

**Comment by p2** [comment]
@nate-ubiquisoft I fixed it on develop branch. I'll have to merge and update the Podspec until you see it in CocoaPods. The fix is easy, if you have access to the source [look at this](https://github.com/p2/OAuth2/commit/7ac5d35c9fe01fcfc5295c28654282cd2eb48603).

Thanks for figuring this out!

**Comment by nate-ubiquisoft** [comment]
No problem I really do appreciate the quick response and resolution! 

##### Have a great weekend!!!

**Comment by p2** [comment]
Happened to be working on it; thanks, you too!

**Comment by p2** [comment]
1.2.5 is now on CocoaPods
