### ISSUE TITLE
OAuth2PasswordGrant doesn't use client_id and client_secret

### ISSUE THREAD

**Issue by FSMaxB-divae** [p2/OAuth2#264]
When making a request using the Resource Owner Password Credentials grant type, it should send the client id and secret via the HTTP basic auth authorization header, but instead they are just ignored.

This can be worked around by manually setting the request header, but this really should be done automatically by the library!

Relevant section of [RFC6749](https://tools.ietf.org/html/rfc6749#section-4.3):

>  (B) The client requests an access token from the authorization server's token endpoint by including the credentials received from the resource owner.  **When making the request, the client authenticates with the authorization server.**
>  (C)  **The authorization server authenticates the client** and validates the resource owner credentials, and if valid, issues an access token.

**Comment by FSMaxB-divae** [comment]
My code:

```swift
let oauth2 = OAuth2PasswordGrant(settings: [
	"cliend_id": "client",
	"client_secret": "secret",
	"token_uri": "https://goss:8081/oauth/token",
	"scope": "read write",
	"keychain": false,
] as OAuth2JSON)

oauth2.username = "john"
oauth2.password = "secret"
oauth2.authorize {(parameters, error) in
	let didSucceed : Bool
	if let parameters = parameters {
		didSucceed = true
	} else {
		didSucceed = false
	}

	completionHandler(didSucceed)
}
```

Request from OAuth2
----------------------------
![request](https://user-images.githubusercontent.com/39257564/40706706-e6ecdf92-63ee-11e8-8409-eb5312faaf6b.png)

As you can see there is no `Authorization` header.

Response from my backend (Spring security)
---------------------------------------------------------
![response](https://user-images.githubusercontent.com/39257564/40706716-eae9cfa6-63ee-11e8-9e65-6f2dda6ecaeb.png)

The response and request were captured using [mitmproxy](https://mitmproxy.org)

I'm using OAuth2 version 4.0.1 using Carthage in Xcode 9.4 on iOS 11.2 in the iPhone Simulator.

**Comment by FSMaxB-divae** [comment]
My current workaround:

```swift
static private func basicAuthHeader(withUsername username: String, andPassword password: String) -> [String : String] {
	guard let authorizationData = "\(username):\(password)".data(using: .utf8) else {
		fatalError("Couldn't convert basic auth string to UTF-8")
	}

	let base64 = authorizationData.base64EncodedString()

	return ["Authorization": "Basic \(base64)"]
}

static private let clientId = "client"
static private let clientSecret = "secret"
let oauth2 = OAuth2PasswordGrant(settings: [
	"cliend_id": clientId,
	"client_secret": clientSecret,
	"token_uri": "https://goss:8081/oauth/token",
	"scope": "read write",
	"keychain": false,
	"headers": basicAuthHeader(withUsername: clientId, andPassword: clientSecret),
] as OAuth2JSON)
```

**Comment by p2** [comment]
That is strange, the Auth header is added by a base class. Can you add a logger so we can see what’s happening and what not?

`OAuth2.logger = OAuth2DebugLogger(.trace)`

**Comment by FSMaxB-divae** [comment]
Hm, this is quite strange, I made a new empty iOS-App to reproduce the problem, but I can't reproduce it. I'm now investigating if I can find any differences between my test-app and the one with the problem.

Debug Log
--------------
```
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: Error refreshing token: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Requesting new access token from https://goss:8081/oauth/token
[Trace] OAuth2: REQUEST
HTTP/1.1 POST https://goss:8081/oauth/token
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Accept: application/json

grant_type=password&scope=read+write&username=john&password=secret
---
[Trace] OAuth2: RESPONSE
HTTP/1.1 401 unauthorized
Content-Type: application/json;charset=UTF-8
Www-Authenticate: Basic realm="oauth2/client"
Expires: 0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Pragma: no-cache
Transfer-Encoding: Identity
Date: Fri, 01 Jun 2018 08:15:03 GMT
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-Frame-Options: DENY

{"timestamp":"2018-06-01T08:15:03.397+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/oauth/token"}
---
[Debug] OAuth2: The username or password is incorrect
```

**Comment by FSMaxB-divae** [comment]
🤦 I found the issue.

> `"cliend_id"`

Just a Typo on my side!

Sorry for wasting your time.

**Comment by p2** [comment]
Man, I thought I checked that, guess we're both blind. :) Thanks for confirming!
