### ISSUE TITLE
Unable to get data from the keychain by background applications?

### ISSUE THREAD

**Issue by KimKellerRasmussen** [p2/OAuth2#267]
It looks (to me) like the SwiftKeychain uses the kSecAttrAccessibleWhenUnlocked attribute and not the kSecAttrAccessibleAfterFirstUnlock ? - or are you using another implementation ?

Link: https://developer.apple.com/documentation/security/ksecattraccessibleafterfirstunlock

kSecAttrAccessibleWhenUnlocked: 
> The data in the keychain item can be accessed only while the device is unlocked by the user.

kSecAttrAccessibleAfterFirstUnlock:
> The data in the keychain item cannot be accessed after a restart until the device has been unlocked once by the user. After the first unlock, the data remains accessible until the next restart. __This is recommended for items that need to be accessed by background applications__. Items with this attribute migrate to a new device when using encrypted backups.

**Comment by KimKellerRasmussen** [comment]
Just found out that you can set the `keychain_access_mode` in the settings...

**Comment by KimKellerRasmussen** [comment]
I have tried to set the `keychain_access_mode` but it does not seem to be work - i'll get an error when updating the keychain value (-50 errorSecParam).

When I change the (default) value in the keychain.swift file (around line 35) the error dissapear:

```
public var accessMode: String {        
        return String(kSecAttrAccessibleWhenUnlocked)
    }
```

**Comment by p2** [comment]
You need to set it as `String`, are you doing that?

```
"keychain_access_mode": String(kSecAttrAccessibleWhenUnlocked)
```

Should add a warning in [OAuth2Securable](https://github.com/p2/OAuth2/blob/3d242f21738d2adfd1a308f9eb3ca1ee26e30b17/Sources/Base/OAuth2Securable.swift#L81) if it's present but not as a string.

**Comment by KimKellerRasmussen** [comment]
No, I just set is as follows:

`"keychain_access_mode": "kSecAttrAccessibleWhenUnlocked"`

My initial attempt still fails using your version... But I have to test it more thoroughly...

By the way - not all return codes from saveInKeychain() are errors; -25299 means that the item already exists.

I found this short list of [Keychain Error Codes](https://www.safaribooksonline.com/library/view/ios-components-and/9780133086898/ch18lev2sec7.html)

**Comment by p2** [comment]
Let me know how it goes, this setting should definitely work.

Error `errSecDuplicateItem ` (25299) is [being taken care of](https://github.com/p2/SwiftKeychain/blob/a7fee4ba90cc77705f979ba14daa26fc39ef3c65/Keychain/Keychain.swift#L131).
