### ISSUE TITLE
Does not automatically refresh token after it is expired

### ISSUE THREAD

**Issue by hamedazhar-giz** [p2/OAuth2#269]
The refresh token used for authentication does not get automatically refreshed after its validity gets expired.

At first, I got:
**OAuth2: Found access token, valid until 2018-06-19 13:42:15 +0000**

After the token gets expired, the following shows:
**OAuth2: Found access token but it seems to have expired**

and then leading to the login screen. So the user gets that login screen every time the token gets expired!! That should not happen. I didn't get any solutions anywhere.
None of you have got this issue yet? Any help is much appreciated.

**Comment by p2** [comment]
Can you post full logs? Right after the logs you post you should see "Found refresh token" or you don't have a refresh token. If you have one, a refresh is attempted before showing the authorize screen.

**Comment by hamedazhar-giz** [comment]
Full log after token expiration:

**[Debug] OAuth2: Initialization finished
[Debug] OAuth2: Looking for items in keychain
[Debug] OAuth2: Found access token but it seems to have expired
[Debug] OAuth2: Initialization finished
[Debug] OAuth2: Looking for items in keychain
[Debug] OAuth2: Found access token but it seems to have expired**

Same log repeated twice.

**Comment by p2** [comment]
And if you then call `authorize()`? It looks like you don't have a refresh token. Do a regular authorize and check the logs to see which tokens you got.

**Comment by hamedazhar-giz** [comment]
What do you mean by "regular authorize" ?
Can you please explain? If u can please elaborate with code.

**Comment by p2** [comment]
Call `authorize()`: https://github.com/p2/OAuth2#4-manually-authorize-the-user

**Comment by hamedazhar-giz** [comment]
Sorry for the delay, the following log is obtained when I call `authorize()` after the token gets expired.

**[Debug] OAuth2: Initialization finished
[Debug] OAuth2: Looking for items in keychain
[Debug] OAuth2: Found access token but it seems to have expired
[Debug] OAuth2: Initialization finished
[Debug] OAuth2: Looking for items in keychain
[Debug] OAuth2: Found access token but it seems to have expired
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: Error refreshing token: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Opening authorize URL embedded: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?state=64C99D11&response_type=code&scope=Calendars.Read&redirect_uri=project%3A%2F%2Foauth2%2Fcallback&client_id=xxxxx-xxxx-xxxx-xxxx-xxxxxx
[Debug] OAuth2: No authorization context present
Authorization was canceled or went wrong: Optional(No authorization context present)
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: Error refreshing token: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Opening authorize URL embedded: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?state=64C99D11&response_type=code&scope=Calendars.Read&redirect_uri=project%3A%2F%2Foauth2%2Fcallback&client_id=xxxxx-xxxx-xxxx-xxxx-xxxxxx
[Debug] OAuth2: No authorization context present
Authorization was canceled or went wrong: Optional(No authorization context present)
response...
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: Error refreshing token: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Opening authorize URL embedded: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?state=64C99D11&response_type=code&scope=Calendars.Read&redirect_uri=project%3A%2F%2Foauth2%2Fcallback&client_id=xxxxx-xxxx-xxxx-xxxx-xxxxxx
[Debug] OAuth2: No authorization context present
Authorization was canceled or went wrong: Optional(No authorization context present)**

**Comment by p2** [comment]
Yes, see the error: **No authorization context present**. You need to set the context as documented in the README:

```
oauth2.authConfig.authorizeContext = <# presenting view controller / window #>
```

Then try again and post your log again.

**Comment by hamedazhar-giz** [comment]
When I am going through [https://github.com/p2/OAuth2#keychain](url) 

> Ideally, access tokens get delivered with an "expires_in" parameter that tells you how long the token is valid. If it is missing the framework will still use those tokens if one is found in the keychain and not re-perform the OAuth dance. You will need to intercept 401s and re-authorize if an access token has expired

**Comment by p2** [comment]
You can only re-authorize without showing the login screen when you have a refresh token. Can you post the log when you authorize **the first time**? Then we can see whether you receive a `refresh_token` at all. Only if you receive one can the framework automatically use it to receive a new `access_token`.

**Comment by hamedazhar-giz** [comment]
Oh really! This is the log obtained after the first login:
**Did exchange code for access [true] and refresh [false] tokens
[Debug] OAuth2: Storing tokens to keychain
2018-06-27 10:03:35.278621+0530 SoShall[1289:678367] Access token: EwBAA8l6BAAURSN/FHlDW5xN74t6GzbtsBBeBUYAAfs1rSmpbK3Xs6Uu+oSncVPsZOzcZx7L1Sk3gVSLyMD9188SVKUqW+trFAsFrlzzOVz4isxG/joPcHRNhKK+VBJ+eQY+P8/IaxgvFd8kCW7YkPfaoPyak5ygyqFGMf3dGh3P2zgJ4vUStuQ1adRnacobOS6DxvK/ebyrMC4tquKKr7U5JFW0rFBUvg0XO692vq5C++8579RBed2NpYvjFEF7epdTMM/AJ27NOFDkDmY8muCIyE6E2OVKz0dnzYuLGr/f78hIUJi1r/l92E5j35GbyDJ0LcRaJBIVcgQrCMf8WmK1N/61HGkETYKeJQl/UhdhoHWy8ntFsjdRNioSFiEDZgAACAYiR8UZg492EALuonNuVSml+pHzGxDs3KAkhDKnSgAMJ0FeP1tEPf4PPdnGSgbStoCCTimJzfe5wJp3MEMPwVRHGR9+e865EihYkdSwRoPL06ySjuboe4x51FNjoPiCYBd+aYD+n5f7BbflNsJT21aShMbaroOw4lTUwe4RmDXnEpvkQBqzjxqPYvqFAm3j1mzgyYKWONYYMSNgo+mWf5CC+KrE0xHB0nejj+M4lb+oah8s4eCDt//IcULinW5EP7KFxCpwi7OWjdJhg7pJsJIBJghYP9AJIhuTclwYDroj4s3dk+dcdzvCBRJ+HdY8tlIHd+7Od/AyjUT1Co98RTj6ZRH/lQEX0nggH5KheiCAT3Bysds/Qf+XjIka0QpU78o/Q5ncrNWVB3n8MITF1H3t6NuPTriguVvSoGrw/5MZXVbQuQQHOjDtCc2EkoysaVIKEEAtaxncg6ULxs09ir1qmze+k+Ga9jfI6jfKnuwPVG+6tYWCg1lBnutoNfABechNOfzRaZg39cFs+yUqi52R+dMoRrq88Gd2zXZgSnM9VPi4M8qWPpDRCgN57e6Ro36tOG6KDHTMJ+/y43fP6yyj4ly/FfccY8VX5QgA1EO74
2018-06-27 10:03:35.281954+0530 SoShall[1289:678367] Successfully logged in.
Authorized! Access token is in  Optional("EwBAA8l6BAAURSN/FHlDW5xN74t6GzbtsBBeBUYAAfs1rSmpbK3Xs6Uu+oSncVPsZOzcZx7L1Sk3gVSLyMD9188SVKUqW+trFAsFrlzzOVz4isxG/joPcHRNhKK+VBJ+eQY+P8/IaxgvFd8kCW7YkPfaoPyak5ygyqFGMf3dGh3P2zgJ4vUStuQ1adRnacobOS6DxvK/ebyrMC4tquKKr7U5JFW0rFBUvg0XO692vq5C++8579RBed2NpYvjFEF7epdTMM/AJ27NOFDkDmY8muCIyE6E2OVKz0dnzYuLGr/f78hIUJi1r/l92E5j35GbyDJ0LcRaJBIVcgQrCMf8WmK1N/61HGkETYKeJQl/UhdhoHWy8ntFsjdRNioSFiEDZgAACAYiR8UZg492EALuonNuVSml+pHzGxDs3KAkhDKnSgAMJ0FeP1tEPf4PPdnGSgbStoCCTimJzfe5wJp3MEMPwVRHGR9+e865EihYkdSwRoPL06ySjuboe4x51FNjoPiCYBd+aYD+n5f7BbflNsJT21aShMbaroOw4lTUwe4RmDXnEpvkQBqzjxqPYvqFAm3j1mzgyYKWONYYMSNgo+mWf5CC+KrE0xHB0nejj+M4lb+oah8s4eCDt//IcULinW5EP7KFxCpwi7OWjdJhg7pJsJIBJghYP9AJIhuTclwYDroj4s3dk+dcdzvCBRJ+HdY8tlIHd+7Od/AyjUT1Co98RTj6ZRH/lQEX0nggH5KheiCAT3Bysds/Qf+XjIka0QpU78o/Q5ncrNWVB3n8MITF1H3t6NuPTriguVvSoGrw/5MZXVbQuQQHOjDtCc2EkoysaVIKEEAtaxncg6ULxs09ir1qmze+k+Ga9jfI6jfKnuwPVG+6tYWCg1lBnutoNfABechNOfzRaZg39cFs+yUqi52R+dMoRrq88Gd2zXZgSnM9VPi4M8qWPpDRCgN57e6Ro36tOG6KDHTMJ+/y43fP6yyj4ly/FfccY8VX5QgA1EO74MuTgcRVoFWH/rVdzGyHS9BqjP2V2yXdCg1ARrWkQJoaHz2kr9gqtjFPqjW0qsnt6GKQuVkOL1Ag4z9JeeW4Fo4gg2xl7h+ebrRJAg==")
Authorized! refreshToken is in  nil
Authorized! Access token is in  Optional("EwBAA8l6BAAURSN/FHlDW5xN74t6GzbtsBBeBUYAAfs1rSmpbK3Xs6Uu+oSncVPsZOzcZx7L1Sk3gVSLyMD9188SVKUqW+trFAsFrlzzOVz4isxG/joPcHRNhKK+VBJ+eQY+P8/IaxgvFd8kCW7YkPfaoPyak5ygyqFGMf3dGh3P2zgJ4vUStuQ1adRnacobOS6DxvK/ebyrMC4tquKKr7U5JFW0rFBUvg0XO692vq5C++8579RBed2NpYvjFEF7epdTMM/AJ27NOFDkDmY8muCIyE6E2OVKz0dnzYuLGr/f78hIUJi1r/l92E5j35GbyDJ0LcRaJBIVcgQrCMf8WmK1N/61HGkETYKeJQl/UhdhoHWy8ntFsjdRNioSFiEDZgAACAYiR8UZg492EALuonNuVSml+pHzGxDs3KAkhDKnSgAMJ0FeP1tEPf4PPdnGSgbStoCCTimJzfe5wJp3MEMPwVRHGR9+e865EihYkdSwRoPL06ySjuboe4x51FNjoPiCYBd+aYD+n5f7BbflNsJT21aShMbaroOw4lTUwe4RmDXnEpvkQBqzjxqPYvqFAm3j1mzgyYKWONYYMSNgo+mWf5CC+KrE0xHB0nejj+M4lb+oah8s4eCDt//IcULinW5EP7KFxCpwi7OWjdJhg7pJsJIBJghYP9AJIhuTclwYDroj4s3dk+dcdzvCBRJ+HdY8tlIHd+7Od/AyjUT1Co98RTj6ZRH/lQEX0nggH5KheiCAT3Bysds/Qf+XjIka0QpU78o/Q5ncrNWVB3n8MITF1H3t6NuPTriguVvSoGrw/5MZXVbQuQQHOjDtCc2EkoysaVIKEEAtaxncg6ULxs09ir1qmze+k+Ga9jfI6jfKnuwPVG+6tYWCg1lBnutoNfABechNOfzRaZg39cFs+yUqi52R+dMoRrq88Gd2zXZgSnM9VPi4M8qWPpDRCgN57e6Ro36tOG6KDHTMJ+/y43fP6yyj4ly/FfccY8VX5QgA1EO74MuTgcRVoFWH/rVdzGyHS9BqjP2V2yXdCg1ARrWkQJoaHz2kr9gqtjFPqjW0qsnt6GKQuVkOL1Ag4z9JeeW4Fo4gg2xl7h+ebrRJAg==")
Authorized! refreshToken is in  nil
Authorization was canceled or went wrong: Optional(The client is already authorizing, wait for it to finish or abort authorization before trying again)
2018-06-27 10:03:35.305846+0530 SoShall[1289:678367] Making request to https://graph.microsoft.com/v1.0/me/events?$top=10&$select=subject,start,end&$orderby=start/dateTime              0X0P+0SC
[Debug] OAuth2: Initialization finished**

I think refresh token is nil! Then how to obtain that?

**Comment by p2** [comment]
Yes, you're not getting a refresh token. Consult the Outlook documentation on how to receive one. Closing this for now.
