### ISSUE TITLE
Missing expires_in causes access token to always appear expired

### ISSUE THREAD

**Issue by jkusnier** [p2/OAuth2#27]
According to [OAuth 2.0 RFC](https://tools.ietf.org/html/rfc6749#section-5.1)
```
expires_in
         RECOMMENDED.  The lifetime in seconds of the access token.  For
         example, the value "3600" denotes that the access token will
         expire in one hour from the time the response was generated.
         If omitted, the authorization server SHOULD provide the
         expiration time via other means or document the default value.
```

If expires_in is not present, each re-launch of the app will result in the error:
```
OAuth2: Found access token but it seems to have expired
```

Would it be possible to add an option to set a default expires in interval when one isn't provided by the access token response or treat the token as permanent?

**Comment by p2** [comment]
I was thinking about this, GitHub for example does not issue `expires_in`. Best way would probably be to test if the token still works, which would require a URL. Could be a setting like `token_test_url` or something.

(BTW I changed this log entry just recently to be more informative)

**Comment by paulwilton** [comment]
yes Instagram auth2 implementation also does not send expires_in  , 
"Even though the access token does not specify an expiration time, your app should handle the case that either the user revokes access, or Instagram expires the token after some period of time. In this case, your meta of your responses will contain an “error_type=OAuthAccessTokenError”. In other words: do not assume your access_token is valid forever."

**Comment by paulwilton** [comment]
reading this it might be best to use a combination of the suggested approaches for dealing with this, i.e. use an estimate for token expiry and a test at the end of that estimate if expiry is not supplied :  
https://rnd.feide.no/2012/04/19/best-practice-for-dealing-with-oauth-2-0-token-expiration-at-the-consumer/

**Comment by p2** [comment]
The develop branch now has `accessTokenAssumeUnexpired`, which is _true_ by default, to handle these cases.

**Comment by p2** [comment]
This is now in `1.2.7`.
