### ISSUE TITLE
forgetTokens() does not remove tokens from keychain!

### ISSUE THREAD

**Issue by hamedazhar-giz** [p2/OAuth2#272]
Implemented this library for integrating Outlook calendar. When the user logouts from the app, `oauth2.forgetTokens()` is called. When the user again enters the app with normal login and then tries to sync the outlook using **OAuth2**, the previous `accessToken` is taken and the sync process gets done.
This should not happen, as when a user logs out from the app, basically all accounts which are synced with him also should gets **logged** **out**!
This works fine when the app is uninstalled and then installed.
Any help is much appreciated.

**Comment by p2** [comment]
Are you running into the issue called out in the README under ["Logout"](https://github.com/p2/OAuth2#9-logout)? Otherwise post a log from logout and then login again.

**Comment by p2** [comment]
Yes, `forgetTokens()` removes the tokens from memory and from keychain. Can you post your code snippets and logs in the situation where you find that the token is still present?

**Comment by hamedazhar-giz** [comment]
After `oauth2.forgetTokens()`,
**[Debug] OAuth2: Forgetting tokens and removing them from keychain**
Then started **re-login**,
**[Debug] OAuth2: Starting authorization
[Debug] OAuth2: Have an apparently unexpired access token
[Debug] OAuth2: Storing tokens to keychain**

Then again I tried `oauth2.forgetTokens()`,
**[Debug] OAuth2: Forgetting tokens and removing them from keychain**
When i clicked again `oauth2.forgetTokens()`,
**[Debug] OAuth2: Forgetting tokens and removing them from keychain
[Warn!] OAuth2: Failed to delete tokens from keychain: Error Domain=swift.keychain.error Code=-25300 "(null)"**
So I think the issue is the tokens are not deleting from keychain. What is you opinion?

**Comment by p2** [comment]
You get error 25300, which is errSecItemNotFound, meaning they do get deleted from the keychain. It appears though that your `oauth2` instance still has them in memory, which shouldn’t be the case since it’s nilled out in code. Do you have the latest version (check the `forgetTokens()` code path) and do you only have one instance?

**Comment by hamedazhar-giz** [comment]
Yes, it works fine even after clearing the app from background. How  do I check the version?

**Comment by hamedazhar-giz** [comment]
By installing `pod 'p2.OAuth2'`

**Comment by p2** [comment]
CocoaPods is not a recommended way to install since it’s not being updated. Make sure you have installed the latest version either from git or using the pod command shown in this issue’s comment: #263.

You can reopen this issue if it persists.

**Comment by hamedazhar-giz** [comment]
The version I'm using is 4.0.1. Is that good?

**Comment by p2** [comment]
Yes, that one's good. I still think the error is in your code, try to step through your code when deleting tokens or paste the relevant code bits here.

**Comment by hamedazhar-giz** [comment]
Regretting the most! It was my mistake, though. I had another instance of the class which in turn give token even after logging out. Sorry for the inconvenience caused! :(

**Comment by p2** [comment]
No worries, glad to hear you found the issue!

**Comment by rajesh-ecommsys** [comment]
[Debug] OAuth2: Forgetting tokens and removing them from keychain

[Warn!] OAuth2: Failed to delete tokens from keychain: Error Domain=swift.keychain.error Code=-25300 "(null)"

still not working for me, if any one have solution please send me..

**Comment by fazalulrahimanedv** [comment]
I was facing the same issue but instead of sticking to `forgetTokens()` **(this may not be the perfect solution kind of a workaround)** only I have **managed to do the logout functionality by using safari** instead of embedded browser (in the web part I have validated logout by invalidating the session if you are using embedded to login and safari to logout or vice versa this won't work because the session instance of embedded and browser are different)
