### ISSUE TITLE
SwiftKeychain can't be found when installing using cocoapods from master

### ISSUE THREAD

**Issue by 343max** [p2/OAuth2#277]
when installing OAuth2 from cocoapods like this:

`pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :branch => 'master'`

the SwiftKeychain dependency won't be loaded. Adding it as a dependency to the Podfile doesn't seem to work either. For now I added the git repository as a submodule and using `:path` to find it, but I guess that's not the way it's supposed to be.

What am I doing wrong?

**Comment by p2** [comment]
You’re missing the `:submodules` flag, see the instructions in the [README under CocoaPods](
https://github.com/p2/OAuth2#cocoapods).
