### ISSUE TITLE
Podspec update

### ISSUE THREAD

**Issue by doudmas** [p2/OAuth2#278]
We cannot get the last updates from 10 months in a simple way if we use Cocoapods as dependency manager.
Could you update the file `p2.OAuth2.podspec` with a new version of the framework and push it to the Cocoapods repo ?

**Comment by p2** [comment]
You can still get the latest and greatest via CocoaPods, [see here](https://github.com/p2/OAuth2#cocoapods). Also refer to #230.

**Comment by djbe** [comment]
4.2.0 has been released on CocoaPods 🎉
