### ISSUE TITLE
Compilation Error : UIScrollViewDecelerationRateNormal renamed (Xcode 10, Swift 4.2)

### ISSUE THREAD

**Issue by ProgrammerLT** [p2/OAuth2#285]
Hi, I'm a newbie in Cocoapods and 3rd party frameworks so please comment or ask if info is missing for this request.

I tried to integrate OAuth2 and it cannot be built because of the renaming of :

UIScrollViewDecelerationRateNormal to UIScrollView.Deceleration.normal.

Thanks for helping.

**Comment by p2** [comment]
Are you using Cocoapods like [documented in the README](
https://github.com/p2/OAuth2#cocoapods) at the very bottom? Also see #230.

**Comment by ProgrammerLT** [comment]
Hi Pascal,
I did not understand what downloading the "bleeding edge" of this framework meant and implied. After more research on Cocoapods, I used the solution in README and everything is working fine.

Thanks for helping and for your framework.

**Comment by p2** [comment]
Great! "bleeding edge" just means you get the latest code from here. The version that is on Cocoapods is outdated.
