### ISSUE TITLE
New Https required Redirect URI error

### ISSUE THREAD

**Issue by riverbaymark** [p2/OAuth2#286]
Greetings,

So for the API I am calling for OAuth, I um unable to use a SafariView due to the required https:// redirect url.  As I am watching the debugging I am able to grab the code, but when I it tries to exchange it for a token, I get this error:

Completion handler passed to -[OAuth2.OAuth2WebViewController webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once

Any ideas?

Thanks!

**Comment by p2** [comment]
This was fixed a while ago. How are you installing the framework?

**Comment by riverbaymark** [comment]
Hi Pascal,

I just went back and checked and I installed it via git.  Maybe I should reinstall via Carthage?

Thanks!

Mark

**Comment by p2** [comment]
No, git is great! Are you on master? [Here](https://github.com/p2/OAuth2/blob/master/Sources/iOS/OAuth2WebViewController.swift#L194) is the relevant code.

**Comment by riverbaymark** [comment]
Thank you!  I will inspect to make sure I am on master and look at the code.  This is very helpful!

I will let you know what I find out.

Mark

**Comment by riverbaymark** [comment]
It turns out I wasn't using master after all.  I just went back and reinstalled and it works beautifully!

Thanks Pascal and great work on this and all your stuff with Apple Health!  As a provider / developer myself you are helping us to be able to escape the realms of horrible medical software we have had to work with for years by enabling us to build our own!

Mark
