### ISSUE TITLE
Release with Swift 4.2 support

### ISSUE THREAD

**Issue by twiedow** [p2/OAuth2#288]
I saw that you already made changes on master for Swift 4.2 support. Do you already have a plan to make a new release with support for Swift 4.2 and Xcode 10?

**Comment by jmbene** [comment]
Any news to release a tag and update the podspecs @p2? Thanks

**Comment by p2** [comment]
There are no plans to push to Cocoapods, Carthage is a much better solution for Swift programming. To use latest `master` with Cocoapods, use:

```
pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :submodules => true, :branch => 'master'
```

To pin to a specific version:

```
pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :submodules => true, :tag => '4.0.0'
```

Reference: [using the Podfile](http://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo)

**Comment by dmsl1805** [comment]
Hi @p2, it is used on the production product which tied with Cocoapods and moving to Carthage is not available right now. Could you please update v 4.0.1 on pods? Confusing is that v 4.0.1 on GitHub and current master is not equal to 4.0.1 on pods. Will be very helpful if you support Cocoapods also. Thanks!
