### ISSUE TITLE
exception in completion handler (authorizeEmbedded = true)

### ISSUE THREAD

**Issue by McWare** [p2/OAuth2#289]
I included oAuth2 into a Mac OS X - Swift 4.2 project using Xcode 10 (release) .. converted framework to Swift 4.2. My authorization setup to access Withings API works perfect, but I get these exceptions:

2018-10-13 15:45:56.016573+0200 Live2Better[3606:707711] [General] Completion handler passed to -[OAuth2.OAuth2WebViewController webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once
2018-10-13 15:45:56.018650+0200 Live2Better[3606:707711] [General] (
	0   CoreFoundation                      0x00007fff2978e66b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff509e4942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2981e955 +[NSException raise:format:] + 197
	3   WebKit                              0x00007fff383a6441 _ZNK6WebKit28CompletionHandlerCallChecker30completionHandlerHasBeenCalledEv + 203
	4   WebKit                              0x00007fff383dee16 _ZZN6WebKit15NavigationState16NavigationClient31decidePolicyForNavigationActionERNS_12WebPageProxyEON3WTF3RefIN3API16NavigationActionENS4_13DumbPtrTraitsIS7_EEEEONS5_INS_27WebFramePolicyListenerProxyENS8_ISC_EEEEPNS6_6ObjectEEN3$_1clE24WKNavigationActionPolicyP18_WKWebsitePolicies + 36
	5   OAuth2                              0x0000000100c46bf9 $SSo24WKNavigationActionPolicyVIeyBy_ABIegy_TR + 25
	6   OAuth2                              0x0000000100c46c4d $SSo24WKNavigationActionPolicyVIeyBy_ABIegy_TRTA + 13
	7   OAuth2                              0x0000000100c46a67 $S6OAuth20A17WebViewControllerC03webC0_15decidePolicyFor15decisionHandlerySo05WKWebC0C_So18WKNavigationActionCySo0lmG0VctF + 2791
	8   OAuth2                              0x0000000100c46bb0 $S6OAuth20A17WebViewControllerC03webC0_15decidePolicyFor15decisionHandlerySo05WKWebC0C_So18WKNavigationActionCySo0lmG0VctFTo + 160
	9   WebKit                              0x00007fff383dc63e _ZN6WebKit15NavigationState16NavigationClient31decidePolicyForNavigationActionERNS_12WebPageProxyEON3WTF3RefIN3API16NavigationActionENS4_13DumbPtrTraitsIS7_EEEEONS5_INS_27WebFramePolicyListenerProxyENS8_ISC_EEEEPNS6_6ObjectE + 762
	10  WebKit                              0x00007fff385a5658 _ZN6WebKit12WebPageProxy31decidePolicyForNavigationActionEyRKN7WebCore18SecurityOriginDataEyONS_20NavigationActionDataERKNS_13FrameInfoDataEyRKNS1_15ResourceRequestEOSA_yRKNS_8UserDataERbRyRNS1_12PolicyActionERNS_10DownloadIDERSt8optionalINS_19WebsitePoliciesDataEE + 1152
	11  WebKit                              0x00007fff385cf11d _ZN3IPC22callMemberFunctionImplIN6WebKit12WebPageProxyEMS2_FvyRKN7WebCore18SecurityOriginDataEyONS1_20NavigationActionDataERKNS1_13FrameInfoDataEyRKNS3_15ResourceRequestEOSC_yRKNS1_8UserDataERbRyRNS3_12PolicyActionERNS1_10DownloadIDERSt8optionalINS1_19WebsitePoliciesDataEEENSt3__15tupleIJyS4_yS7_S9_ySC_SC_ySG_EEEJLm0ELm1ELm2ELm3ELm4ELm5ELm6ELm7ELm8ELm9EENSW_IJbySL_SN_SR_EEEJLm0ELm1ELm2ELm3ELm4EEEEvPT_T0_OT1_RT3_NSV_16integer_sequenceImJXspT2_EEEENS16_ImJXspT4_EEEE + 139
	12  WebKit                              0x00007fff385c5583 _ZN3IPC13handleMessageIN8Messages12WebPageProxy31DecidePolicyForNavigationActionEN6WebKit12WebPageProxyEMS5_FvyRKN7WebCore18SecurityOriginDataEyONS4_20NavigationActionDataERKNS4_13FrameInfoDataEyRKNS6_15ResourceRequestEOSF_yRKNS4_8UserDataERbRyRNS6_12PolicyActionERNS4_10DownloadIDERSt8optionalINS4_19WebsitePoliciesDataEEEEEvRNS_7DecoderERNS_7EncoderEPT0_T1_ + 304
	13  WebKit                              0x00007fff383d953f _ZN3IPC18MessageReceiverMap19dispatchSyncMessageERNS_10ConnectionERNS_7DecoderERNSt3__110unique_ptrINS_7EncoderENS5_14default_deleteIS7_EEEE + 141
	14  WebKit                              0x00007fff386153ac _ZN6WebKit15WebProcessProxy21didReceiveSyncMessageERN3IPC10ConnectionERNS1_7DecoderERNSt3__110unique_ptrINS1_7EncoderENS6_14default_deleteIS8_EEEE + 28
	15  WebKit                              0x00007fff383a91c7 _ZN3IPC10Connection19dispatchSyncMessageERNS_7DecoderE + 203
	16  WebKit                              0x00007fff383a687e _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 104
	17  WebKit                              0x00007fff383a93e4 _ZN3IPC10Connection18dispatchOneMessageEv + 176
	18  JavaScriptCore                      0x00007fff2d38809c _ZN3WTF7RunLoop11performWorkEv + 236
	19  JavaScriptCore                      0x00007fff2d388332 _ZN3WTF7RunLoop11performWorkEPv + 34
	20  CoreFoundation                      0x00007fff29727d31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	21  CoreFoundation                      0x00007fff297df60c __CFRunLoopDoSource0 + 108
	22  CoreFoundation                      0x00007fff2970ace0 __CFRunLoopDoSources0 + 208
	23  CoreFoundation                      0x00007fff2970a15d __CFRunLoopRun + 1293
	24  CoreFoundation                      0x00007fff297099b7 CFRunLoopRunSpecific + 487
	25  HIToolbox                           0x00007fff289e9d96 RunCurrentEventLoopInMode + 286
	26  HIToolbox                           0x00007fff289e9b06 ReceiveNextEventCommon + 613
	27  HIToolbox                           0x00007fff289e9884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	28  AppKit                              0x00007fff26c9aa73 _DPSNextEvent + 2085
	29  AppKit                              0x00007fff27430e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	30  AppKit                              0x00007fff26c8f885 -[NSApplication run] + 764
	31  AppKit                              0x00007fff26c5ea72 NSApplicationMain + 804
	32  Live2Better                         0x000000010001fa1d main + 13
	33  libdyld.dylib                       0x00007fff515fb015 start + 1
	34  ???                                 0x0000000000000003 0x0 + 3

cannot identify why! Any help appreciated?

**Comment by p2** [comment]
See #286
