### ISSUE TITLE
update example to swift 4.2 xcode 10

### ISSUE THREAD

**Issue by fukemy** [p2/OAuth2#291]
Hello. I saw our sample is using swift 3. Can you update to xcode 10?
I got this problem in swift 4.2:

<img width="904" alt="screen shot 2018-10-21 at 01 48 44" src="https://user-images.githubusercontent.com/8202437/47259411-77544700-d4d3-11e8-802a-743f11ab74c3.png">

**Comment by ossus-lib** [comment]
It's now updated.
