### ISSUE TITLE
How to add OAuth2 as dependency into another cocoapod?

### ISSUE THREAD

**Issue by rapinto** [p2/OAuth2#301]
Hi,

Everything works fine when I link OAuth2 from the Podfile of my project using : 
`pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2', :submodules => true`

But I'm trying to embed OAuth2 into a custom private cocoapod (Swift 4.2). 
Here is how I'm trying to make the dependency from my 'podspec' : 
`s.dependency 'p2.OAuth2'`

But when I try to lint my custom pod, I always get the following error : 

    

> - ERROR | [iOS] xcodebuild:  p2.OAuth2/Sources/iOS/OAuth2WebViewController.swift:118:37: error: 'UIScrollViewDecelerationRateNormal' has been renamed to 'UIScrollView.DecelerationRate.normal'
>     - NOTE  | [iOS] xcodebuild:  UIKit.UIScrollViewDecelerationRateNormal:3:12: note: 'UIScrollViewDecelerationRateNormal' was obsoleted in Swift 3

Is it possible? What am I doing wrong?

Thanks!

**Comment by ossus-lib** [comment]
This should now work, can you try again?
