### ISSUE TITLE
Push releases 5.0.0 and 5.1.0 on CocoaPods

### ISSUE THREAD

**Issue by MarcoFilosi** [p2/OAuth2#316]
Using CocoaPods 1.7.3, XCode 10.2.1 (10E1001).

It seems p2.OAuth2 pod needs SwiftKeychain now, but the SwiftKeychain is an old pod and it is not re-written in Swift 4.0 or above.

Pod p2.OAuth2 5.0.0 is not usable on XCode 10.2.1. Please fix this issue

**Comment by MarcoFilosi** [comment]
Also `p2.OAuth2 5.1.0` is affected by this issue

**Comment by drdavec** [comment]
Your original post on July 2 indicated that this issue is caused by an old SwiftKeychain pod that is not re-written in Swift 4.  Can you confirm that this error is caused by this old SwiftKeychain pod?  I use Swift Package Manager with 5.1.0 and do not experience this problem.

**Comment by MarcoFilosi** [comment]
Thanks for your reply @drdavec . I want to be more clear here so you can reproduce and fix this issue.

XCode Version 10.3 (10G8)
CocoaPods 1.7.5

First issue: if we write `pod 'p2.OAuth2', '5.1.0'` in Podfile, CocoaPods is not able to install it because this release is not found.
To cope with it I specified the commit in this way: `pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :commit => 'e4deb6c'`

I installed the pod into my current workspace executing `pod install`.

When I try to compile the workspace I have 11 errors (you can see image attached).

I found the fix [here](https://github.com/p2/OAuth2/issues/137) by adding `:submodules => true` to Podfile:
`pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2.git', :commit => 'e4deb6c', :submodules => true`

By the way, please push releases 5.0.0 and 5.1.0 on CocoaPods. Thanks 

![p2 OAuth compile errors](https://user-images.githubusercontent.com/1218291/65246121-381ce480-daee-11e9-8251-c648cc3d745a.png)

**Comment by ossus-lib** [comment]
It's best to update to Xcode 11 and use Swift Packages, CocoaPods is no longer supported.
