### ISSUE TITLE
Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by lasseporsch** [p2/OAuth2#323]
We have just uploaded one of our apps with p2.OAuth2 to AppStoreConnect, and got the following warning from Apple:

> We identified one or more issues with a recent delivery for your app. Your delivery was successful, but you may wish to correct the following issues in your next delivery:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

A quick Xcode search found that the only usage of UIWebView in our app was in p2.OAuth2. We currently use version 5.0.0

**Comment by ossus-lib** [comment]
Are you sure you're using version 5? `UIWebView` had been replaced by `WKWebView` in #173 3 years ago.
