### ISSUE TITLE
Use of unresolved identifier Keychain

### ISSUE THREAD

**Issue by jfbenckhuijsen** [p2/OAuth2#33]
Hi,

Im trying to get your code working but run into the error mentioned in the title. Environment is XCode 7 (new beta)/Swift 2 (running of that branch). ANy ideas how to fix this?

Tnx

**Comment by p2** [comment]
Xcode 7 only supports Swift 2.0, use the `swift-2.0` branch.

**Comment by p2** [comment]
(I do not get that error running off of the swift-2.0 branch – run a "clean")

**Comment by p2** [comment]
(I do not get that error running off of the swift-2.0 branch – make sure you do a "git submodule update" and run a "clean")

**Comment by paul999** [comment]
I am getting the same error, however I am using cocaopods to run the swift-2.0 branch. Any idea how to solve.
This are the errors I have:
/Users/paul/Documents/shoutbox-app-ios/Pods/p2.OAuth2/OAuth2/OAuth2.swift:203:18: Use of unresolved identifier 'Keychain'
/Users/paul/Documents/shoutbox-app-ios/Pods/p2.OAuth2/OAuth2/OAuth2.swift:204:13: Use of unresolved identifier 'ArchiveKey'
/Users/paul/Documents/shoutbox-app-ios/Pods/p2.OAuth2/OAuth2/OAuth2.swift:233:18: Use of unresolved identifier 'Keychain'
/Users/paul/Documents/shoutbox-app-ios/Pods/p2.OAuth2/OAuth2/OAuth2.swift:234:13: Use of unresolved identifier 'ArchiveKey'
/Users/paul/Documents/shoutbox-app-ios/Pods/p2.OAuth2/OAuth2/OAuth2.swift:254:18: Use of unresolved identifier 'Keychain'
/Users/paul/Documents/shoutbox-app-ios/Pods/p2.OAuth2/OAuth2/OAuth2.swift:255:13: Use of unresolved identifier 'ArchiveKey'

**Comment by p2** [comment]
This means the keychain submodule is not present and thus these classes are missing. Not sure how to fix this for CocoaPods, as described above for git you'd do a "git submodule update".

**Comment by vendruscolo** [comment]
You have to use the following syntax, so CocoaPods will set up the submodule correctly:

```
pod 'p2.OAuth2', '~> 2.0.1', :submodules => true
```

(The version thing is optional, at the moment specifying `pod 'p2.OAuth2` would install the latest version)

Maybe it's worth writing in the readme?

**Comment by p2** [comment]
This should not be necessary as the `submodules` flag is supplied in the podspec of the library. At least it is working in the [test app](https://github.com/p2/OAuth2PodApp) without that flag.
