### ISSUE TITLE
Callback when using SwiftUI SceneDelgate

### ISSUE THREAD

**Issue by jcombs-pointblue** [p2/OAuth2#333]
When using iOS13+ and SwiftUI, the callback will not be called if it's in the AppDelgate. You must move it to the SceneDelgate. This callback works there:

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        print("In callback")
      for urlContext in URLContexts {
          let url = urlContext.url
          oauth2.handleRedirectURL(url)
      }
      // URL not auth related, developer should handle it.
    }

This should be added to the docs

**Comment by cacaosteve** [comment]
does this package actually support SwiftUI??? I don't see anything about that

**Comment by ossus-lib** [comment]
Added with #355 . Yes, cacaosteve, you can use this lib if you use SwiftUI in your own app.
