### ISSUE TITLE
Integrate ASWebAuthenticationSession

### ISSUE THREAD

**Issue by gregcotten** [p2/OAuth2#336]
Apple has recently provided a cross-platform UX for handling web service authentication. [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) looks like a great replacement for the WebViewController for modern OS versions (iOS 12+, macOS 10.15+).

More info on the authentication flow can be found [in their docs](https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service).

**Comment by ossus-lib** [comment]
Implemented in #305

**Comment by gregcotten** [comment]
I would generally agree with your closing of the issue, but OAuth2 only supports ASWebAuthenticationSession for iOS, when it actually is supported by Apple on iOS, iPadOS, macOS, and watchOS.
