### ISSUE TITLE
obtain soundcloud token

### ISSUE THREAD

**Issue by longbowww** [p2/OAuth2#35]
I wanted to implement this lib to use the soundcloud SDK but somehow i do not get a valid token back:

my settings:
```Swift    
var oauth2 = OAuth2CodeGrant(settings: [
        "client_id": "xxx",
        "client_secret": "xxx",
        "authorize_uri": "https://soundcloud.com/connect",
        "token_uri": "https://api.soundcloud.com/oauth2/token",
        "scope": "non-expiring",
        "redirect_uris": ["myApp://oauth2"],  
        "keychain": false, 
        "verbose":true,
        "secret_in_body":true //soundcloud requests everything in body
        ])
```
These are the last lines of the logfile 
```
OAuth2: Authorizing against https://api.soundcloud.com/oauth2/token?grant_type=authorization_code&client_secret=xxx&scope=non-expiring&code=xxx&client_id=xxx&redirect_uri=xxx&state=xxx
OAuth2: Exchanging code xxx with redirect xxx for access token at https://api.soundcloud.com/oauth2/token
OAuth2: Did not get access token expiration interval
OAuth2: Did exchange code for access [true] and refresh [false] tokens
OAuth2: Storing tokens to keychain
(Function)
Error Domain=NSCocoaErrorDomain Code=3840 "The operation couldn’t be completed. (Cocoa error 3840.)" (No value.) UserInfo=0x7fe3659573f0 {NSDebugDescription=No value.}
```
SoundCloud API reference can be found here: https://developers.soundcloud.com/docs/api/reference#connect

**Comment by p2** [comment]
You seem to get a token back ("...access [true]..."), that error comes from somewhere else. How do you make the request?

**Comment by longbowww** [comment]
Ok, nvm - I misread the sentence. The request was my fault, because soundcloud obviously wants url encoded params.

---

Unfortunately another thing arose - as SC only issues non-expiring tokens atm it seems that the keychain service wont get/set into keychain :(
```OAuth2: Found access token but no expiration date, discarding```

As I only use your lib for SC and nothing else, i now hacked the if block where it finds the token - to manually set an expiration date of now + 1 month, so it is able to correctly set/get the token and further on make requests incl. the token.

**Comment by p2** [comment]
That would be #27 ;)
