### ISSUE TITLE
Xcode 12.0 Deployment target warning

### ISSUE THREAD

**Issue by telipskiy** [p2/OAuth2#352]
Starting with Xcode 12.0, I get a deployment target warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

Environment

OAuth2: 5.2.0
Xcode Version: 12.0 (12A7209)
Swift Package Manager 5.3.0

**Comment by neoneye** [comment]
Seems to be fixed on [2 Jan 2021 in Package.swift](https://github.com/p2/OAuth2/commit/f544bc39fd19460d62604f350ae5d7166eca72ff#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677e).
