### ISSUE TITLE
Setting ASWebAuthenticationSession.prefersEphemeralWebBrowserSession to true?

### ISSUE THREAD

**Issue by hoereth** [p2/OAuth2#359]
see: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio?language=objc

_The value of this property is false by default._

I would like to set this property to true.

**Comment by EmilBadhAranzMedical** [comment]
Any ideas when this may be released?

**Comment by pballada** [comment]
I was able to set it using the SPM instead of the cocoapods setup.

**Comment by ossus-lib** [comment]
This was added with #366
