### ISSUE TITLE
OAuth fails on WebView after SDK8.4 update

### ISSUE THREAD

**Issue by longbowww** [p2/OAuth2#36]
I got a weird problem since I updated to 8.4 SDK - on a live device running either 8.3. or 8.4 the OAuth will instantly fail on the WebView where you enter your credentials.

The Log:
````
OAuth2: Initialized with client id xxx
OAuth2: No access token, maybe I can refresh
OAuth2: I don't have a refresh token, not trying to refresh
OAuth2: Authorizing against https://soundcloud.com/connect?client_id=xxx&redirect_uri=xxxx%3A%2F%2Fsoundcloud-redirect&scope=non-expiring&response_type=code&state=4A31B29D
OAuth2: No access token, maybe I can refresh
OAuth2: I don't have a refresh token, not trying to refresh
OAuth2: Authorizing against https://soundcloud.com/connect?client_id=xxx&redirect_uri=xxx%3A%2F%2Fsoundcloud-redirect&scope=non-expiring&response_type=code&state=4A31B29D
fatal error: Cannot open authorize URL: file /Users/xxx/xxx/xxx/Pods/p2.OAuth2/OAuth2/OAuth2.swift, line 296
````
Somehow on a simulator, this error does not occur - it will do everything just fine.

**Comment by p2** [comment]
It's working fine for me. It seems to try to open a local file url, do you know where this is coming from?

**Comment by longbowww** [comment]
No Idea, as the authorize Url is the one logged above and also the token_uri/redirect_uri are completely different.

**Comment by p2** [comment]
Which Pod version are you using?

**Comment by philipheinser** [comment]
Got same issue

**Comment by p2** [comment]
I have created a new iPhone app that uses Cocoapods and added it as a [sample app here](https://github.com/p2/OAuth2PodApp). I do not get that error, can use embedded or native login without issues. Can you both look and see what's different between the sample app and yours?

**Comment by p2** [comment]
@longbowww or @philipheinser , does the issue persist?

**Comment by damianesteban** [comment]
I just tried it out on both a device and the simulator, no problems.

**Comment by p2** [comment]
Thanks for confirming, I'll close it.
