### ISSUE TITLE
refresh tokens?

### ISSUE THREAD

**Issue by johnbeynon** [p2/OAuth2#37]
Is it best to call `oauth2.authorize()` before any API calls are made to ensure that if the token has expired then it is refreshed?

puzzled how to use the refresh method?

**Comment by p2** [comment]
You _can_ call `authorize()` before any API call as it will only do anything if it doesn't have an active access token ([see here](http://p2.github.io/OAuth2/Classes/OAuth2.html#/s:FC6OAuth26OAuth29authorizeFS0_FT6paramsGSqGVSs10DictionarySSSS__11autoDismissSb_T_)), you can also only call it e.g. after your app comes to the foreground and you perform the first request. Whatever works best in your case.

There is no need to call the refresh method, it's called automatically from `authorize()` if a) there is no active access token and b) there is a refresh token.
