### ISSUE TITLE
Package.swift has no Package.swift manifest for version 1.2.9 in https://github.com/p2/OAuth2.git

### ISSUE THREAD

**Issue by VladYak71** [p2/OAuth2#375]
After installation  OAuth2 package through package swift manager error occurs: 
Showing All Errors Only
/Package.swift has no Package.swift manifest for version 1.2.9 in https://github.com/p2/OAuth2,git

import OAuth2 produce another error: module not found

**Comment by ZhannySunny** [comment]
> Same error: "/Package.swift has no Package.swift manifest for version 1.2.9 in https://github.com/p2/OAuth2.git", XCode 13.0, project fails to build.
> 
> Edit: works when re-added library with fixed commit "30f46ad74bcbe7013fb340e54f41bc9e6d2ce994"

Hi! I get the same error when adding this library with SPM and Xcode13. Could you please say how to add this library with fixed commit?

**Comment by kanoilki-zincora** [comment]
@ZhannySunny I just used the standard xcode dialog
![image](https://user-images.githubusercontent.com/84045420/144573782-ce6fd76b-280b-4c65-aac3-090d82d626af.png)

**Comment by ossus-lib** [comment]
This should be working fine now.
