### ISSUE TITLE
Unable to compile when the deployment target is set to macOS 10.12

### ISSUE THREAD

**Issue by DominikPalo** [p2/OAuth2#376]
I'm trying to add this framework (the latest version 5.3.2) to my project targeting macOS 10.12. The [README.md](https://github.com/p2/OAuth2/blob/5.3.2/README.md) says:
> OAuth2 requires Xcode 10.2, the built framework can be used on OS X 10.11 or iOS 8 and later.

therefore macOS 10.12 should be compatible. Unfortunately, when I try to compile the project in Xcode 13, it shows an error:

```
Compiling for macOS 10.12, but module 'OAuth2' has a minimum deployment target of macOS 10.13
```

**Comment by ossus-lib** [comment]
Stale issue.
