### ISSUE TITLE
VisionOS issue

### ISSUE THREAD

**Issue by djensenius** [p2/OAuth2#417]
I am getting

`....../OAuth2/Sources/iOS/OAuth2Authorizer+iOS.swift:41:34 Cannot find type 'OAuth2SFViewControllerDelegate' in scope`

with package 5.3.4 when trying to compile with VisionOS.

**Comment by ossus-lib** [comment]
Looks like that happened with #416

**Comment by ossus-lib** [comment]
Should have been fixed with 5.3.5.

**Comment by djensenius** [comment]
Aha, there we go. Unfortunately it's not opening a web view or safari window:

```
[Debug] OAuth2: Starting authorization
[Debug] OAuth2: No access token, checking if a refresh token is available
[Debug] OAuth2: Error refreshing token: I don't have a refresh token, not trying to refresh
[Debug] OAuth2: Opening authorize URL in system browser: https://REMOVED
[Debug] OAuth2: Cannot open authorize URL
```

**Comment by ossus-lib** [comment]
Have you tried using a ASWebAuthenticationSession, what is preferred anyway?

**Comment by djensenius** [comment]
Yep, that's what did it. Thank you!
