### ISSUE TITLE
Not able to get access token of Linkedin

### ISSUE THREAD

**Issue by vhs123** [p2/OAuth2#43]
I am trying to get access token for Linkedin. As mentioned in the [usage section][2], I have created the following code for getting access token. 

      let settingsLinkedin = [
            "client_id": "75afkn125135v14",
            "client_secret": "R5gHlmkRtld4xge4",
            "authorize_uri": "https://www.linkedin.com/uas/oauth2/authorization",
            "token_uri": "https://www.linkedin.com/uas/oauth2/accessToken",
            "scope": "",
            "redirect_uris": ["http://www.dummyredirecturl.com/oauth.aspx"],   // don't forget to register this scheme
            "keychain": false        ] as OAuth2JSON            // the "as" part may or may not be needed
    
    
            let oauth2 = OAuth2CodeGrant(settings: settingsLinkedin)
            oauth2.onAuthorize = { parameters in
                println("Did authorize with parameters: \(parameters)")
            }
            oauth2.onFailure = { error in        // `error` is nil on cancel
                if nil != error {
                    println("Authorization went wrong: \(error!.localizedDescription)")
                }
            }
            
            
            oauth2.authConfig.authorizeEmbedded = true
            oauth2.authConfig.authorizeContext = self.view.window!.rootViewController
            //oauth2.authConfig.ui.backButton = <# UIBarButtonItem(...) #>    // to customize go-back button
            oauth2.authorize()

The problem is that when I use it with Linkedin, it gives following error: 

> Authorization went wrong: missing required parameters, includes an
> invalid parameter value, parameter more than once. : client_secret

When I use [implicit-grant][3], I get following error, even before the user credentials form comes up:

> Authorization went wrong: Invalid redirect URL:
> http://www.dummyredirecturl.com/oauth.aspx?error=unsupported_response_type&error_description=We+only+support+a+response_type+of+%22code%22%2C+but+you+passed+token

Also, when I use the above code for Facebook (of-course after changing credentials) , it works correctly.

  [1]: https://github.com/p2/OAuth2
  [2]: https://github.com/p2/OAuth2/blob/master/README.md#usage
  [3]: https://github.com/p2/OAuth2/blob/master/README.md#implicit-grant

**Comment by p2** [comment]
Sorry I missed this. The second error tells you that you can't use an implicit grant. The first one that LinkedIn doesn't like `client_secret` in the request; what does their documentation say, how do you need to send your secret?

**Comment by vhs123** [comment]
https://developer.linkedin.com/docs/oauth2 says that LinkedIn does require `client_secret`

**Comment by p2** [comment]
Since I don't see a way to set any other redirect-url other than ones starting with `https`, this framework can only be used against LinkedIn via built-in web-view, disabling `SFSafariWebViewController`.

```swift
oauth2.authConfig.authorizeEmbedded = true
oauth2.authConfig.ui.useSafariView = false
```

**Comment by nahouto** [comment]
I am stuck exactly on the same problem : "missing required parameters, includes an invalid parameter value, parameter more than once. : client_id".
I try to login to Linkedin using iOS 9 and swift 2.0 
Did you find a solution ?
Thanks
