### ISSUE TITLE
Side effect with SafariViewController upon logout.

### ISSUE THREAD

**Issue by nickvelloff** [p2/OAuth2#48]
Hello.

Some time ago we discussed (https://github.com/p2/OAuth2/issues/25) a way to clear cookies in the web view in a "log out" scenario. 
This was the snippet that handled that:
``` Swift
let storage = NSHTTPCookieStorage.sharedHTTPCookieStorage()
        for cookie in storage.cookies! {
            storage.deleteCookie(cookie)
        }
        NSUserDefaults.standardUserDefaults()
```

Now with SafariViewController this approach won't work, and I understand why.

My question is do you have any idea of another approach to address the issue?

**Comment by p2** [comment]
I guess you will have to open a Safari view controller at the logout URL of the specific site. Have you tried?

**Comment by nickvelloff** [comment]
That's what I ended up doing. Was just hoping there was magically some other way.

**Comment by p2** [comment]
I don't think so, `SFSafariViewController` is nicely isolated from the app, it's not even possible to intercept loading a URL. I'll close for now, if you find another way comment here again or send a pull request!

**Comment by nickvelloff** [comment]
Sure will thanks for taking a look.
