### ISSUE TITLE
NSURLSession.dataTaskWithRequest() returns empty/200 when no call made

### ISSUE THREAD

**Issue by feydrautha** [p2/OAuth2#55]
NSURLSession.dataTaskWithRequest() is returning empty data and a 200 http code immediately, without actually making an outbound http call to the server using sample code in the readme.   Adjusted the sample code as below and fixed it.  Think it has something to do with async nature of this call?

        let session = NSURLSession.sharedSession()
        let task = session.dataTaskWithRequest(req) {
            (
            let data, let response, let error) in
            
            guard let _:NSData = data, let _:NSURLResponse = response  where error == nil else {
                print("error")
                return
            }
            
            let dataString = NSString(data: data!, encoding: NSUTF8StringEncoding)
            print(dataString)
            
        }
        task.resume()

**Comment by p2** [comment]
The sample code is incomplete, but in general it works that way. Getting empty data and a 200 is valid, just depends on where you send your request to. Here's an actual implementation from the OS X sample app; also very minimal but it returns either data or an error:

https://github.com/p2/OAuth2App/blob/master/OAuth2App/GitHubLoader.swift#L52

If that doesn't clear things up, can you provide your complete code that immediately returns an empty 200 response?

**Comment by feydrautha** [comment]
Initially I had just followed the sample provided in the readme with the distribution...

let req = oauth2.request(forURL: <# resource URL #>)
let session = NSURLSession.sharedSession()
let task = session.dataTaskWithRequest(req) { data, response, error in
    if nil != error {
        // something went wrong
    }
    else {
        // check the response and the data
        // you have just received data with an OAuth2-signed request!
    }
}
task.resume()

**Comment by p2** [comment]
So is it working for you now? Which URL did you try against?
