### ISSUE TITLE
Cancel an ongoing authorization request

### ISSUE THREAD

**Issue by vendruscolo** [p2/OAuth2#58]
Is there a way to cancel an ongoing `authorize()` request?

In the readme it says:

>
```
oauth2.onFailure = { error in        // `error` is nil on cancel
    if nil != error {
        print("Authorization went wrong: \(error!.localizedDescription)")
    }
}
```

But the doc doesn't mention you can actually cancel the request..?
Is it possible?

**Comment by p2** [comment]
A _Cancel_ happens when a user dismisses the login view without logging in. There is currently no way to abort a running request. Maybe this should be added? There also is no check in place whether an `authorize()` is already running, this is probably worth adding.

**Comment by vendruscolo** [comment]
In my opinion it's worth adding this feature. Let me explain: I'm using the code grant flow, and there's no web view involved; my use case is to let the user use the app without a "blocking" authentication: it happens in background and meanwhile he can use the app (hoping that he didn't change the password or something similar).
If the Internet connection is slow, the user can can trigger a logout while oauth is authorizing asynchronously. At that point I'd need to cancel the ongoing request.


– Alessandro Vendruscolo

**Comment by p2** [comment]
I'll add this in one of the next commits, I want to add better support for requests anyway, so this would go hand in hand.

But I'm curious, how are you doing a code grant flow without user interaction? If your app has the username/password it would kinda defeat the purpose of a code grant flow. ;)

**Comment by vendruscolo** [comment]
This project uses OAuth in a _weird_ way: client id and client secret are used in place of username and password, so users insert them in two text fields (managed by the app, so not in a web view); I have no control over this, so I can just accept this API :(
After all, OAuth is used just as _a token provider_.
