### ISSUE TITLE
Checking if user is authorized without authorizing?

### ISSUE THREAD

**Issue by noctivityinc** [p2/OAuth2#62]
Maybe I am missing something but I dont see how to check if the user if authorized without starting the entire OAuth dance.  

When my app is launched, I want to check to see if the user is authorized.  If they are, I would use the access token like normal but if they ARE NOT I want to display a button that says "Sign In" which would THEN trigger the typical OAuth dance.  This seems to be fairly standard for apps (i.e. when you start it up, if they are logged in just keep them logged in without requiring them to click sign in) but Im not sure how to do it.

Thanks.

**Comment by p2** [comment]
Use [`hasUnexpiredAccessToken()`](http://p2.github.io/OAuth2/Classes/OAuth2.html#/s:FC6OAuth26OAuth223hasUnexpiredAccessTokenFS0_FT_Sb) to check whether there is an access token.
