### ISSUE TITLE
Cannot switch users after embed login / logout

### ISSUE THREAD

**Issue by noctivityinc** [p2/OAuth2#64]
I'm using the embedded webview to authorize.  The authorization appears to go fine the first time and everything works great.  The problem is after I logout.  If I login as a DIFFERENT USER when I do an oauth2 request it's pulling from the API as if I was the FIRST authenticated user, not the newly authenticated user!?

I'm not seeing anything odd in the logs except maybe this:
    
    OAuth2: Did exchange code for access [true] and refresh [false] tokens

and my log out routine is pretty simple - it posts a DELETE to a Rails app that logs me out of the app and then forgets the tokens in Oauth and redirects back to the login screen, all of which *appears* to happen correctly with this code: 

    @IBAction func logOutButton(sender: AnyObject) {
        let req = oauth2.request(forURL: NSURL(string: "http://wecora.com/api/v1/sessions")!)
        req.HTTPMethod = "DELETE"
        
        let session = NSURLSession.sharedSession()
        let task = session.dataTaskWithRequest(req) { data, response, error in
            if (error != nil) {
                print("Something went wrong - \(error)")
            } else {
                dispatch_async(dispatch_get_main_queue()) { () -> Void in
                    self.oauth2.forgetTokens()
                    
                    let storyboard = UIStoryboard(name: "Main", bundle: nil)
                    let controller = storyboard.instantiateViewControllerWithIdentifier("loginVC") as! LoginViewController
                    self.presentViewController(controller, animated: true, completion: nil)
                }
            }
        }
        task.resume()
    }

I've tested the API itself to make sure it works and it works fine with other clients (i.e. a test Rails app for example using the same OAuth2 process) so it has to be something with the implementation in my Swift app.

**Comment by p2** [comment]
Yes, this is an issue with the website's session. See #25 .

**Comment by noctivityinc** [comment]
You closed this but I dont think that's the issue.  I just ran this against localhost via a tunnel and noticed something interesting - it was NEVER hitting my server!

So I debugged the crap out of it and found the problem is here:

    func request(url: NSURL, callback: ((data: NSData?, error: NSError?) -> Void)) {
        let req = oauth2.request(forURL: url)
        req.setValue("application/json", forHTTPHeaderField: "Accept")
        
        let session = NSURLSession.sharedSession()
        let task = session.dataTaskWithRequest(req) { data, response, error in
            print("im here!")
            let dataString = NSString(data: data!, encoding: NSUTF8StringEncoding)
            print(dataString)
            callback(data: nil != error ? nil : data, error: error)
        }
        task.resume()
    }
    
When the app first launches I tried clearing the tokens (forgetTokens) and making a request.  Obviously there are no tokens, so we get this:

    Wecora[63988:4174089] Cannot sign request, access token is empty

BUT here's the crazy part - the data variable is STILL POPULATED with the object from the last request!?  And, for whatever reason, I cant seem to remove or change that object no matter what I do.  

In fact even when I reauth via Oauth in the app, and the callback is triggered, and the above request is done it's STILL NOT MAKING THE HTTP REQUEST - it just returns the already existing, in memory objects.

I have no idea what is going on and this clearly looks to be like some kind of issue with the request, so please advise.  If it's on my end, my bad, but this code is direct from the sample all.

**Comment by p2** [comment]
So sounds like a caching issue on the side of `NSURLSession`. You can try setting cache headers on the mutable URL request.

**Comment by noctivityinc** [comment]
Sorry - Im new to this but isn’t that something that needs to happen in your Pod?  Not sure why it would be caching the data on the oath2.request.

Thanks.

On November 16, 2015 at 1:43:34 PM, Pascal Pfiffner (notifications@github.com) wrote:

So sounds like a caching issue on the side of NSURLSession. You can try setting cache headers on the mutable URL request.

**Comment by p2** [comment]
This library does not yet provide nice request handling. OAuth2.request is merely a NSMutableURLRequest that sets `Header: Bearer xxx`. Then it uses standard `NSURLSession` to send the request. `NSURLSession` does caching by default that you can change to your liking. So it's all bare bones.

**Comment by noctivityinc** [comment]
Gotcha.  So given that how can I turn off the cache in the request?  Right now Im about to try adding a randomly generated cache buster to the request url, which seems a bit nuts :)


On November 16, 2015 at 2:13:13 PM, Pascal Pfiffner (notifications@github.com) wrote:

This library does not yet provide nice request handling. OAuth2.request is merely a NSMutableURLRequest that sets Header: Bearer xxx. Then it uses standard NSURLSession to send the request. NSURLSession does caching by default that you can change to your liking. So it's all bare bones.

**Comment by p2** [comment]
Start with [`NSURLSessionConfiguration`](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLSessionConfiguration_class/index.html#//apple_ref/occ/instp/NSURLSessionConfiguration/requestCachePolicy).

Yeah you don't want to do cache busters if there are better ways. :)

**Comment by p2** [comment]
FWIW, I never had this caching issue.

**Comment by noctivityinc** [comment]
Doesn’t make sense.  All I am doing is using your logic to authenticate and then display a view controller with the results of an API call (using SwiftyJSON).  When I tack on the cache buster it seems to work, so not sure why the request would be getting cached by your call.  I tried it in the sample app and had the same thing.  So weird.

Thanks. Time for me to google “ NSURLSessionConfiguration Swift Cache” :)


On November 16, 2015 at 2:20:25 PM, Pascal Pfiffner (notifications@github.com) wrote:

FWIW, I never had this caching issue.

**Comment by noctivityinc** [comment]
Serious progress.  This seems to stop the cache issue.  Enjoy and thanks!

    
    func request(url: NSURL, callback: ((data: NSData?, error: NSError?) -> Void)) {
        let request = oauth2.request(forURL: url)
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        
        let config = NSURLSessionConfiguration.defaultSessionConfiguration()
        config.URLCache = nil
        let session = NSURLSession(configuration: config)
        
        let task : NSURLSessionDataTask = session.dataTaskWithRequest(request, completionHandler: {(data, response, error) in
            print("im here!")
            let dataString = NSString(data: data!, encoding: NSUTF8StringEncoding)
            print(dataString)
            callback(data: nil != error ? nil : data, error: error)
        });
        
        task.resume()
    }

On November 16, 2015 at 2:20:25 PM, Pascal Pfiffner (notifications@github.com) wrote:

FWIW, I never had this caching issue.
