### ISSUE TITLE
SafariViewController Freezes

### ISSUE THREAD

**Issue by bennettl** [p2/OAuth2#65]
Hello,

I'm on an iOS 9 device trying to authenticate with Uber oAuth 'https://login.uber.com/oauth/' , and when my app opens safari view controller it freezes like this:

![img_8571](https://cloud.githubusercontent.com/assets/1672224/11198699/b95a5af2-8c7b-11e5-9da1-20bce55476e5.jpg)

Hitting the refresh button still doesn't load the web page. My wifi connection seems to be working fine.

**Comment by p2** [comment]
I'm not sure why it doesn't display anything; this is iOS, not the framework's doing. In any case, it seems the correct authorize URL is: `https://login.uber.com/oauth/v2/authorize`.
