### ISSUE TITLE
How to use a client side form to pass credentials with p2

### ISSUE THREAD

**Issue by noctivityinc** [p2/OAuth2#66]
I believe it's possible to have a form in the app that asks for the username and password and authenticate it against the OAuth2 app, which I am hoping will solve my login/logout issues, but I cant seem to find any example or detailed code on how we would do this with p2.  Is it possible and, if so, where can we find info on how to proceed?

Also, when you are using p2 to make requests how are you checking with each request if the current access token is still valid?   For example, if an API returns a 401 due to the passed access token being forbidden, how are you detecting this with P2?  Right now, no errors or the like are thrown.

**Comment by p2** [comment]
Yes, you can use the `OAuth2PasswordGrant` to use username and password directly.

You have to check for 401s yourself and take appropriate action, [see here](https://github.com/p2/OAuth2#6-re-authorize).

**Comment by noctivityinc** [comment]
Thanks.  I saw that but where is there documentation or examples on HOW to use your OAuth2PasswordGrant?  

Thx,

J

On November 19, 2015 at 11:20:44 AM, Pascal Pfiffner (notifications@github.com) wrote:

Closed #66.

**Comment by p2** [comment]
Just [set username and password](http://p2.github.io/OAuth2/Classes/OAuth2PasswordGrant.html), then call `authorize()`.
