### ISSUE TITLE
Safari "Cannot Open Page" upon GitHub authentication in iOS 8

### ISSUE THREAD

**Issue by nickvelloff** [p2/OAuth2#7]
Hi.
Thanks for providing this library. Im very close to getting this to work... 
I'm using your GitHub example in iOS and upon authenticating I get "Cannot Open Page" in Safari.
I have properly registered the URL and if I paste it into Safari it opens the app correctly.
My redirect URI is set:
"redirect_uris": ["grid://oauth/callback"],

Im using the latest Xcode 6.1.1 and your master branch (not the Xcode 6.1 tag) but I do not get any build errors so I do not think that is the issue. 

Any idea why Safari is stalling?

![screenshot 2015-01-08 02 27 40](https://cloud.githubusercontent.com/assets/885369/5659305/1248e1a4-96de-11e4-83aa-86a7652a743a.png)
![screenshot 2015-01-08 02 29 10](https://cloud.githubusercontent.com/assets/885369/5659309/28cbf20e-96de-11e4-9e8e-21b038f794c7.png)

**Comment by nickvelloff** [comment]
Never mind... I missed the part that you registered "ppoauthapp" with GitHub so the mismatch with mine hung it up. Thanks again for the lib!

**Comment by p2** [comment]
Good you have it figured out! Maybe I should add a hint about this somewhere.
