### ISSUE TITLE
OAuthPasswordGrant 

### ISSUE THREAD

**Issue by comphealer** [p2/OAuth2#71]
I am connecting to a OAuthPasswordGrant type of OAuth Site. The ClientID and Secret had special characters in them. I was getting Access Denied until I took out the wwwFormURLEncodedString from both of them in the tokenRequest func. If you are going to encode them in base64EncodedStringWithOptions then, I believe,  you do not need to use wwwFormURLEncodedString.

**Comment by p2** [comment]
You're sending id/secret in the Authorize header?

**Comment by p2** [comment]
You closed this, so does it work for you? As [per the spec](http://tools.ietf.org/html/rfc6749#section-2.3.1) the form-urlencoding should be correct:

> The client identifier is encoded using the  "application/x-www-form-urlencoded" encoding algorithm per Appendix B, and the encoded value is used as the username; the client password is encoded using the same algorithm and used as the password.

**Comment by comphealer** [comment]
Yes that is where it ended up. Verbose logging printed 

Adding “Authorization” header as “Basic client-key:client-secret

**Comment by comphealer** [comment]
Also. I did not close this

**Comment by p2** [comment]
So as per spec, the encoding is needed. Which site are you trying to connect to?

**Comment by comphealer** [comment]
It is a private corporate network oauth site. All I know is that It did not work but if I use a C# .net library in windows it works just fine. The base64 encoding takes care of anything you will be send. I will ask the developers of the site what they expect as well.

**Comment by p2** [comment]
I'd have to add an option to suppress url-encoding in such cases, it's possible that the C# library does that. As per the spec, the [url-encoding is correct](http://tools.ietf.org/html/rfc6749#section-2.3.1) (even though it's base-64 encoded). Let me know what the network devs think and I can act accordingly.

**Comment by p2** [comment]
Any update on this?

**Comment by comphealer** [comment]
Nothing yet. Most of them are out for vacation. We will see what they say soon.

**Comment by p2** [comment]
Great, thanks for keeping this updated!
