### ISSUE TITLE
Linkedin : missing required parameters

### ISSUE THREAD

**Issue by nahouto** [p2/OAuth2#73]
Hi, 
I try using this awesome library to signin with Linkedin (on iOS9), but I am stucked in a problem 
"missing required parameters, includes an invalid parameter value, parameter more than once. : client_id".
Could you please help me ?
Thank you

**Comment by p2** [comment]
Can you give me the full log that you're getting from OAuth2 up to this point? Set the `verbose` flag to `true` when instantiating the client.

**Comment by nahouto** [comment]
Thank for your very quick reply :+1: 
Here is my full log

OAuth2: Looking for items in keychain
OAuth2: Initialization finished
OAuth2: No access token, maybe I can refresh
OAuth2: I don't have a refresh token, not trying to refresh
OAuth2: Authorizing against https://www.linkedin.com/uas/oauth2/authorization?client_id=77f56qjbf9tzhi&redirect_uri=http%3A%2F%2Fwww.website.com&scope=r_basicprofile%2Cr_emailaddress&response_type=code&state=7276CC08
2015-12-20 17:59:44.514 OAuth2PodApp[874:337103] XPC connection interrupted
OAuth2: Handling redirect URL http://www.website.com/?code=AQRp6Jk_XFNOAxapx5rvwRw0Hej6OSBsWJ66ad4M2vkfGjSYRxOSU8ck9uGdBBUKNvplnQkACbO5L_QzMWtaR6t1ZZCI9cGutEFEuc71JBd2qrWB8DU&state=7276CC08
OAuth2: Authorizing against https://www.linkedin.com/uas/oauth2/accessToken?code=AQRp6Jk_XFNOAxapx5rvwRw0Hej6OSBsWJ66ad4M2vkfGjSYRxOSU8ck9uGdBBUKNvplnQkACbO5L_QzMWtaR6t1ZZCI9cGutEFEuc71JBd2qrWB8DU&grant_type=authorization_code&redirect_uri=http%3A%2F%2Fwww.website.com
OAuth2: Adding “Authorization” header as “Basic client-key:client-secret”
OAuth2: Exchanging code AQRp6Jk_XFNOAxapx5rvwRw0Hej6OSBsWJ66ad4M2vkfGjSYRxOSU8ck9uGdBBUKNvplnQkACbO5L_QzMWtaR6t1ZZCI9cGutEFEuc71JBd2qrWB8DU for access token at https://www.linkedin.com/uas/oauth2/accessToken
OAuth2: missing required parameters, includes an invalid parameter value, parameter more than once. : client_id
Authorization went wrong: missing required parameters, includes an invalid parameter value, parameter more than once. : client_id

and here are my parameters : 
    var oauth2 = OAuth2CodeGrant(settings: [
        "client_id": "77f56qjbf9tzhi",                        
        "client_secret": "iixQCs2sqkGwlnkB",
        "authorize_uri": "https://www.linkedin.com/uas/oauth2/authorization",
        "token_uri": "https://www.linkedin.com/uas/oauth2/accessToken",
        "redirect_uris": ["http://www.website.com"],          
        "scope": "r_basicprofile,r_emailaddress"
        ] as OAuth2JSON)

Many thanks

**Comment by p2** [comment]
Looks like LinkedIn wants client-id/secret to be in the body, not in the Authorization header. Assuming `oauth2` is your `OAuth2CodeGrant` instance, try this:

```swift
oauth2.authConfig.secretInBody = true
```

**Comment by nahouto** [comment]
Thank you, it seems it makes some progress by adding `oauth2.authConfig.secretInBody = true` (adding `secret_in_body`  in the settings dictionary did not help)

Unfortunately, I now faces to another error : 
`
OAuth2: No token type received, will not use the token
Authorization went wrong: No token type received, will not use the token
`


In the assureCorrectBearerType function, it expects a token_type parameter, but the variable params only have : 
` (p2_OAuth2.OAuth2JSON) $R0 = 2 key/value pairs {
  [0] = {
    key = "expires_in"
    value = 0xb000000004f19ff3 Int64(5183999)
  }
  [1] = {
    key = "access_token"
    value = 0x00007fb22f357238
  }
}
`

Maybe I am not using the right function to login...

Thank you again and sorry for my poor english...

**Comment by p2** [comment]
That means LinkedIn is not returning the token type, which is incorrect. I guess it'll have to be a subclass to handle that exception. You can try to make one yourself (subclass of `OAuth2CodeGrant`) and override `assureCorrectBearerType()` to not do anything. That should do the trick:

```swift
override func assureCorrectBearerType(params: OAuth2JSON) throws {
}
```

No worries about your English, it's fine!

**Comment by nahouto** [comment]
Thank you so much, it works !
OAuth2: Did exchange code for access [true] and refresh [false] tokens
OAuth2: Storing tokens to keychain
Did authorize with parameters: ["expires_in": 5183999, "access_token": AQUs8-R5VPzSXtcIrHlkOvncIlJLuUXcKSoEOKAsPa4z7niNeTQJlAGv5xjMRc1b05td-NTXAjiv34rciu7ZyYMRRug1pXb14oIBp0btgJzKukiAo2E15XJ4qJFkpGawxKitH72pBctpaw1awrE2gPFv_V3gQUz0dcNY_zOD6zHLd-hnBxA]

To sum up, I add 
`oauth2.authConfig.secretInBody = true`
and I bypassed the `assureCorrectBearerType()` function

Now, I will try to retrieve some informations from the user profile. 
Fetching user data failed: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

If I succeed, I will post my complete code for further reference.

**Comment by nahouto** [comment]
Finally, a quick explanation how-to : 

1. Add OAuth2 framework to your project
2. YOU MUST first comment the content of assureCorrectBearerType function (personnaly, I did not manage by overriding OAuth2, XCode throws an error)
3. Create your application in linkedin, and fill up the build id parameter and authorized redirect urls (here, it is https://www.google.com/)

Write this in your ViewController.swift : 
```
let linkedinURL = "https://api.linkedin.com/v1/people/~:(first-name,last-name,public-profile-url,email-address,picture-urls::(original))?oauth2_access_token="
var oauth2 = OAuth2CodeGrant(settings: [
        "client_id": "CLIENTID",                       
        "client_secret": "CLIENTSECRET",
        "authorize_uri": "https://www.linkedin.com/uas/oauth2/authorization",
        "token_uri": "https://www.linkedin.com/uas/oauth2/accessToken",
        "redirect_uris": ["https://www.google.com/"],  // be sure it matches with the authorized redirect urls in Linkedin developer console
        "scope": "r_basicprofile,r_emailaddress",
        "secret_in_body": "true",
        "keychain": false,
    ] as OAuth2JSON)

@IBAction func signInLinkedin(sender: AnyObject) {
        oauth2.authConfig.authorizeEmbedded = true
        oauth2.authConfig.ui.useSafariView = false
        oauth2.authConfig.secretInBody = true
        oauth2.authConfig.authorizeContext = self
        oauth2.forgetTokens()
        oauth2.onAuthorize = { parameters in
                self.didAuthorizeWith(parameters)
        }
        oauth2.onFailure = { error in
                print(error)
        }
        oauth2.authorize()
}

func didAuthorizeWith(parameters: OAuth2JSON) {
        print("Did authorize with parameters: \(parameters)")        
        let accessToken = parameters["access_token"] as? String ?? ""        
        let url = NSURL(string: (self.linkedinURL + accessToken))
        let urlRequest = NSMutableURLRequest(URL: url!)
        urlRequest.setValue("json", forHTTPHeaderField: "x-li-format")
        let config = NSURLSessionConfiguration.defaultSessionConfiguration()
        let session = NSURLSession(configuration: config)
        var task = session.dataTaskWithRequest(urlRequest, completionHandler: myCompletionHandler)
        task.resume()
}
    
func myCompletionHandler(data: NSData?, response: NSURLResponse?, error: NSError?) -> Void {
        guard let responseData = data else {
                print("Error: did not receive data")
                return
        }
        guard error == nil else {
                print(error)
                return
        }
       let post: NSDictionary
        do {
                post = try NSJSONSerialization.JSONObjectWithData(responseData, options: []) as! NSDictionary
        } catch let erreur {
                print(erreur)
                return
        }

        let name = (post["firstName"] as! String) + " " + (post["lastName"] as! String) ?? "ERREUR"
        let mail = post["emailAddress"] as? String ?? "ERREUR"
        if let pictureUrls1 = post["pictureUrls"] as? NSDictionary {
                if let pictureUrls2 = pictureUrls1["values"] as? NSArray {
                        let pictureURL = pictureUrls2[0]
                }
        }
}

```
that's it !

**Comment by p2** [comment]
Cocoa error 3840 is usually JSON parsing error because it's not JSON you've received.

So what you now have is a subclass for LinkedIn. You could override `init(settings: OAuth2JSON)` and set the params in there. You also did disable the Safari view controller, right? Otherwise the callback would not work. So:

```swift
public override init(settings: OAuth2JSON) {
    super.init(settings: settings)
    authConfig.secretInBody = true
    authConfig.authorizeEmbedded = true
    authConfig.ui.useSafariView = false
}
```

If you have that, can you remove the settings from the dict and it works? If so we could make this a default class and add it to the repository.

**Comment by p2** [comment]
We posted at the same time. Looks good, I'll add the subclass.

You can use the following instead of creating a blank URL request. This will return an already-signed `NSMutableURLRequest` than you can then further modify.

```swift
let req = oauth2.request(forURL: <# resource URL #>)
```

**Comment by nahouto** [comment]
Thank you very much !
In this program, I deleted almost all what you write, because I did not fully understand it. Sorry, I am a begineer...

I did not manage to create a subclass of OAuth2CodeGrant to override assureCorrectBearerType. Xcode throws : 
`Method does not override any method from its superclass`

**Comment by p2** [comment]
I have just [added the subclass here](https://github.com/p2/OAuth2/blob/develop/Sources/Base/OAuth2CodeGrantLinkedIn.swift), will be available with the next release. You can copy this file to your project if you like.

**Comment by nahouto** [comment]
Woaw ! Génial !
Thank you !!!
