### ISSUE TITLE
A little mistake about Cocoapods

### ISSUE THREAD

**Issue by nahouto** [p2/OAuth2#74]
In the readme, it is written
 (use `p2_OAuth2` if you installed via CocoaPods) 

but in fact the correct pod seems to be
 (use `p2.OAuth2` if you installed via CocoaPods) 

Thanks a lot for this awesome library

**Comment by p2** [comment]
You are right that the library name is **p2.OAuth2** but the period is not valid in a pod name, so it gets replaced with an underscore. You can [see its usage](https://github.com/p2/OAuth2PodApp/blob/master/OAuth2PodApp/ViewController.swift) in the `OAuth2PodApp` example; at the top is the import.

Glad you like it!
