### ISSUE TITLE
After "Refresh token" save new token in keychain.

### ISSUE THREAD

**Issue by whitefoxy** [p2/OAuth2#75]
Hey again,

I have found a one more feature which is not implemented. In my API, after requesting new `access_token` from **RefreshTokenGrant** it returns new refresh_token. Such a system also exists in other API's.

Here is JSON response:
```
{
  "access_token": "Hbr8Ecwh5W23GJGc2wgAkRZM965vo8mFlIK22rXN",
  "token_type": "Bearer",
  "expires_in": 86400,
  "refresh_token": "UzS7SgUCVfyPkG0Av8sEKP05RU4jqfOIlsFG9a9t"
}
```

I think that you just need to compare stored `refresh_token` in keychain and in a response, if the are difference, then update it.

**Comment by p2** [comment]
The refresh token is always updated when the response is parsed, are you saying the refresh token is not stored to keychain?

https://github.com/p2/OAuth2/blob/master/OAuth2/OAuth2ClientConfig.swift#L116

**Comment by whitefoxy** [comment]
Yes, they are not updated in keychain.

**Comment by p2** [comment]
Can you show the log? In your previous issue you had `keychain: false`, make sure it's turned on.

**Comment by whitefoxy** [comment]
Step 1 (Authorization):
```
OAuth2: Looking for items in keychain
OAuth2: Initialization finished
OAuth2: No access token, maybe I can refresh
OAuth2: I don't have a refresh token, not trying to refresh
OAuth2: No access token, requesting a new one
OAuth2: Adding “client_id” and “client_secret” to request body
OAuth2: Requesting new access token from Optional("http://example.com/oauth/access_token")
OAuth2: Did get access token [true]
OAuth2: Storing tokens to keychain
Optional("akNGPujw9j9CbbC04dWxkGRBbRZEClIceJa4g2q3") <-- This is refresh_token
```

Step 2 (Token expired, Close & Reopen the app):
```
OAuth2: Looking for items in keychain
OAuth2: Found access token, valid until 2015-12-22 19:13:52 +0000
OAuth2: Found refresh token
OAuth2: Initialization finished
we need to refresh
OAuth2: Authorizing against http://example.com/oauth/access_token?refresh_token=akNGPujw9j9CbbC04dWxkGRBbRZEClIceJa4g2q3&grant_type=refresh_token&client_id=test&client_secret=test
OAuth2: Using refresh token to receive access token from http://example.com/oauth/access_token
OAuth2: Did use refresh token for access token [true]
```

Step 3 (Token expired, Close & Reopen the app (Second time))
```
OAuth2: Looking for items in keychain
OAuth2: Found access token, valid until 2015-12-22 19:13:52 +0000
OAuth2: Found refresh token
OAuth2: Initialization finished
we need to refresh
OAuth2: Authorizing against http://example.com/oauth/access_token?refresh_token= akNGPujw9j9CbbC04dWxkGRBbRZEClIceJa4g2q3&grant_type=refresh_token&client_id=test&client_secret=test
OAuth2: Using refresh token to receive access token from http://example.com/oauth/access_token
OAuth2: Error parsing refreshed access token: The refresh token is invalid.
OAuth2: Forgetting tokens and removing them from keychain
```

Refresh is called from function `doRefreshToken()`.

Now I don't have `keychain: false`, all is correct. Don't look that I am using `http` scheme, I just turned your exception off and it will be good if you will add this ability from config, for example, when verbose is true, then `http` scheme will work too. Because I am developing my app and Web and in current state SSL is not enable on the server, I will enable it later.
