### ISSUE TITLE
After Cancel, the previous previous View Controller flashes

### ISSUE THREAD

**Issue by nahouto** [p2/OAuth2#76]
Hi,

I spent one day to understand this problem and I didn't succeed.

When I perform an embedded authorization and press on Cancel, the penultimate view controller is briefly shown, then the previous view controller is loaded.
How can I prevent this behavior ?

Thank you !

Here is my code : 

        // parameters for Linkedin
        linkedinURL = "https://api.linkedin.com/v1/people/~:(first-name,last-name,public-profile-url,email-address,picture-urls::(original))?oauth2_access_token="
        linkedinSettings = [
            "client_id": "---",
            "client_secret": "---",
            "authorize_uri": "https://www.linkedin.com/uas/oauth2/authorization",
            "token_uri": "https://www.linkedin.com/uas/oauth2/accessToken",
            "redirect_uris": ["http://google.com"],
            "scope": "r_basicprofile,r_emailaddress", // permissions required from linkedin
            "secret_in_body": "true",
            "keychain": false,
            ]
        
        // delay before moving to next view (in seconds)
        segueDelay = 2

    func continueNextView() {
        self.performSegueWithIdentifier("successfulLogIn", sender: self)
    }
    
    // enable all the buttons and hide the activity indicator
    func activateScreen() {
        activityIndicator.stopAnimating()
        signInLinkedin.enabled = true
    }
    
    // disable all the buttons and animate the activity indicator
    func deactivateScreen() {
        activityIndicator.startAnimating()
        signInLinkedin.enabled = false
    }
    // For Linkedin API
    @IBAction func signInLinkedinAPI(sender: AnyObject) {
        self.deactivateScreen()
        
        let oauth2 = OAuth2CodeGrant(settings: linkedinSettings)
        
        oauth2.authConfig.authorizeEmbedded = true
        oauth2.authConfig.ui.useSafariView = false
        oauth2.authConfig.secretInBody = true
        oauth2.authConfig.authorizeContext = self
        //oauth2.authConfig.ui.backButton = UIBarButtonItem(title: "Back", style: .Plain, target: self, action: nil)
        //oauth2.forgetTokens()
        oauth2.onFailure = { error in
            print(error)
            self.activateScreen()
        }
        
        oauth2.onAuthorize = { parameters in
            let accessToken = parameters["access_token"] as? String ?? ""
            let url = NSURL(string: (self.linkedinURL + accessToken))
            let urlRequest = NSMutableURLRequest(URL: url!)
            urlRequest.setValue("json", forHTTPHeaderField: "x-li-format")
            let config = NSURLSessionConfiguration.defaultSessionConfiguration()
            let session = NSURLSession(configuration: config)
            let task = session.dataTaskWithRequest(urlRequest, completionHandler: { (data: NSData?, response: NSURLResponse?, error: NSError?) in
                guard let responseData = data else {
                    print("Error : did not recieve data ")
                    print(error)
                    self.activateScreen()
                    return
                }
                guard error == nil else {
                    print(error)
                    self.activateScreen()
                    return
                }
                
                let post: NSDictionary
                do {
                    post = try NSJSONSerialization.JSONObjectWithData(responseData, options: []) as! NSDictionary
                } catch let error {
                    print("Error in parsing to JSON : ") ; print(error)
                    self.activateScreen()
                    return
                }
                
                let name = (post["firstName"] as! String) + " " + (post["lastName"] as! String) ?? "ERREUR"
                let mail = post["emailAddress"] as? String ?? "ERREUR"
                let userType = "linkedin"
                
                var pictureUrls3  = ""
                if let pictureUrls1 = post["pictureUrls"] as? NSDictionary, pictureUrls2 = pictureUrls1["values"] as? NSArray {
                    pictureUrls3 = pictureUrls2[0] as! String
                }
                let pictureURL = NSURL(string:pictureUrls3)! ?? NSURL()
                
                self.currentUser.update(name, pictureURL: pictureURL, userType: userType, emailAdress: mail)
                
                dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(self.segueDelay * Double(NSEC_PER_SEC))), dispatch_get_main_queue(), { () -> Void in
                    self.continueNextView()
                    self.activateScreen()
                })
            })
            task.resume()
        }
        oauth2.authorize()
    }

**Comment by p2** [comment]
If you set `oauth2.verbose = true` (or set `verbose` to true in your settings dict), you should see the steps that are happening. What is it doing before/when you hit cancel? And which controller do you mean with the penultimate view controller?

**Comment by nahouto** [comment]
Here is my verbose : 

OAuth2: No access token, maybe I can refresh
OAuth2: I don't have a refresh token, not trying to refresh
OAuth2: Authorizing against https://www.linkedin.com/uas/oauth2/authorization?client_id=---&redirect_uri=http%3A%2F%2Fgoogle.com&scope=r_basicprofile%2Cr_emailaddress&response_type=code&state=4459E50F
Error from oauth2.onFailure: nil

I set a viewController firstVC and then the login viewController SignInVC.
When I hit Cancel, it briefly shows firstVC and then shows SignInVC

**Comment by p2** [comment]
I have just tested against the [OAuth2 Pod Test App](https://github.com/p2/OAuth2PodApp) and am getting the same logging as you do, but correct dismiss behavior (p2.OAuth2 v2.1.1). Can you check if your own methods, like `continueNextView()`, are called at one point by setting breakpoints?

**Comment by nahouto** [comment]
After many tests, I did not find anything suspicious there...
In OAuth2WebViewController, I change the dismiss function 
`self.dismissViewControllerAnimated(animated, completion: nil)`
instead of
 `presentingViewController?.dismissViewControllerAnimated(animated, completion: nil)`
and it works correctly.

Maybe it is related to the way (kind of segue) I present my SignIn View Controller

Anyway, thank you very much for your help !

**Comment by p2** [comment]
Awesome, thanks for figuring that out, rolled into `2.1.3`!

**Comment by nahouto** [comment]
Thank you very much
