### ISSUE TITLE
SFSafariViewController logout question

### ISSUE THREAD

**Issue by nickvelloff** [p2/OAuth2#77]
Hello again.
When you say:
> With the newer SFSafariViewController, or logins performed in the browser, it's probably best to directly open the logout page so the user sees the logout happen.

Do you mean that there is a specific logout URL for providers like GitHub and Google? Perhaps I missed them and need to look again, but I want to confirm that is what you mean.

**Comment by p2** [comment]
Yes, this is what I meant.

The problem is that when you login with Safari(ViewController), it acts just like a browser, setting session cookies, local storage and what not. You cannot programmatically remove them since _a)_ you don't know what the website is doing and _b)_ you don't have access anyway.

So the only option is to log out the user as if you would log out from the website itself. For GitHub for example you can just open `https://github.com/logout`.

**Comment by nickvelloff** [comment]
We actually worked on this:
```
let storage = NSHTTPCookieStorage.sharedHTTPCookieStorage()
storage.cookies?.forEach() { storage.deleteCookie($0) }
```
some time ago _in an issue far far way_, and moving to `SFSafariViewController` was something I was avoiding for this reason. 

Again - appreciate your work on this. 

Th

**Comment by p2** [comment]
Yes, I remember that but it [only works](https://github.com/p2/OAuth2#7-logout) for the built-in web view controller.

**Comment by nickvelloff** [comment]
Yup exactly. That was the blocker moving to `SFSafariViewController` I mentioned. But perhaps the logout URL for GitHub and Google (Facebook and Twitter I handle with system config) may allow me to migrate to 'SFSafariViewController' after all if the flow is not confusing for the user.

**Comment by p2** [comment]
Implementation-wise there's not much incentive to switch away from the custom web view controller. Security-wise it's much cleaner as it's a _true_ OAuth flow, with no chance for the developer to get at the user's credentials. This might become more important with future iOS updates and/or users becoming more sensible to these kinds of things. It might also never matter... :)

**Comment by nickvelloff** [comment]
Perhaps the true idea of the OAuth flow is not ever to allow the user to log out system wide with a single client, this logging out all other apps currently authenticated. It's tricky on mobile because the practical user story is "hey I want to log in with my other Google account", but in reality will any user ever really want to do that (other than me testing and hammering my app)? :smile:

**Comment by p2** [comment]
Yes, I also think that regular users rarely need to log out. But if they do that does not affect the access/refresh tokens other apps already have, so might not be much of an issue after all. 👍🏼
