### ISSUE TITLE
Embedded auth on OSX

### ISSUE THREAD

**Issue by rboisjoly** [p2/OAuth2#80]
Hi

Looking to use this for Oauth2 in a Mac OS X app, but would prefer an embedded version using WKWebView since my app is already an embedded web app... And switching to Safari for oauth is not very elegant.

What are the chances of seeing this implemented soon? I see the stubs are there in the code...

Thanks!

**Comment by p2** [comment]
If you fork the repo and implement this for OS X I'd be very happy to accept a pull request! Please use the `develop` branch, things have changed a bit.

This could then be added to the OS X sample app, would be very cool.

**Comment by rboisjoly** [comment]
I'd love to, I'm just afraid I don't have the skills. I've been trying on my own with no success which is why I'm looking for a solution. But I'll explore how you do it in iOS and see if I can use the same concepts as with the SFWebView and try to apply them. If I feel I can get somewhere, I'll fork. Thanks for the quick response!

**Comment by p2** [comment]
I haven't built more advanced OS X apps in a while, that's why I haven't gotten to it as well. If you take a look at the iOS code it might be easy enough, translate SFSafariWebView to WKWebView.

If you feel like it, give it a shot and update here. Maybe I can even give some input.

**Comment by rboisjoly** [comment]
I'll take up the challenge then :-) looking forward to collaborating

Renaud

Envoyé de mon iPhone

**Comment by rboisjoly** [comment]
Hi! I've made some progress. You can look at my fork? I'm not super-efficient with granular commits yet, but I'm trying to improve.
I've added a NSViewController subclass and nib to do something akin to the SafariWebView version, but it shouldn't need to use the open url concept. I've managed to get the token, but then I'm unsure how to continue from there after success. The closure (onAuthorize) doesn't get called... not sure why. My scenario only requires me to get the token, which I will then pass along to a Javascript method, so I'm almost there. Just trying to follow your model as best as I can to make this useful to others.

I've had to make oAuth2 require 10.0 for now, because there is no alternative to WKWebView implemented... there must be a better way to define things for 10.9 support and require 10.10 only for this, but at one point I couldn't figure out how to make it work ... feel free to comment and suggest other ways. Once that is done, I'll submit a pull request, or would it be more appropriate to do that and comment there. Not an advanced git/github user by any means.

Thanks again!

**Comment by rboisjoly** [comment]
Just looked at some of the code in oAuth2WebViewController that I had missed! I can always use the same technique and do the openUrl approach... then the patterns would match and it will work fine. Let me do that and I'll get back to you.

**Comment by rboisjoly** [comment]
I think I've got it working, without any opening of URL's, simply the same way or close to what you did in the iOS embedded WebView version. Closure is now called and all, so I'm good to go with this!

Will do a pull request

**Comment by p2** [comment]
Implemented via #84. `develop` branch contains some enhancements.
