### ISSUE TITLE
Not working with Instagram

### ISSUE THREAD

**Issue by bennettl** [p2/OAuth2#81]
I've set up this dictionary
```
let settings = [
    "client_id": "abc123",
    "client_secret": "abc123",
    "authorize_uri": "https://api.instagram.com/oauth/authorize",
    "token_uri": "https://api.instagram.com/oauth/access_token",
    "response_type": "code",
    "redirect_uris": ["myapp://oauth/callback"],
    "keychain": false,
    "title": "InstagramViwer" 
    ] as OAuth2JSON

```
I got the callback url as `myapp://oauth/callback?code=abc123&state=xyz123`, and let oauth2 handle the URL, but I received this error in my `onFailure` property `No token type received, will not use the token`. Any ideas?

**Comment by p2** [comment]
This means Instagram does not return `token_type`, similar to LinkedIn and Bitly. I've added the subclass `OAuth2NoTokenType` to the _develop_ branch that you can use. If you're not using git, you can easily create your own subclass:

```swift
public class OAuth2CodeGrantNoTokenType: OAuth2CodeGrant {
	
	public override init(settings: OAuth2JSON) {
		super.init(settings: settings)
	}
	
	override func assureCorrectBearerType(params: OAuth2JSON) throws {
	}
}
```

**Comment by bennettl** [comment]
Tried downloading with 

```
pod 'p2.OAuth2', git: 'https://github.com/p2/OAuth2.git', branch: 'develop'
```

It said class 'OAuth2CodeGrantNoTokenType' does not exist. Tried creating my own subclass, it said 'assureCorrectBearerType' no override method from its superclass

**Comment by p2** [comment]
Ah of course, that method is not public. I've updated the `Podfile` for the develop branch, can you try to install again?

**Comment by bennettl** [comment]
I was able to use the class, web view open, I click "Allow", redirected with URL:

```
url myapp://oauth/callback?code=abc123&state=xyz123
```

I handle the errors with:

```
oauth2.onFailure = { error in       
            if let err = error {
                print("error \(err)")
            }
        }
```

And saw this on the console

```
error Optional(400)
```

**Comment by p2** [comment]
So that means invalid request. Hmm, according to [their dev docs](https://www.instagram.com/developer/authentication/) it looks like their code exchange is by the book. If you set `oauth2.verbose = true` then your exchange will be logged. Can you turn that on and see if the error is reported to the console?

**Comment by bennettl** [comment]
Got it. The issue is that the authorization code is passed in the HTTP header, when Instagram expects it in the body for an HTTP Post request. I've set "secret_in_body" to be true and it worked. Might want to update your docs as well for Instagram =).

**Comment by p2** [comment]
Aaah very good, thanks for the update! Yes I haven't tried Instagram myself; I'll update the readme. 👍🏼
