### ISSUE TITLE
use CocoaLumberjack for logging

### ISSUE THREAD

**Issue by tompson** [p2/OAuth2#82]
In most of our apps we are using CocoaLumberjack for logging. When using p2.OAuth2 I have the problem that those logs are not written into our log files.

Have you considered using a log framework like CocoaLumberjack?

**Comment by p2** [comment]
CocoaLumberjack is Objective-C, so not a good candidate since I don't want to depend on CocoaPods. I don't use logging frameworks so am not thinking about using one near term. If you have ideas on how this could be an optional hook let me know!

**Comment by tompson** [comment]
There is branch CocoaLumberjack/Swift too which works very well in Swift projects.

Currently I just made the changes locally for my test setup. If there was a way to redirect NSLog output to  CocoaLumberbjack there would be no need to make this library depend on it.

**Comment by p2** [comment]
Currently I'm simply using Swift's `print()`. That method though accepts an argument declaring the output stream, defaulting to stdout.

Would it work for you if you would be able to specify the output stream on the `OAuth2XY` instance and logging would be redirected there? Meaning does CocoaLumberjack allow you to retrieve the `OutputStreamType` in use?

**Comment by tompson** [comment]
I thought of something similar, will look into that and let you know, thanks!

**Comment by p2** [comment]
Did you make progress on the logging front?

**Comment by tompson** [comment]
I just made change in my fork to get more log for tackling issue #79

**Comment by p2** [comment]
@tompson I have now added a simple logger protocol (latest develop, should be on 2.2.7). The logger can be assigned to `oauth2.logger`, should be easy enough to create one that interfaces with CocoaLumberjack. I'll close this issue, re-open if this does not work for you!
