### ISSUE TITLE
Extract SwiftKeychain to Pod for all plattforms

### ISSUE THREAD

**Issue by ddengler** [p2/OAuth2#87]
This would be an easy task, if we could get a new release of the yankodimitrov/SwiftKeychain pod. SwiftKeychain itself seems to be fully compatible with OSX and tvOS. Only the podspec has to be updated (for now). Also see #70 

The project on the other hand seems to be dead. Future issues might block your project. How do you intend to proceed?

**Comment by p2** [comment]
Since I don't use CocoaPods myself the submodule works perfectly fine for me. Maybe it's better to not rely on a separate Pod on all platforms to be consistent and just include the sources?

**Comment by ddengler** [comment]
I am currently testing a fork of SwiftKeychain. If it works out I will open a pull request and hopefully get this accepted into the keychain lib (also with updated swift syntax). If not, copying the code might be an acceptable quick fix.

**Comment by ddengler** [comment]
Got this merged into SwiftKeychain. Hope there will be an official release soon.

**Comment by p2** [comment]
Sweet! 👍🏼

**Comment by ddengler** [comment]
yay it has been released https://github.com/yankodimitrov/SwiftKeychain/releases/tag/v1.0.0 
I will look into it again. Maybe I can also add Carthage support on the way

**Comment by ddengler** [comment]
this is coupled with #70 right now as we look mostly into the tvOS support. let me know if we need to extract this. I changed/updated the submodule to the v1.0.0 tag.

**Comment by p2** [comment]
Extracting to Pod for all platforms is great **if one installs via CocoaPods**. But the project must still compile without CocoaPods, i.e. open OAuth2.xcodeproj and hit <key>CMD</key> + <key>U</key>.

**Comment by ddengler** [comment]
I am aware of that and will fix this. I just needed a way to test this quickly.

**Comment by p2** [comment]
Ok great! I misunderstood your "let me know if we need to extract this" question.

**Comment by ddengler** [comment]
With the merge of #70 this is resolved.
