### ISSUE TITLE
Crashlytics reporting crashes on webView.goBack()

### ISSUE THREAD

**Issue by aadjemonkeyrock** [p2/OAuth2#88]
Using a standard implementation, but getting occasional Crashlytics crashes on OAuth2WebViewController.swift -> webView.goBack() line 161.

Unfortunately not able to reproduce the situation. Anybody having the same?

**Comment by p2** [comment]
Can you post the stack trace?

**Comment by aadjemonkeyrock** [comment]
That is the problem, I don't have a stack trace, only the Crashlytics log

<img width="957" alt="fabric" src="https://cloud.githubusercontent.com/assets/956176/12848696/bb149dbe-cc1b-11e5-9886-8e3c04a48ea1.png">

**Comment by p2** [comment]
Not terribly helpful, but the `webView` property is the only think I remember ever making _implicitly unwrapped_. So it could be that the web view got deallocated, then the `goBack()` method is called.

I'll make it a proper optional. Damn you implicit unwrapping!
