### ISSUE TITLE
Setting the cache policy - Question

### ISSUE THREAD

**Issue by tylerswartz** [p2/OAuth2#89]
Hi - I'm having some trouble with an API and I think I'm getting a local cache back from a request instead of updated information from the API. In `OAuth2Request.swift` I see the convenience initializer with a cache policy. What I'd like the cache policy to be is `ReloadIgnoringLocalCacheData`, but I can't figure out how to properly set that in the initializer without getting an undeclared type error. I'm new to Swift, so I'm not sure if this change is even a smart thing to do with OAuth2. Does OAuth2 rely on using the local cache for some requests? What's the best way to set the cache policy?

**Comment by p2** [comment]
Oh, apparently I haven't updated the docs. There was a similar request recently (issue #86) and there is now a `sessionConfiguration` property on `OAuth2Base`, the base class for all flows. You can assign your own `NSURLSessionConfiguration` and it will be used from then on.

You can also use `sessionDelegate` to assign a `NSURLSessionDelegate` to get more control over requests.

**Comment by tylerswartz** [comment]
Thanks for the quick response @p2! If I understand correctly, by adding the following line to the `URLSession` function I can specify the cache policy. Or do I need to include more?

`config.requestCachePolicy = NSURLRequestCachePolicy.ReloadIgnoringLocalCacheData`

So now the function looks like this:
```
func URLSession() -> NSURLSession {
		if nil == session {
			if let delegate = sessionDelegate {
				let config = NSURLSessionConfiguration.defaultSessionConfiguration()
                config.requestCachePolicy = NSURLRequestCachePolicy.ReloadIgnoringLocalCacheData
				session = NSURLSession(configuration: config, delegate: delegate, delegateQueue: nil)
			}
			else {
				session = NSURLSession.sharedSession()
			}
		}
		return session!
	}
```

After adding this line, I tried my Uber API call again and it's still returning the cached response.

**Comment by p2** [comment]
You do not need to alter the OAuth2 code at all. Just do something like this:

```swift
let config = NSURLSessionConfiguration.defaultSessionConfiguration()
config.requestCachePolicy = NSURLRequestCachePolicy.ReloadIgnoringLocalCacheData

let oauth = OAuth2CodeGrant(...)
oauth.sessionConfiguration = config

oauth.authorize() { ... }

oauth2.request(forURL: <# NSURL #>)
```

I have not yet had the caching issue (but others have), let me know how that goes!

**Comment by tylerswartz** [comment]
Oh, I see thanks. I was working off 2.0.0, just updated to the current version and set the sessionConfiguration. Still seeing a cached response, but I'll play around with it a bit more. Thanks for the help

**Comment by p2** [comment]
That would be awesome. Are you seeing cached requests for authorization or data requests? If you can try the latter with your own `NSURLSession` that'd be cool.

**Comment by tylerswartz** [comment]
I'm seeing cached responses for data requests. The authorization is working well.

**Comment by tylerswartz** [comment]
Got it working! When I tried setting the cache policy in `oauth.sessionConfiguration` I was still seeing the cached response. What I did was ALSO specify the cache policy when I make the request, like so:

```
let urlPath = "https://sandbox-api.uber.com/v1/requests/\(uberRequestId)"
        let appDelegate = UIApplication.sharedApplication().delegate as! AppDelegate
        
        guard let endpoint = NSURL(string: urlPath) else { print("Error creating endpoint");return }
        let request = appDelegate.oauth.request(forURL: NSURL(string:urlPath)!)
        request.setValue("application/json; charset=utf-8", forHTTPHeaderField: "Content-Type")
        request.cachePolicy = NSURLRequestCachePolicy.ReloadIgnoringCacheData
        request.HTTPMethod = "GET"
        
        //get ride status response from uber.
        appDelegate.oauth.session.dataTaskWithRequest(request) { (data, response, error) -> Void in
            do {
                guard let dat = data else { throw JSONError.NoData }
                
                let result = try NSJSONSerialization.JSONObjectWithData(dat, options: NSJSONReadingOptions.MutableContainers)
                
                print(result)
                
            } catch let error as JSONError {
                print(error.rawValue)
                print("ERROR NEEDS TO BE HANDLED. NO RETURN FROM UBER API")
            } catch {
                print(error)
                print("ERROR NEEDS TO BE HANDLED. NO RETURN FROM UBER API")
            }
        }.resume()

```

**Comment by p2** [comment]
Great! Have you tried ONLY setting the cache policy on the request?

**Comment by tylerswartz** [comment]
No I have not tried that. Do you want me to give that a try? Would that help you on anything?

**Comment by p2** [comment]
Would be interesting to know which combinations work. I haven't had this issue with other APIs so can't test myself.

**Comment by tylerswartz** [comment]
sure, I'm happy to try the other combination. I'll do it tonight after work and report back!

**Comment by p2** [comment]
Very cool, thanks a lot and no rush!

**Comment by tylerswartz** [comment]
When I removed the config settings from my AppDelegate the Uber API still worked. It appears that the only way my app ignored the local cache was setting the cache policy for each request.

**Comment by tylerswartz** [comment]
I also put in a pull request to update the Readme that explains this Uber peculiarity. Feel free to expand on it if you think it need more details. I've been in the weeds with this caching too long  😊

**Comment by p2** [comment]
Oh; feel free to ignore my 3 requests then, I can do it myself – unless you get to it before tomorrow when I'll do it.

In any case, thanks a lot for testing, that should help a lot of others as well!!
