### ISSUE TITLE
Error during JSON serialization with Facebook authentication

### ISSUE THREAD

**Issue by rjourde** [p2/OAuth2#9]
Performed a OAuth2CodeGrant operation with Facebook settings:
~~~ swift
let settings = [
            "client_id": "xxxx",
            "client_secret": "xxxx",
            "authorize_uri": "https://graph.facebook.com/oauth/authorize",
            "token_uri": "https://graph.facebook.com/oauth/access_token",
            "scope": "email",
            "redirect_uris": ["domain name"],
        ]
~~~

And got the error `Authorization went wrong: The operation couldn’t be completed. (Cocoa error 3840.)` after the JSONObjectWithData method has been called:
~~~ swift
let json = NSJSONSerialization.JSONObjectWithData(data, options: nil, error: &finalError) as? NSDictionary
~~~

**Comment by p2** [comment]
You can create a String from that `data` object to see what you're getting back. I don't have Facebook so can't test.

    let str = NSString(data: data, encoding: NSUTF8StringEncoding)
    println("--> \(str)")

**Comment by rjourde** [comment]
String representation of the response is `Optional(access_token=xxxxx)` which explains why the JSON serialization is failing.

**Comment by p2** [comment]
I have just pushed a Facebook-specific subclass to the `develop` branch, can you check out that branch and use `OAuth2CodeGrantFacebook` instead of the standard code grant class, and test if it works?

**Comment by rjourde** [comment]
I just tested your change and it works well except that 'OAuth2CodeGrantFacebook' class has not been declared as public. The 'onAuthorize' closure is reached and the 'parameters' dictionary contains the access token.
Thanks for your quick reply.

**Comment by p2** [comment]
Very good, thanks for testing! I'll fix the `public` thing and merge. 👍
