### ISSUE TITLE
weird google permission ?

### ISSUE THREAD

**Issue by tirrorex** [p2/OAuth2#91]
Hello, implemented the google oauth, app is asking for access without connection (offline access), i followed basic example and i didn't see anything about it, is it coming from the code underneath?
If so could you point how is it possible to disable this? Since i do not need this and that could scared some users. thanks

**Comment by p2** [comment]
This means that you're also getting a `refresh_token`. Apparently, this is returned by default, [see here](https://developers.google.com/identity/protocols/OAuth2InstalledApp). I don't know how to disable refresh tokens.

**Comment by tirrorex** [comment]
Thanks for the quick reply, gonna check on google then, have a good day

**Comment by p2** [comment]
Great 👍🏼
