### ISSUE TITLE
accessMode not configurable for tokens stored in keychain 

### ISSUE THREAD

**Issue by tompson** [p2/OAuth2#92]
the default mode in wich SwiftKeychain saves stuff to the Keychain is `kSecAttrAccessibleWhenUnlocked` which means they can not be read when the device is unlocked. Since my app needs to access them when doing a refresh in the background I need to change this somehow.

The constructor of the `SwiftKeychain` class `Keychain` would allow that:

```
public init(serviceName name: String, accessMode: NSString = kSecAttrAccessibleWhenUnlocked, group: String? = nil) {

   self.accessMode = accessMode

   serviceName = name
   accessGroup = group
}
```

it has to be possible to access the store tokens while the device is unlocked

**Comment by tompson** [comment]
I tried to call the Keychain with `kSecAttrAccessibleAlways` but that lead to

`Failed to store to keychain: swift.keychain.error.domain-Fehler -25299`

maybe a Problem in `SwiftKeychain`?

**Comment by p2** [comment]
-25299 is the error `errSecDuplicateItem`, basically the inverse of the _update_ ➔ _not-found_ ➔ _add_ check that was implemented in SwiftKeychain a while ago. Should probably check for that in the `add()` method and, if this error occurs, fall back to an `update()` operation.

**Comment by tompson** [comment]
I found that error code description too and read some articles like http://useyourloaf.com/blog/keychain-duplicate-item-when-adding-password/ about it

the strange thing is that there this happens even after all previous tokens were deleted by calling forget tokens and it only happens when setting `kSecAttrAccessibleAlways`

**Comment by p2** [comment]
Should be easy to expose on `authConfig` (in `OAuth2AuthConfig`), defaulting to the current mode since it's suitable for most use-cases it seems and it's always good to default to more secure settings.
