### ISSUE TITLE
Copy and paste modifier keys don't work

### ISSUE THREAD

**Issue by matthewcheok** [p2/OAuth2#93]
I can't seem to paste into the login page on OSX. Any ideas what's happening here?

**Comment by p2** [comment]
Assuming you mean the built-in login screen; pasting seems to work for me when testing with [OAuth2App](https://github.com/p2/OAuth2App).

**Comment by matthewcheok** [comment]
Ah I'm presenting this in as a modal without a menu bar (and edit menu.)
