### ISSUE TITLE
Weird layout in WKWebView

### ISSUE THREAD

**Issue by matthewcheok** [p2/OAuth2#94]
![screen shot 2016-02-29 at 8 21 16 am](https://cloud.githubusercontent.com/assets/4529964/13400622/7d5bdece-debd-11e5-836b-fb804ebc53f4.png)

Any ideas how I can fix this?

**Comment by p2** [comment]
Same problem here, not sure what's going on...

**Comment by matthewcheok** [comment]
I believe its a `min-width` CSS attribute imposed by the webpage...

**Comment by p2** [comment]
Yes, loading the login page in any browser and shrinking the window has the same effect. So a GitHub issue.

**Comment by p2** [comment]
Reported the issue, I'll close this as I don't think injecting JS or otherwise changing the CSS is in-scope for OAuth2. :)
