### ISSUE TITLE
Issues with Bitbucket

### ISSUE THREAD

**Issue by matthewcheok** [p2/OAuth2#96]
I'm getting errors with Bitbucket with the following configuration:

```
OAuth2CodeGrant(settings: [
    "client_id": "...",
    "client_secret": "...",
    "authorize_uri": "https://bitbucket.org/site/oauth2/authorize",
    "token_uri": "https://bitbucket.org/site/oauth2/access_token",
    "scope": "",
    "redirect_uris": ["..."],
    "title": "Bitbucket",
    ])
```

The error as follows:
```
{
  "error_description": "Requests must be authenticated using OAuth client credentials", 
  "error": "unauthorized_client"
}
```

Any ideas how I can fix this?

**Comment by p2** [comment]
It says your `client_id` and `client_secret` are invalid. Do you have credentials from BitBucket that you can use?

**Comment by matthewcheok** [comment]
The weird thing is that when I take the same params it works in a HTTP client like Paw.

**Comment by p2** [comment]
Indeed, I get the same error, although the request looks correct to when comparing [to their spec](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Authorizationcodegrant). Strange.

**Comment by matthewcheok** [comment]
<img width="989" alt="screen_shot_2016-03-10_at_7_49_12_am2" src="https://cloud.githubusercontent.com/assets/4529964/13675107/f7e901ba-e694-11e5-8d6d-76e0882b0df8.png">

**Comment by p2** [comment]
I've filed a support ticket with Atlasssian support.

**Comment by matthewcheok** [comment]
👍

**Comment by p2** [comment]
Yes, even using the same parameters from command line using _HTTPie_ I do get an access token. Very weird.

**Comment by matthewcheok** [comment]
Any updates so far?

**Comment by p2** [comment]
The Atlassian Dev team is taking a look (status as of yesterday after a bit back and forth). It appears you have to log in to [see the ticket BBS-29230](https://support.atlassian.com/servicedesk/customer/portal/11/BBS-29230).

**Comment by matthewcheok** [comment]
Seems I don't have permission to view that ticket. Thanks for following up with this!

**Comment by paketo-admin** [comment]
Hi,
You can below curl URL

$ curl -X POST -u "client_id:secret" 
https://bitbucket.org/site/oauth2/access_token -d grant_type=password 
-d username={username} -d password={password} /// this is API exposed by bitbucket

where
client_id : your client id (eg: 75frt****)
secret : your secret key (eg:8uyrioooreu*****)

username : 
password :

so above url will be updated as
$ curl -X POST -u "abc****:123****" 
https://bitbucket.org/site/oauth2/access_token -d grant_type=password 
-d username={abc123@gmail.com} -d password={******}

Note: Initially I was using alias username in 'username' field and I was facing error "Unauthorised client" error, later when I changed username to my registered email id [abc123@gmail.com], it worked fine.

Hope this helps.
