### ISSUE TITLE
localizedDescription memeber for errorType is not available

### ISSUE THREAD

**Issue by stephen-talari** [p2/OAuth2#97]
I am trying to print the error message, according to documentation `error!.localizedDescription` should give me the error message description but this fails saying 

> "ErrorType has no member 'localizedDescription' "

. 
Below is my code:
`let p2oauth2 = OAuth2PasswordGrant(settings: settings)`
`p2oauth2.authorize()`
`p2oauth2.onFailure = { error in`
           ` if nil != error {`
        `print("Authorization went wrong: \(error!.localizedDescription)")`
    `}`
        `}`
This code gives me following error
![screen shot 2016-03-17 at 12 22 30 pm](https://cloud.githubusercontent.com/assets/1725945/13838584/112e0d40-ec3b-11e5-8f31-bc6c07a9ddb6.png)

**Comment by p2** [comment]
Whoops, yeah, that's wrong and a remnant from NSError. You can just use the following, the readme has been fixed.

```swift
oauth2.onFailure = { error in        // `error` is nil on cancel
    if let error = error {
        print("Authorization went wrong: \(error)")
    }
}
```
