### ISSUE TITLE
OAuth client credentials edge case

### ISSUE THREAD

**Issue by squiffy** [p2/OAuth2#98]
I'm attempting to use this library for Reddit OAuth. Reddit offers two different types of OAuth. The first one is authenticating to a user. The second one is client only "userless" mode.

I want to use the "userless" mode. So, I looked into `OAuth2ClientCredentials`. It seems that Reddit's `grant_type` parameter is different on what they call "installed apps". So instead of the `grant_type` parameter being `client_credentials ` it needs to be `https://oauth.reddit.com/grants/installed_client`. 

Of course, if this issue can be solved with existing functionality of this library, I may have overlooked it.

I know this may sound strange, but thats how [reddit defines it](https://github.com/reddit/reddit/wiki/OAuth2).

As a proposed solution, being able to override default parameters in the `authorize(params:)` function would work.

**Comment by p2** [comment]
Seems to me it would be best to create a custom subclass of `OAuth2ClientCredentials` to handle all the [implementation details](https://github.com/reddit/reddit/wiki/OAuth2#application-only-oauth). That class could also hold on to the `device_id` parameter.

**Comment by squiffy** [comment]
Adding the `grant_type` through subclassing seems easy enough. However, I do not see an obvious way to add a custom parameter to the request. Before going forward, would you recommend a good way of doing this?

**Comment by p2** [comment]
I've added `OAuth2ClientCredentialsReddit`, can you pull latest `master` and see if it works?

**Comment by squiffy** [comment]
Yup, works like a charm. Thanks for your help 👍👍

**Comment by p2** [comment]
Great, thanks for testing!
